import { useStore } from '../state/store';
import type { Entity, EntityId, PenetrationSeal } from '../types';
import {
  autoDetectPenetrationsForContainment,
  autoPlaceFittingsForContainment,
  autoPlaceSupportsForContainment,
  removeAutoGeneratedFor,
} from './auto-features';

export interface RegenerateAutoFeaturesResult {
  containmentCount: number;
  removedCount: number;
  addedCount: number;
  sealCount: number;
}

export function regenerateAutoFeaturesForContainments(
  containmentIds: EntityId[],
): RegenerateAutoFeaturesResult {
  const uniqueIds = Array.from(new Set(containmentIds));
  if (uniqueIds.length === 0) {
    return { containmentCount: 0, removedCount: 0, addedCount: 0, sealCount: 0 };
  }

  const state = useStore.getState();
  const project = state.project;
  const sheetId = project.activeSheetId;
  const sheet = project.sheets[sheetId];
  if (!sheet) {
    return { containmentCount: 0, removedCount: 0, addedCount: 0, sealCount: 0 };
  }

  const validIds = uniqueIds.filter((id) => sheet.entities[id]?.kind === 'containment');
  if (validIds.length === 0) {
    return { containmentCount: 0, removedCount: 0, addedCount: 0, sealCount: 0 };
  }

  const staleIds = new Set<EntityId>();
  const staleSealIds = new Set<string>();
  for (const containmentId of validIds) {
    for (const staleId of removeAutoGeneratedFor(project, sheetId, containmentId)) {
      staleIds.add(staleId);
      const staleEntity = sheet.entities[staleId];
      if (staleEntity?.kind === 'penetration') staleSealIds.add(staleEntity.sealId);
    }
  }

  if (staleIds.size > 0) useStore.getState().removeEntities(Array.from(staleIds));

  if (staleSealIds.size > 0) {
    useStore.setState((s) => {
      const nextSeals = { ...(s.project.penetrationSeals ?? {}) };
      for (const sealId of staleSealIds) delete nextSeals[sealId];
      return {
        project: {
          ...s.project,
          penetrationSeals: nextSeals,
          modified: Date.now(),
        },
      };
    });
  }

  const refreshedProject = useStore.getState().project;
  const newEntities: Entity[] = [];
  let newSeals: Record<string, PenetrationSeal> = {};

  for (const containmentId of validIds) {
    newEntities.push(...autoPlaceFittingsForContainment(refreshedProject, sheetId, containmentId));
    newEntities.push(...autoPlaceSupportsForContainment(refreshedProject, sheetId, containmentId));
    const penetrationResult = autoDetectPenetrationsForContainment(refreshedProject, sheetId, containmentId);
    newEntities.push(...penetrationResult.penetrations);
    newSeals = { ...newSeals, ...penetrationResult.seals };
  }

  if (newEntities.length > 0) useStore.getState().addEntities(newEntities);

  const sealCount = Object.keys(newSeals).length;
  if (sealCount > 0) {
    useStore.setState((s) => ({
      project: {
        ...s.project,
        penetrationSeals: { ...(s.project.penetrationSeals ?? {}), ...newSeals },
        modified: Date.now(),
      },
    }));
  }

  return {
    containmentCount: validIds.length,
    removedCount: staleIds.size,
    addedCount: newEntities.length,
    sealCount,
  };
}
