import { useStore } from '../state/store';
import { shouldRejectLocalProjectMutation } from '../state/collaboration-guard';
import type { Entity, EntityId, PenetrationSeal, Project } from '../types';
import {
  autoDetectPenetrationsForContainment,
  autoPlaceFittingsForContainment,
  autoPlaceSupportsForContainment,
  removeAutoGeneratedFor,
} from './auto-features';

export interface RegenerateAutoFeaturesResult {
  containmentCount: number;
  removedCount: number;
  addedCount: number;
  sealCount: number;
  /** Existing identities reused instead of replacing their recorded history. */
  matchedCount: number;
  /** Recorded parts that could not be matched and now require manual review. */
  retainedCount: number;
}

type Accessory = Extract<Entity, { kind: 'fitting' | 'support' | 'penetration' }>;
const POSITION_TOLERANCE_MM = 1;
const isAccessory = (entity: Entity): entity is Accessory =>
  entity.kind === 'fitting' || entity.kind === 'support' || entity.kind === 'penetration';

const parentIds = (entity: Accessory): string[] =>
  entity.kind === 'support' ? [...entity.supportingContainmentIds].sort()
    : [entity.kind === 'fitting' ? entity.containmentId : entity.penetrationOf];

function matchesPart(a: Accessory, b: Accessory): boolean {
  if (a.kind !== b.kind || parentIds(a).join('\0') !== parentIds(b).join('\0')) return false;
  if (Math.hypot(a.position.x - b.position.x, a.position.y - b.position.y) > POSITION_TOLERANCE_MM) return false;
  if (a.kind === 'fitting' && b.kind === 'fitting') return a.fittingKind === b.fittingKind;
  if (a.kind === 'support' && b.kind === 'support') {
    return a.supportKind === b.supportKind
      && (a.elevation === b.elevation || (a.elevation != null && b.elevation != null
        && Math.abs(a.elevation - b.elevation) <= POSITION_TOLERANCE_MM));
  }
  return a.kind === 'penetration' && b.kind === 'penetration' && a.barrierEntityId === b.barrierEntityId;
}

function hasRecordedWork(entity: Accessory, project: Project): boolean {
  // Preserve even an empty/legacy installation record: regeneration must never
  // decide that a user's saved progress is disposable.
  if (entity.installation) return true;
  if (entity.kind !== 'penetration') return false;
  const seal = project.penetrationSeals?.[entity.sealId];
  if (!seal) return false;
  return seal.status !== 'flagged'
    || seal.sealType != null || seal.productId != null || seal.productPartNumber != null
    || seal.achievedRating != null || seal.openingWidth != null || seal.openingHeight != null
    || seal.inspectedBy != null || seal.inspectedAt != null || seal.certificateRef != null
    || !!seal.photoUrls?.length
    || (!!seal.notes && !/^Auto-flagged: [a-z-]+ crosses (?:\d+|fire-rated) wall$/.test(seal.notes));
}

// Fast identity comparison for shared histories, with value comparison for
// generated positions and reference arrays. Unchanged regeneration is a no-op.
function sameValues(a: object, b: object): boolean {
  const previous = a as Record<string, unknown>;
  const next = b as Record<string, unknown>;
  const keys = new Set([...Object.keys(previous), ...Object.keys(next)]);
  return [...keys].every(key => previous[key] === next[key]
    || JSON.stringify(previous[key]) === JSON.stringify(next[key]));
}

export function regenerateAutoFeaturesForContainments(containmentIds: EntityId[]): RegenerateAutoFeaturesResult {
  const result: RegenerateAutoFeaturesResult = {
    containmentCount: 0, removedCount: 0, addedCount: 0, sealCount: 0, matchedCount: 0, retainedCount: 0,
  };
  const state = useStore.getState();
  if (shouldRejectLocalProjectMutation()) {
    state.setStatus('Collaboration viewer: auto-feature edits are disabled');
    return result;
  }
  const project = state.project;
  const sheetId = project.activeSheetId;
  const sheet = project.sheets[sheetId];
  if (!sheet) return result;
  const validIds = [...new Set(containmentIds)].filter(id => sheet.entities[id]?.kind === 'containment');
  if (!validIds.length) return result;
  result.containmentCount = validIds.length;

  const staleIds = new Set(validIds.flatMap(id => removeAutoGeneratedFor(project, sheetId, id)));
  const requested = new Set(validIds);
  // Include matching manual accessories so a later regeneration cannot create
  // a duplicate on top of a recorded part previously retained for review.
  const candidates = Object.values(sheet.entities).filter(isAccessory)
    .filter(entity => parentIds(entity).some(id => requested.has(id)));
  const matchedIds = new Set<string>();
  const entities = { ...sheet.entities };
  const seals = { ...(project.penetrationSeals ?? {}) };
  const addedIds: string[] = [];
  let changed = false;

  const accept = (fresh: Accessory, freshSeal?: PenetrationSeal) => {
    const old = candidates.filter(candidate => !matchedIds.has(candidate.id) && matchesPart(candidate, fresh))
      .sort((a, b) => {
        const da = Math.hypot(a.position.x - fresh.position.x, a.position.y - fresh.position.y);
        const db = Math.hypot(b.position.x - fresh.position.x, b.position.y - fresh.position.y);
        return da - db || Number(hasRecordedWork(b, project)) - Number(hasRecordedWork(a, project));
      })[0];
    if (old) {
      matchedIds.add(old.id);
      result.matchedCount++;
      // Manual parts retain their explicitly placed geometry and visibility.
      // Auto parts receive refreshed geometry while keeping all site metadata.
      const updated: Accessory = old.autoGenerated
        ? { ...old, ...fresh, id: old.id, installation: old.installation, visible: old.visible, locked: old.locked }
        : old;
      if (old.kind === 'penetration' && updated.kind === 'penetration') {
        if (updated !== old) updated.sealId = old.sealId;
        if (freshSeal) {
          const oldSeal = seals[old.sealId];
          const nextSeal = oldSeal
            ? { ...freshSeal, ...oldSeal, crossingPoint: updated.position, requiredRating: freshSeal.requiredRating }
            : { ...freshSeal, id: old.sealId };
          if (!oldSeal || !sameValues(oldSeal, nextSeal)) {
            seals[old.sealId] = nextSeal;
            changed = true;
          }
        }
      }
      if (!sameValues(old, updated)) {
        entities[old.id] = updated;
        changed = true;
      }
      return;
    }
    entities[fresh.id] = fresh;
    addedIds.push(fresh.id);
    result.addedCount++;
    if (fresh.kind === 'penetration' && freshSeal) {
      seals[fresh.sealId] = freshSeal;
      result.sealCount++;
    }
    changed = true;
  };

  // Stage everything in memory first. A generator failure cannot leave half a
  // regeneration committed or temporarily remove timeline entries.
  for (const containmentId of validIds) {
    const generationProject = { ...project, penetrationSeals: seals };
    for (const fresh of [
      ...autoPlaceFittingsForContainment(generationProject, sheetId, containmentId),
      ...autoPlaceSupportsForContainment(generationProject, sheetId, containmentId),
    ]) if (isAccessory(fresh)) accept(fresh);
    const penetrations = autoDetectPenetrationsForContainment(generationProject, sheetId, containmentId);
    for (const fresh of penetrations.penetrations) {
      if (fresh.kind === 'penetration') accept(fresh, penetrations.seals[fresh.sealId]);
    }
  }

  for (const id of staleIds) {
    if (matchedIds.has(id)) continue;
    const old = sheet.entities[id];
    if (!old || !isAccessory(old)) continue;
    if (hasRecordedWork(old, project)) {
      entities[id] = { ...old, autoGenerated: false };
      result.retainedCount++;
    } else {
      delete entities[id];
      result.removedCount++;
    }
    changed = true;
  }
  if (!changed) return result;

  const sheets = { ...project.sheets, [sheetId]: {
    ...sheet, entities, entityOrder: [...sheet.entityOrder.filter(id => !!entities[id]), ...addedIds],
  } };
  // Remove only obsolete auto seals, and only if no sheet still references one.
  const referencedSeals = new Set(Object.values(sheets).flatMap(s =>
    Object.values(s.entities).flatMap(entity => entity.kind === 'penetration' ? [entity.sealId] : [])));
  for (const id of staleIds) {
    const old = sheet.entities[id];
    if (old?.kind === 'penetration' && !referencedSeals.has(old.sealId)) delete seals[old.sealId];
  }
  state.setProjectPatch({ sheets, penetrationSeals: seals });
  if (result.removedCount) {
    const selection = [...state.editor.selection].filter(id => !!entities[id]);
    if (selection.length !== state.editor.selection.size) useStore.getState().setSelection(selection);
  }
  if (result.retainedCount) {
    useStore.getState().setStatus(
      'Auto-features regenerated; ' + result.retainedCount + ' recorded part'
      + (result.retainedCount === 1 ? '' : 's') + ' retained as manual for review',
    );
  }
  return result;
}
