// Auto-feature generation for containment runs.
//
// Given a freshly committed (or moved) containment, derive the fittings,
// supports, and fire-stop penetrations it requires and return them as
// pure data — the caller decides when to dispatch to the store.
//
// All emitted entities carry `autoGenerated: true` and either reference
// the parent containment (`containmentId`) or a wall (`barrierEntityId`)
// so they can be diffed and removed when the containment changes.
import { nanoid } from 'nanoid';
import type {
  Entity,
  EntityId,
  Project,
  SheetId,
  Vec2,
  ContainmentEntity,
  WallEntity,
  PenetrationEntity,
  PenetrationSeal,
} from '../types';
import { detectFittings } from './fittings';
import { placeSupportsForContainment } from './support-placer';
import { segIntersect } from './math';

const findContainment = (
  project: Project,
  sheetId: SheetId,
  containmentId: EntityId,
): ContainmentEntity | null => {
  const sheet = project.sheets[sheetId];
  if (!sheet) return null;
  const e = sheet.entities[containmentId];
  if (!e || e.kind !== 'containment') return null;
  return e;
};

const otherContainmentsOnSheet = (
  project: Project,
  sheetId: SheetId,
  selfId: EntityId,
): ContainmentEntity[] => {
  const sheet = project.sheets[sheetId];
  if (!sheet) return [];
  const out: ContainmentEntity[] = [];
  for (const id of sheet.entityOrder) {
    const e = sheet.entities[id];
    if (e && e.kind === 'containment' && e.id !== selfId) out.push(e);
  }
  return out;
};

const fireRatedWallsOnSheet = (project: Project, sheetId: SheetId): WallEntity[] => {
  const sheet = project.sheets[sheetId];
  if (!sheet) return [];
  const out: WallEntity[] = [];
  for (const id of sheet.entityOrder) {
    const e = sheet.entities[id];
    if (e && e.kind === 'wall' && e.fireRating) out.push(e);
  }
  return out;
};

// Find the next available "FS-NNN" reference given a map of existing seals.
const nextSealReference = (existing: Record<string, PenetrationSeal> | undefined): string => {
  let highest = 0;
  if (existing) {
    for (const seal of Object.values(existing)) {
      const m = /^FS-(\d+)$/.exec(seal.reference);
      if (m) {
        const n = parseInt(m[1], 10);
        if (n > highest) highest = n;
      }
    }
  }
  const next = highest + 1;
  return `FS-${String(next).padStart(3, '0')}`;
};

export const autoPlaceFittingsForContainment = (
  project: Project,
  sheetId: SheetId,
  containmentId: EntityId,
): Entity[] => {
  const containment = findContainment(project, sheetId, containmentId);
  if (!containment) return [];
  const others = otherContainmentsOnSheet(project, sheetId, containmentId);
  return detectFittings(containment, others);
};

export const autoPlaceSupportsForContainment = (
  project: Project,
  sheetId: SheetId,
  containmentId: EntityId,
): Entity[] => {
  const containment = findContainment(project, sheetId, containmentId);
  if (!containment) return [];
  return placeSupportsForContainment(containment);
};

export interface AutoPenetrationsResult {
  penetrations: Entity[];
  seals: Record<string, PenetrationSeal>;
}

const segmentsIntersect = (a1: Vec2, a2: Vec2, b1: Vec2, b2: Vec2): Vec2 | null =>
  segIntersect(a1, a2, b1, b2);

export const autoDetectPenetrationsForContainment = (
  project: Project,
  sheetId: SheetId,
  containmentId: EntityId,
): AutoPenetrationsResult => {
  const containment = findContainment(project, sheetId, containmentId);
  if (!containment) return { penetrations: [], seals: {} };
  const walls = fireRatedWallsOnSheet(project, sheetId);
  if (walls.length === 0) return { penetrations: [], seals: {} };

  const penetrations: Entity[] = [];
  const seals: Record<string, PenetrationSeal> = {};
  const existing = { ...(project.penetrationSeals ?? {}) };

  for (const wall of walls) {
    if (wall.points.length < 2) continue;
    for (let i = 0; i < containment.points.length - 1; i++) {
      const a1 = containment.points[i];
      const a2 = containment.points[i + 1];
      for (let j = 0; j < wall.points.length - 1; j++) {
        const b1 = wall.points[j];
        const b2 = wall.points[j + 1];
        const hit = segmentsIntersect(a1, a2, b1, b2);
        if (!hit) continue;

        const sealId = nanoid(10);
        const reference = nextSealReference({ ...existing, ...seals });

        const penEntity: PenetrationEntity = {
          id: nanoid(10),
          kind: 'penetration',
          layerId: containment.layerId,
          visible: true,
          locked: false,
          position: hit,
          barrierEntityId: wall.id,
          penetrationOf: containment.id,
          sealId,
          autoGenerated: true,
        };
        penetrations.push(penEntity);

        seals[sealId] = {
          id: sealId,
          reference,
          status: 'flagged',
          requiredRating: wall.fireRating ?? 60,
          boundaryEntityId: wall.id,
          penetrationEntityId: containment.id,
          crossingPoint: hit,
          notes: `Auto-flagged: ${containment.containmentType} crosses ${wall.fireRating ?? 'fire-rated'} wall`,
        };
      }
    }
  }

  return { penetrations, seals };
};

// Find all auto-generated supports/fittings/penetrations attached to a
// given containment so the caller can remove them when the containment
// is deleted or its geometry changes.
export const removeAutoGeneratedFor = (
  project: Project,
  sheetId: SheetId,
  containmentId: EntityId,
): EntityId[] => {
  const sheet = project.sheets[sheetId];
  if (!sheet) return [];
  const ids: EntityId[] = [];
  for (const id of sheet.entityOrder) {
    const e = sheet.entities[id];
    if (!e) continue;
    if (e.kind === 'fitting' && e.autoGenerated && e.containmentId === containmentId) ids.push(id);
    else if (
      e.kind === 'support' &&
      e.autoGenerated &&
      e.supportingContainmentIds.includes(containmentId)
    ) ids.push(id);
    else if (e.kind === 'penetration' && e.autoGenerated && e.penetrationOf === containmentId) ids.push(id);
  }
  return ids;
};
