// Auto-detection of containment fittings from polyline geometry.
//
// Given a containment route as a polyline plus the surrounding network of
// other containments, this module derives the fittings that physically
// must exist on the route:
//
//   - Direction changes  → flat-bend (with snapped angle 30/45/60/90)
//   - Junctions with 1 other containment touching at endpoint → tee
//   - Junctions with 2 other containments touching at endpoint → cross
//   - Free endpoints  → end-cap
//   - Stock-length boundaries → coupler
//
// All generated fittings are marked `autoGenerated: true` so the system
// can re-derive them when the polyline changes without losing user-placed
// custom fittings.
//
// Pure functions — no side effects on the input entities.
import { nanoid } from 'nanoid';
import type {
  ContainmentEntity,
  FittingEntity,
  FittingKind,
  Vec2,
  EntityId,
  LayerId,
} from '../types';
import { dist, sub, RAD2DEG } from './math';

// Angular tolerance for "no direction change" (degrees).
// Anything less than this is treated as a straight run.
const ANGLE_NOOP_DEG = 5;

// Distance tolerance for "endpoint coincidence" (mm).
const ENDPOINT_TOL_MM = 10;

// Default standard stock length for straight containment (mm).
// 3000 mm (3m) is the de-facto industry default for tray/trunking.
const DEFAULT_STOCK_LENGTH_MM = 3000;

// Snap a deflection angle to one of the standard fitting angles
// 30 / 45 / 60 / 90 degrees. The input is expected to be the
// magnitude of the direction change (0..180).
const SNAP_ANGLES: readonly number[] = [30, 45, 60, 90];

export interface JunctionClassification {
  kind: FittingKind;
  angleDeg?: number;
}

export interface DetectFittingsOptions {
  // Override stock length (mm). Defaults to 3000.
  stockLength?: number;
  // Layer to assign to fittings. Defaults to the parent containment layer.
  layerId?: LayerId;
}

// Compute total length of a polyline in mm.
export function polylineLength(points: Vec2[]): number {
  let total = 0;
  for (let i = 1; i < points.length; i++) {
    total += dist(points[i - 1], points[i]);
  }
  return total;
}

// Snap a deflection magnitude (in degrees) to the nearest standard
// fitting angle (30/45/60/90).
function snapAngleToStandard(deflectionDeg: number): number {
  let best = SNAP_ANGLES[0];
  let bestDelta = Math.abs(deflectionDeg - best);
  for (const candidate of SNAP_ANGLES) {
    const delta = Math.abs(deflectionDeg - candidate);
    if (delta < bestDelta) {
      best = candidate;
      bestDelta = delta;
    }
  }
  return best;
}

// Magnitude of direction change at vertex i of a polyline.
// Returns 0 for a straight run, up to 180 for a U-turn.
function deflectionAt(points: Vec2[], i: number): number {
  if (i <= 0 || i >= points.length - 1) return 0;
  const a = sub(points[i], points[i - 1]);
  const b = sub(points[i + 1], points[i]);
  const la = Math.hypot(a.x, a.y);
  const lb = Math.hypot(b.x, b.y);
  if (la < 1e-6 || lb < 1e-6) return 0;
  const cosTheta = (a.x * b.x + a.y * b.y) / (la * lb);
  // Clamp for numerical safety
  const c = Math.min(1, Math.max(-1, cosTheta));
  return Math.acos(c) * RAD2DEG;
}

// Direction angle in radians from segment a→b.
function segAngle(a: Vec2, b: Vec2): number {
  return Math.atan2(b.y - a.y, b.x - a.x);
}

// Test if two points are coincident within tolerance.
function nearlyEqual(a: Vec2, b: Vec2, tol = ENDPOINT_TOL_MM): boolean {
  return dist(a, b) <= tol;
}

function pointToSegmentDistance(p: Vec2, a: Vec2, b: Vec2): number {
  const dx = b.x - a.x;
  const dy = b.y - a.y;
  const lenSq = dx * dx + dy * dy;
  if (lenSq < 1e-9) return dist(p, a);
  const t = Math.max(0, Math.min(1, ((p.x - a.x) * dx + (p.y - a.y) * dy) / lenSq));
  return dist(p, { x: a.x + dx * t, y: a.y + dy * t });
}

export function containmentTouchesPoint(
  containment: ContainmentEntity,
  p: Vec2,
  tol = ENDPOINT_TOL_MM,
): boolean {
  if (!containment.points || containment.points.length < 2) return false;
  for (const vertex of containment.points) {
    if (nearlyEqual(p, vertex, tol)) return true;
  }
  for (let i = 0; i < containment.points.length - 1; i++) {
    if (pointToSegmentDistance(p, containment.points[i], containment.points[i + 1]) <= tol) {
      return true;
    }
  }
  return false;
}

// Count how many other containments touch `p` (excluding self). Branches
// often join a spine at an interior vertex or along a straight segment, not
// only at the spine endpoint.
function endpointConnections(
  p: Vec2,
  selfId: EntityId,
  others: ContainmentEntity[]
): ContainmentEntity[] {
  const hits: ContainmentEntity[] = [];
  for (const o of others) {
    if (o.id === selfId) continue;
    if (containmentTouchesPoint(o, p)) hits.push(o);
  }
  return hits;
}

// Classify a junction given the connection point and the network of
// surrounding containments. Used both for endpoints (end-cap / tee /
// cross) and for direction changes (flat-bend).
export function classifyJunction(
  p: Vec2,
  containments: ContainmentEntity[],
  selfId?: EntityId
): JunctionClassification {
  const connections = endpointConnections(p, selfId ?? '', containments);
  if (connections.length === 0) {
    return { kind: 'end-cap' };
  }
  if (connections.length === 1) {
    return { kind: 'tee' };
  }
  // 2+ touching: treat as a cross fitting
  return { kind: 'cross' };
}

// Pick the larger or equal sized neighbour. We only place tees / crosses
// when the connecting containment is the same or larger than the parent.
function isSameOrLarger(self: ContainmentEntity, other: ContainmentEntity): boolean {
  const selfW = self.width ?? 0;
  const selfH = self.height ?? 0;
  const otherW = other.width ?? 0;
  const otherH = other.height ?? 0;
  // Compare cross-section area as a simple proxy
  return otherW * otherH >= selfW * selfH;
}

// Auto-detect every fitting required by a containment polyline.
//
// The output is unstable in id (each call generates new nanoids) so the
// caller is responsible for diffing against any user-placed fittings
// they want to preserve.
export function detectFittings(
  containment: ContainmentEntity,
  otherContainments: ContainmentEntity[] = [],
  options: DetectFittingsOptions = {}
): FittingEntity[] {
  const { points } = containment;
  if (!points || points.length < 2) return [];

  const stockLength = options.stockLength ?? DEFAULT_STOCK_LENGTH_MM;
  const layerId = options.layerId ?? containment.layerId;
  const fittings: FittingEntity[] = [];

  // 1) Direction changes → flat-bend
  for (let i = 1; i < points.length - 1; i++) {
    const deflection = deflectionAt(points, i);
    if (deflection < ANGLE_NOOP_DEG) continue;
    const angleDeg = snapAngleToStandard(deflection);
    const incoming = segAngle(points[i - 1], points[i]);
    fittings.push({
      id: nanoid(),
      kind: 'fitting',
      fittingKind: 'flat-bend',
      layerId,
      visible: true,
      locked: false,
      position: { x: points[i].x, y: points[i].y },
      rotation: incoming,
      angleDeg,
      containmentId: containment.id,
      width: containment.width,
      height: containment.height,
      autoGenerated: true,
    });
  }

  // 2) Endpoints → end-cap, tee, or cross
  const endpoints: { p: Vec2; rot: number }[] = [
    { p: points[0], rot: segAngle(points[1], points[0]) },
    {
      p: points[points.length - 1],
      rot: segAngle(points[points.length - 2], points[points.length - 1]),
    },
  ];
  for (const ep of endpoints) {
    const cls = classifyJunction(ep.p, otherContainments, containment.id);
    let fittingKind: FittingKind = cls.kind;
    if (fittingKind === 'tee' || fittingKind === 'cross') {
      // Only count tees/crosses where neighbours are same/larger size.
      const neighbours = endpointConnections(
        ep.p,
        containment.id,
        otherContainments
      );
      const compatible = neighbours.filter((n) => isSameOrLarger(containment, n));
      if (compatible.length === 0) {
        fittingKind = 'end-cap';
      } else if (compatible.length === 1) {
        fittingKind = 'tee';
      } else {
        fittingKind = 'cross';
      }
    }
    fittings.push({
      id: nanoid(),
      kind: 'fitting',
      fittingKind,
      layerId,
      visible: true,
      locked: false,
      position: { x: ep.p.x, y: ep.p.y },
      rotation: ep.rot,
      containmentId: containment.id,
      width: containment.width,
      height: containment.height,
      autoGenerated: true,
    });
  }

  // 3) Stock-length boundaries → couplers
  // Walk along the polyline and emit a coupler at every multiple of
  // stockLength. Skip vertices that already coincide with a bend.
  let cumulative = 0;
  let nextCouplerAt = stockLength;
  for (let i = 1; i < points.length; i++) {
    const a = points[i - 1];
    const b = points[i];
    const segLen = dist(a, b);
    if (segLen < 1e-6) continue;
    while (cumulative + segLen >= nextCouplerAt) {
      const tInSeg = (nextCouplerAt - cumulative) / segLen;
      const couplerPos: Vec2 = {
        x: a.x + (b.x - a.x) * tInSeg,
        y: a.y + (b.y - a.y) * tInSeg,
      };
      // Skip if this coupler position is too close to a vertex (bend
      // point) — the bend already serves as a joint.
      const nearVertex = points.some((p) => nearlyEqual(p, couplerPos, 100));
      if (!nearVertex) {
        fittings.push({
          id: nanoid(),
          kind: 'fitting',
          fittingKind: 'coupler',
          layerId,
          visible: true,
          locked: false,
          position: couplerPos,
          rotation: segAngle(a, b),
          containmentId: containment.id,
          width: containment.width,
          height: containment.height,
          autoGenerated: true,
        });
      }
      nextCouplerAt += stockLength;
    }
    cumulative += segLen;
  }

  return fittings;
}
