// Auto-detection of containment fittings from polyline geometry.
//
// Given a containment route as a polyline plus the surrounding network of
// other containments, this module derives the fittings that physically
// must exist on the route:
//
//   - Direction changes  → flat-bend (with snapped angle 30/45/60/90)
//   - Connected ends → coupler or bend; three/four directions → tee/cross
//   - Free endpoints  → end-cap
//   - Stock-length boundaries → coupler
//
// All generated fittings are marked `autoGenerated: true` so the system
// can re-derive them when the polyline changes without losing user-placed
// custom fittings.
//
// Pure functions — no side effects on the input entities.
import { nanoid } from 'nanoid';
import type {
  ContainmentEntity,
  FittingEntity,
  FittingKind,
  RoutePoint,
  EntityId,
  LayerId,
} from '../types';
import { RAD2DEG } from './math';
import { closestOnPath, distance3 as dist, pathLength, routePath } from './route-path';

// Angular tolerance for "no direction change" (degrees).
// Anything less than this is treated as a straight run.
const ANGLE_NOOP_DEG = 5;

// Distance tolerance for "endpoint coincidence" (mm).
const ENDPOINT_TOL_MM = 10;

// Default standard stock length for straight containment (mm).
// 3000 mm (3m) is the de-facto industry default for tray/trunking.
const DEFAULT_STOCK_LENGTH_MM = 3000;

// Snap a deflection angle to one of the standard fitting angles
// 30 / 45 / 60 / 90 degrees. The input is expected to be the
// magnitude of the direction change (0..180).
const SNAP_ANGLES: readonly number[] = [30, 45, 60, 90];

export interface JunctionClassification {
  kind: FittingKind;
  angleDeg?: number;
}

export interface DetectFittingsOptions {
  // Override stock length (mm). Defaults to 3000.
  stockLength?: number;
  // Layer to assign to fittings. Defaults to the parent containment layer.
  layerId?: LayerId;
  // A locked reference may be connected to without assigning new parts to it.
  canOwnJunction?: (containment: ContainmentEntity) => boolean;
}

// Compute total length of a polyline in mm.
export function polylineLength(points: RoutePoint[]): number {
  return pathLength(points);
}

// Snap a deflection magnitude (in degrees) to the nearest standard
// fitting angle (30/45/60/90).
function snapAngleToStandard(deflectionDeg: number): number {
  let best = SNAP_ANGLES[0];
  let bestDelta = Math.abs(deflectionDeg - best);
  for (const candidate of SNAP_ANGLES) {
    const delta = Math.abs(deflectionDeg - candidate);
    if (delta < bestDelta) {
      best = candidate;
      bestDelta = delta;
    }
  }
  return best;
}

// Magnitude of direction change at vertex i of a polyline.
// Returns 0 for a straight run, up to 180 for a U-turn.
function deflectionAt(points: RoutePoint[], i: number): number {
  if (i <= 0 || i >= points.length - 1) return 0;
  const a = { x: points[i].x - points[i - 1].x, y: points[i].y - points[i - 1].y, z: (points[i].z ?? 0) - (points[i - 1].z ?? 0) };
  const b = { x: points[i + 1].x - points[i].x, y: points[i + 1].y - points[i].y, z: (points[i + 1].z ?? 0) - (points[i].z ?? 0) };
  const la = Math.hypot(a.x, a.y, a.z);
  const lb = Math.hypot(b.x, b.y, b.z);
  if (la < 1e-6 || lb < 1e-6) return 0;
  const cosTheta = (a.x * b.x + a.y * b.y + a.z * b.z) / (la * lb);
  // Clamp for numerical safety
  const c = Math.min(1, Math.max(-1, cosTheta));
  return Math.acos(c) * RAD2DEG;
}

// Direction angle in radians from segment a→b.
function segAngle(a: RoutePoint, b: RoutePoint): number {
  return Math.atan2(b.y - a.y, b.x - a.x);
}

// Test if two points are coincident within tolerance.
function nearlyEqual(a: RoutePoint, b: RoutePoint, tol = ENDPOINT_TOL_MM): boolean {
  return dist(a, b) <= tol;
}

function pointToSegmentDistance(p: RoutePoint, a: RoutePoint, b: RoutePoint): number {
  return closestOnPath({ ...p, z: p.z ?? 0 }, [{ ...a, z: a.z ?? 0 }, { ...b, z: b.z ?? 0 }])?.distance ?? dist(p, a);
}

export function containmentTouchesPoint(
  containment: ContainmentEntity,
  p: RoutePoint,
  tol = ENDPOINT_TOL_MM,
): boolean {
  if (!containment.points || containment.points.length < 2) return false;
  const points = p.z == null ? containment.points.map(({ x, y }) => ({ x, y })) : routePath(containment);
  for (const vertex of points) {
    if (nearlyEqual(p, vertex, tol)) return true;
  }
  for (let i = 0; i < points.length - 1; i++) {
    if (pointToSegmentDistance(p, points[i], points[i + 1]) <= tol) {
      return true;
    }
  }
  return false;
}

// Count how many other containments touch `p` (excluding self). Branches
// often join a spine at an interior vertex or along a straight segment, not
// only at the spine endpoint.
function endpointConnections(
  p: RoutePoint,
  selfId: EntityId,
  others: ContainmentEntity[]
): ContainmentEntity[] {
  const hits: ContainmentEntity[] = [];
  for (const o of others) {
    if (o.id === selfId) continue;
    if (containmentTouchesPoint(o, p)) hits.push(o);
  }
  return hits;
}

// Classify a junction given the connection point and the network of
// surrounding containments. Used both for endpoints (end-cap / tee /
// cross) and for direction changes (flat-bend).
export function classifyJunction(
  p: RoutePoint,
  containments: ContainmentEntity[],
  selfId?: EntityId,
  source?: ContainmentEntity,
): JunctionClassification {
  const connections = endpointConnections(p, selfId ?? '', containments);
  if (!connections.length) return { kind: 'end-cap' };
  const owner = source ?? containments.find(entity => entity.id === selfId);
  const directions: { x: number; y: number; z: number }[] = [];
  const addDirection = (point: RoutePoint) => {
    const length = dist(p, point);
    if (length <= ENDPOINT_TOL_MM) return;
    const direction = { x: (point.x - p.x) / length, y: (point.y - p.y) / length, z: ((point.z ?? 0) - (p.z ?? 0)) / length };
    if (!directions.some(other => other.x * direction.x + other.y * direction.y + other.z * direction.z > Math.cos(ANGLE_NOOP_DEG * Math.PI / 180))) directions.push(direction);
  };
  for (const route of owner ? [owner, ...connections] : connections) {
    const path = p.z == null ? route.points.map(({ x, y }) => ({ x, y })) : routePath(route);
    for (let index = 1; index < path.length; index++) {
      const a = path[index - 1], b = path[index];
      if (pointToSegmentDistance(p, a, b) <= ENDPOINT_TOL_MM) { addDirection(a); addDirection(b); }
    }
  }
  const branches = directions.length + (owner ? 0 : 1);
  if (branches >= 4) return { kind: 'cross' };
  if (branches === 3) return { kind: 'tee' };
  if (directions.length === 2 && owner) {
    const dot = directions[0].x * directions[1].x + directions[0].y * directions[1].y + directions[0].z * directions[1].z;
    const deflection = 180 - Math.acos(Math.max(-1, Math.min(1, dot))) * 180 / Math.PI;
    if (deflection >= ANGLE_NOOP_DEG) return { kind: directions.some(d => Math.abs(d.z) > 0.01) ? 'inside-riser' : 'flat-bend', angleDeg: snapAngleToStandard(deflection) };
  }
  return { kind: 'coupler' };
}

// Auto-detect every fitting required by a containment polyline.
//
// The output is unstable in id (each call generates new nanoids) so the
// caller is responsible for diffing against any user-placed fittings
// they want to preserve.
export function detectFittings(
  containment: ContainmentEntity,
  otherContainments: ContainmentEntity[] = [],
  options: DetectFittingsOptions = {}
): FittingEntity[] {
  containment = { ...containment, points: routePath(containment) };
  otherContainments = otherContainments.map(route => ({ ...route, points: routePath(route) }));
  const { points } = containment;
  if (!points || points.length < 2) return [];

  const stockLength = options.stockLength ?? DEFAULT_STOCK_LENGTH_MM;
  const layerId = options.layerId ?? containment.layerId;
  const fittings: FittingEntity[] = [];

  // 1) Direction changes → flat-bend
  for (let i = 1; i < points.length - 1; i++) {
    if (endpointConnections(points[i], containment.id, otherContainments).length) continue;
    const deflection = deflectionAt(points, i);
    if (deflection < ANGLE_NOOP_DEG) continue;
    const angleDeg = snapAngleToStandard(deflection);
    const incoming = segAngle(points[i - 1], points[i]);
    const incomingZ = (points[i].z ?? 0) - (points[i - 1].z ?? 0);
    const outgoingZ = (points[i + 1].z ?? 0) - (points[i].z ?? 0);
    fittings.push({
      id: nanoid(),
      kind: 'fitting',
      fittingKind: Math.abs(incomingZ) + Math.abs(outgoingZ) < 0.01 ? 'flat-bend' : outgoingZ > incomingZ ? 'inside-riser' : 'outside-riser',
      layerId,
      visible: true,
      locked: false,
      position: { x: points[i].x, y: points[i].y },
      elevation: points[i].z,
      rotation: incoming,
      angleDeg,
      containmentId: containment.id,
      width: containment.width,
      height: containment.height,
      autoGenerated: true,
    });
  }

  // 2) Network joints include branches landing midway along a straight spine.
  const endpoints: { p: RoutePoint; rot: number }[] = [
    { p: points[0], rot: segAngle(points[1], points[0]) },
    {
      p: points[points.length - 1],
      rot: segAngle(points[points.length - 2], points[points.length - 1]),
    },
  ];
  for (const other of otherContainments) {
    for (const point of [other.points[0], other.points.at(-1)]) {
      if (!point || !containmentTouchesPoint(containment, point) || endpoints.some(ep => nearlyEqual(ep.p, point))) continue;
      const segment = points.findIndex((p, i) => i > 0 && pointToSegmentDistance(point, points[i - 1], p) <= ENDPOINT_TOL_MM);
      if (segment > 0) endpoints.push({ p: point, rot: segAngle(points[segment - 1], points[segment]) });
    }
  }
  for (const ep of endpoints) {
    const neighbours = endpointConnections(ep.p, containment.id, otherContainments);
    // One saved joint per physical connection, with a stable owner across regenerations.
    const owners = [containment, ...neighbours].filter(route => options.canOwnJunction?.(route) ?? true);
    if (neighbours.length && owners.map(route => route.id).sort()[0] !== containment.id) continue;
    const cls = classifyJunction(ep.p, otherContainments, containment.id, containment);
    const fittingKind: FittingKind = cls.kind;
    fittings.push({
      id: nanoid(),
      kind: 'fitting',
      fittingKind,
      ...(cls.angleDeg != null ? { angleDeg: cls.angleDeg } : {}),
      layerId,
      visible: true,
      locked: false,
      position: { x: ep.p.x, y: ep.p.y },
      elevation: ep.p.z,
      rotation: ep.rot,
      containmentId: containment.id,
      width: containment.width,
      height: containment.height,
      autoGenerated: true,
    });
  }

  // 3) Stock-length boundaries → couplers
  // Walk along the polyline and emit a coupler at every multiple of
  // stockLength. Skip vertices that already coincide with a bend.
  let cumulative = 0;
  let nextCouplerAt = stockLength;
  for (let i = 1; i < points.length; i++) {
    const a = points[i - 1];
    const b = points[i];
    const segLen = dist(a, b);
    if (segLen < 1e-6) continue;
    while (cumulative + segLen >= nextCouplerAt) {
      const tInSeg = (nextCouplerAt - cumulative) / segLen;
      const couplerPos: RoutePoint = {
        x: a.x + (b.x - a.x) * tInSeg,
        y: a.y + (b.y - a.y) * tInSeg,
        z: (a.z ?? 0) + ((b.z ?? 0) - (a.z ?? 0)) * tInSeg,
      };
      // Skip if this coupler position is too close to a vertex (bend
      // point) — the bend already serves as a joint.
      const nearVertex = points.some((p) => nearlyEqual(p, couplerPos, 100))
        || fittings.some(fitting => nearlyEqual({ ...fitting.position, z: fitting.elevation }, couplerPos, 100));
      if (!nearVertex) {
        fittings.push({
          id: nanoid(),
          kind: 'fitting',
          fittingKind: 'coupler',
          layerId,
          visible: true,
          locked: false,
          position: { x: couplerPos.x, y: couplerPos.y },
          elevation: couplerPos.z,
          rotation: segAngle(a, b),
          containmentId: containment.id,
          width: containment.width,
          height: containment.height,
          autoGenerated: true,
        });
      }
      nextCouplerAt += stockLength;
    }
    cumulative += segLen;
  }

  return fittings;
}
