// Support placer — auto-derive the SupportEntity records required to
// physically suspend a containment run.
//
// Spacing follows BS EN 61537 / manufacturer load tables (encoded in
// SUPPORT_SPANS_HORIZONTAL_MM). The placer also adds an extra support
// within 300 mm of every direction change, junction or end so the run
// is safely terminated against pull-out forces (per IET GN8 §6).
//
// All generated supports are flagged `autoGenerated: true` so they can
// be re-placed when the containment route is edited.
import { nanoid } from 'nanoid';
import type {
  ContainmentEntity,
  ContainmentType,
  SupportEntity,
  SupportKind,
  Vec2,
  LayerId,
} from '../types';
import { SUPPORT_SPANS_HORIZONTAL_MM } from '../models/standards';
import { dist } from './math';
import { polylineLength } from './fittings';

// Distance from a vertex (bend / tee / end) within which a support must
// be placed in addition to the regular span supports (mm).
const VERTEX_SUPPORT_DISTANCE_MM = 300;

// Default trapeze rod length in mm — assumes a 600 mm ceiling void.
const DEFAULT_ROD_LENGTH_MM = 500;

export interface SupportPlacerOptions {
  // Override the calculated max span (mm).
  maxSpanMm?: number;
  // Layer to assign the supports to (defaults to parent layer).
  layerId?: LayerId;
  // Override anchor type — 'expansion' (drilled into concrete) by default.
  anchorType?: SupportEntity['anchorType'];
  // Force a particular support kind, overriding the heuristic.
  supportKind?: SupportKind;
}

// Snap a containment width to the closest size key in the support span
// table. Keys are in mm.
function nearestKey(table: Record<number, number>, w: number): number {
  const keys = Object.keys(table).map((k) => Number(k));
  if (keys.length === 0) return w;
  let best = keys[0];
  let bestDelta = Math.abs(w - best);
  for (const k of keys) {
    const d = Math.abs(w - k);
    if (d < bestDelta) {
      best = k;
      bestDelta = d;
    }
  }
  return best;
}

// Lookup the recommended max horizontal span (centre-to-centre) for a
// given containment type and width. Falls back to a conservative default
// when no entry exists.
export function maxSpanForContainment(
  type: ContainmentType,
  width: number,
  material?: ContainmentEntity['material']
): number {
  const t = SUPPORT_SPANS_HORIZONTAL_MM as Readonly<
    Record<string, Record<number, number>>
  >;
  let table: Record<number, number> | undefined;
  switch (type) {
    case 'ladder':
      table = t.ladder;
      break;
    case 'tray':
      table = t.tray;
      break;
    case 'basket':
      table = t.basket;
      break;
    case 'trunking':
      table = t.trunking;
      break;
    case 'conduit': {
      const isPlastic =
        material === 'pvc' || material === 'lsoh' || material === 'grp';
      table = isPlastic ? t.conduit_pvc : t.conduit_steel;
      break;
    }
    default:
      table = undefined;
  }
  if (!table) return 1500;
  const key = nearestKey(table, width);
  return table[key] ?? 1500;
}

// Pick a sensible support kind based on the containment shape.
function pickSupportKind(c: ContainmentEntity): SupportKind {
  if (c.containmentType === 'conduit') return 'saddle-clip';
  const w = c.width ?? 0;
  if (w < 300) return 'wall-bracket';
  return 'trapeze-hanger';
}

// Walk a polyline and emit the (x,y) of every point at a given cumulative
// distance from the start. Stops at the end of the polyline.
function pointAtDistance(points: Vec2[], distance: number): Vec2 | null {
  let cumulative = 0;
  for (let i = 1; i < points.length; i++) {
    const a = points[i - 1];
    const b = points[i];
    const segLen = dist(a, b);
    if (cumulative + segLen >= distance) {
      const t = (distance - cumulative) / segLen;
      return { x: a.x + (b.x - a.x) * t, y: a.y + (b.y - a.y) * t };
    }
    cumulative += segLen;
  }
  return null;
}

// Test if a candidate support position is within tolerance of any
// existing support. Used to dedupe vertex supports against span supports.
function tooCloseTo(existing: Vec2[], candidate: Vec2, tol: number): boolean {
  for (const e of existing) {
    if (dist(e, candidate) <= tol) return true;
  }
  return false;
}

// Auto-place supports along a containment polyline.
//
// Algorithm:
//   1. Compute total run length L.
//   2. Lookup max span S for this containment.
//   3. Place supports at 0, S, 2S, ..., L  (number of supports = ceil(L/S)+1).
//   4. Add an extra support within VERTEX_SUPPORT_DISTANCE_MM of every
//      interior vertex (bend/junction) and every end, dedup against
//      span supports.
//   5. Pick supportKind heuristically.
export function placeSupportsForContainment(
  containment: ContainmentEntity,
  options: SupportPlacerOptions = {}
): SupportEntity[] {
  const { points } = containment;
  if (!points || points.length < 2) return [];

  const layerId = options.layerId ?? containment.layerId;
  const width = containment.width ?? 200;
  const maxSpan =
    options.maxSpanMm ??
    maxSpanForContainment(containment.containmentType, width, containment.material);
  const supportKind = options.supportKind ?? pickSupportKind(containment);
  const anchorType = options.anchorType ?? 'expansion';

  const supports: SupportEntity[] = [];
  const placedPositions: Vec2[] = [];

  // 1) Span supports along the run length
  const totalLength = polylineLength(points);
  const numSpans = Math.max(1, Math.ceil(totalLength / maxSpan));
  // Place numSpans+1 supports evenly along the run so spacing never
  // exceeds maxSpan but the very ends are always supported.
  const actualSpan = totalLength / numSpans;
  for (let i = 0; i <= numSpans; i++) {
    const d = i * actualSpan;
    const pos = pointAtDistance(points, d) ?? points[points.length - 1];
    supports.push(makeSupport(containment, pos, supportKind, anchorType, layerId));
    placedPositions.push(pos);
  }

  // 2) Vertex supports — within 300 mm of every interior vertex
  for (let i = 1; i < points.length - 1; i++) {
    const v = points[i];
    if (tooCloseTo(placedPositions, v, VERTEX_SUPPORT_DISTANCE_MM)) continue;
    supports.push(makeSupport(containment, v, supportKind, anchorType, layerId));
    placedPositions.push(v);
  }

  // 3) Endpoint reinforcement supports — only if the first/last points
  //    aren't already covered (which they normally are by the span loop).
  for (const ep of [points[0], points[points.length - 1]]) {
    if (!tooCloseTo(placedPositions, ep, 1)) {
      supports.push(makeSupport(containment, ep, supportKind, anchorType, layerId));
      placedPositions.push(ep);
    }
  }

  return supports;
}

function makeSupport(
  containment: ContainmentEntity,
  position: Vec2,
  supportKind: SupportKind,
  anchorType: SupportEntity['anchorType'],
  layerId: LayerId
): SupportEntity {
  const support: SupportEntity = {
    id: nanoid(),
    kind: 'support',
    supportKind,
    layerId,
    visible: true,
    locked: false,
    position: { x: position.x, y: position.y },
    rotation: 0,
    supportingContainmentIds: [containment.id],
    elevation: containment.elevation,
    anchorType,
    autoGenerated: true,
  };
  if (supportKind === 'trapeze-hanger') {
    support.rodLength = DEFAULT_ROD_LENGTH_MM;
    support.channelLength = (containment.width ?? 200) + 100;
  } else if (supportKind === 'wall-bracket') {
    support.channelLength = (containment.width ?? 200) + 50;
  }
  return support;
}
