import { describe, expect, it } from 'vitest';
import * as THREE from 'three';
import { renderFitting3D } from '../FittingRender3D';
import type { ContainmentEntity, FittingEntity } from '../../types';

const containment = (
  id: string,
  containmentType: ContainmentEntity['containmentType'],
): ContainmentEntity => ({
  id,
  kind: 'containment',
  layerId: 'containment-layer',
  visible: true,
  locked: false,
  containmentType,
  points: [
    { x: 0, y: 0 },
    { x: 1000, y: 0 },
  ],
  width: 200,
  height: 80,
});

const fitting = (
  fittingKind: FittingEntity['fittingKind'],
  containmentId: string,
): FittingEntity => ({
  id: `${fittingKind}-1`,
  kind: 'fitting',
  layerId: 'containment-layer',
  visible: true,
  locked: false,
  fittingKind,
  position: { x: 0, y: 0 },
  rotation: 0,
  containmentId,
  width: 200,
  height: 80,
  autoGenerated: true,
});

const meshCount = (root: THREE.Object3D): number => {
  let count = 0;
  root.traverse((obj) => {
    if (obj instanceof THREE.Mesh) count += 1;
  });
  return count;
};

const meshesContaining = (root: THREE.Object3D, point: THREE.Vector3): THREE.Mesh[] => {
  const hits: THREE.Mesh[] = [];
  root.updateMatrixWorld(true);
  root.traverse((obj) => {
    if (obj instanceof THREE.Mesh && new THREE.Box3().setFromObject(obj).containsPoint(point)) {
      hits.push(obj);
    }
  });
  return hits;
};

describe('renderFitting3D', () => {
  it('does not render tray end caps as cable-path blockers', () => {
    const tray = containment('tray-1', 'tray');
    const obj = renderFitting3D(fitting('end-cap', tray.id), { parent: tray });

    expect(meshCount(obj)).toBe(0);
  });

  it('renders tray couplers as side joiner plates, leaving the cable path clear', () => {
    const tray = containment('tray-1', 'tray');
    const obj = renderFitting3D(fitting('coupler', tray.id), { parent: tray });

    expect(meshCount(obj)).toBe(2);
    expect(meshesContaining(obj, new THREE.Vector3(0, 0, 0))).toHaveLength(0);
  });

  it('renders tray flat bends as side plates instead of a bulky tube', () => {
    const tray = containment('tray-1', 'tray');
    const obj = renderFitting3D(fitting('flat-bend', tray.id), { parent: tray });

    expect(meshCount(obj)).toBe(4);
    expect(meshesContaining(obj, new THREE.Vector3(0, 0, 0))).toHaveLength(0);
  });

  it('keeps closed trunking end caps visible', () => {
    const trunking = containment('trunking-1', 'trunking');
    const obj = renderFitting3D(fitting('end-cap', trunking.id), { parent: trunking });

    expect(meshCount(obj)).toBe(1);
    expect(meshesContaining(obj, new THREE.Vector3(0, 0, 0)).length).toBeGreaterThan(0);
  });
});
