import { describe, expect, it } from 'vitest';
import * as THREE from 'three';
import { renderSupport3D } from '../SupportRender3D';
import type { SupportEntity } from '../../types';

const support = (channelLength = 960): SupportEntity => ({
  id: 'support-1',
  kind: 'support',
  layerId: 'containment-layer',
  visible: true,
  locked: false,
  supportKind: 'trapeze-hanger',
  position: { x: 0, y: 0 },
  rotation: 0,
  supportingContainmentIds: ['containment-1'],
  elevation: 2400,
  rodLength: 600,
  channelLength,
  autoGenerated: true,
});

const channelSize = (obj: THREE.Object3D): THREE.Vector3 => {
  obj.updateMatrixWorld(true);
  const channels: THREE.Object3D[] = [];
  obj.traverse((child) => {
    if (child.userData.supportPart === 'support-channel') channels.push(child);
  });
  expect(channels).toHaveLength(1);
  const size = new THREE.Vector3();
  new THREE.Box3().setFromObject(channels[0]).getSize(size);
  return size;
};

describe('renderSupport3D', () => {
  it('keeps full hanger span when rods are visible', () => {
    const obj = renderSupport3D(support(), {
      containmentWidth: 600,
      hideHangerRods: false,
    });

    expect(channelSize(obj).x).toBeCloseTo(960, 5);
  });

  it('compacts generated route channels when rods are hidden', () => {
    const obj = renderSupport3D(support(), {
      containmentWidth: 600,
      hideHangerRods: true,
    });

    expect(channelSize(obj).x).toBeCloseTo(720, 5);
  });
});
