import { describe, expect, it } from 'vitest';
import * as THREE from 'three';
import { createSupportClashTester, renderSupport3D, supportHasContainmentClash } from '../SupportRender3D';
import { renderContainment3D } from '../ContainmentRender3D';
import type { ContainmentEntity, SupportEntity } from '../../types';

const support = (channelLength = 960): SupportEntity => ({
  id: 'support-1',
  kind: 'support',
  layerId: 'containment-layer',
  visible: true,
  locked: false,
  supportKind: 'trapeze-hanger',
  position: { x: 0, y: 0 },
  rotation: 0,
  supportingContainmentIds: ['containment-1'],
  elevation: 2400,
  rodLength: 600,
  channelLength,
  autoGenerated: true,
});

const channelSize = (obj: THREE.Object3D): THREE.Vector3 => {
  obj.updateMatrixWorld(true);
  const channels: THREE.Object3D[] = [];
  obj.traverse((child) => {
    if (child.userData.supportPart === 'support-channel') channels.push(child);
  });
  expect(channels).toHaveLength(1);
  const size = new THREE.Vector3();
  new THREE.Box3().setFromObject(channels[0]).getSize(size);
  return size;
};

describe('renderSupport3D', () => {
  it('keeps full hanger span when rods are visible', () => {
    const obj = renderSupport3D({ ...support(), autoGenerated: false }, {
      containmentWidth: 600,
      hideHangerRods: false,
    });

    expect(channelSize(obj).x).toBeCloseTo(960, 5);
  });

  it('compacts generated route channels when rods are hidden', () => {
    const obj = renderSupport3D(support(), {
      containmentWidth: 600,
      hideHangerRods: true,
    });

    expect(channelSize(obj).x).toBeCloseTo(720, 5);
  });

  it('keeps generated rods beside the route without restoring an oversized legacy span', () => {
    const obj = renderSupport3D(support(), { containmentWidth: 200 });
    expect(channelSize(obj).x).toBeCloseTo(320, 5);
    const rods: THREE.Object3D[] = [];
    obj.traverse((child) => { if (child.userData.supportPart === 'hanger-rod') rods.push(child); });
    expect(rods).toHaveLength(2);
    for (const rod of rods) expect(Math.abs(rod.position.x)).toBe(160);
  });

  it('uses a real open strut slot and through-perforated back', () => {
    const obj = renderSupport3D(support(), { containmentWidth: 600, hideHangerRods: true });
    obj.updateMatrixWorld(true);
    const channel = obj.getObjectByName('slotted-strut-channel')!;
    const ray = new THREE.Raycaster(new THREE.Vector3(0, 0, 2500), new THREE.Vector3(0, 0, -1));
    expect(ray.intersectObject(channel, true)).toHaveLength(0);
    ray.ray.origin.y = 15;
    expect(ray.intersectObject(channel, true)[0].point.z).toBeCloseTo(2400);
  });

  it('connects drop rods from below the channel to the ceiling anchor with fixings', () => {
    const obj = renderSupport3D(support(), { containmentWidth: 600 });
    obj.updateMatrixWorld(true);
    const rods: THREE.Object3D[] = [];
    const anchors: THREE.Object3D[] = [];
    obj.traverse((child) => {
      if (child.userData.supportPart === 'hanger-rod') rods.push(child);
      if (child.userData.supportPart === 'ceiling-anchor') anchors.push(child);
    });
    expect(rods).toHaveLength(2);
    expect(anchors).toHaveLength(2);
    const rodBounds = new THREE.Box3().setFromObject(rods[0]);
    expect(rodBounds.min.z).toBeCloseTo(2348);
    expect(rodBounds.max.z).toBeCloseTo(3000);
    expect(obj.getObjectByName('washer-and-hex-nut')).toBeDefined();
  });

  it('keeps invalid optional dimensions from producing non-finite meshes', () => {
    const obj = renderSupport3D({ ...support(), channelLength: NaN, rodLength: Infinity, rotation: NaN, elevation: NaN });
    obj.updateMatrixWorld(true);
    const bounds = new THREE.Box3().setFromObject(obj);
    expect([...bounds.min.toArray(), ...bounds.max.toArray()].every(Number.isFinite)).toBe(true);
  });

  it('detects a rod crossing a neighbouring tray while accepting its own loaded route', () => {
    const loaded: ContainmentEntity = {
      id: 'loaded', kind: 'containment', layerId: 'routes', visible: true, locked: false,
      containmentType: 'tray', width: 200, height: 100, elevation: 2400,
      points: [{ x: 0, y: -1000 }, { x: 0, y: 1000 }],
    };
    const crossing = { ...loaded, id: 'crossing', elevation: 2600, subType: 'solid-bottom' as const,
      points: [{ x: -1000, y: 0 }, { x: 1000, y: 0 }],
    };
    const loadedObject = renderContainment3D(loaded);
    const crossingObject = renderContainment3D(crossing);
    const supportObject = renderSupport3D(support(), { containmentWidth: 200 });
    const floor = new THREE.Group();
    floor.position.z = 3500;
    floor.add(loadedObject, crossingObject, supportObject);
    floor.updateMatrixWorld(true);
    expect(supportHasContainmentClash(supportObject, [loadedObject])).toBe(false);
    const test = createSupportClashTester([loadedObject, crossingObject]);
    expect(test(supportObject)).toBe(true);
    supportObject.position.y = 400;
    expect(test(supportObject)).toBe(false);
    expect(supportObject.parent).toBe(floor);
  });
});
