import type {
  Entity,
  Project,
  Sheet,
  EditorState,
  Vec2,
  Layer,
  SymbolEntity,
  EntityId,
  SymbolPrimitive,
} from '../types';
import { worldToScreen } from '../lib/viewport';
import type { SymbolDef } from '../types';
import { transformSymbolPoint } from '../lib/hittest';
import { entityBounds } from '../lib/math';
import { computeOrthogonalRoute } from '../lib/autoroute';

export interface RenderOptions {
  width: number;
  height: number;
  dpr: number;
  symbolLookup: (id: string) => SymbolDef | undefined;
  /** When true and the wire tool is drafting, show an auto-routed preview. */
  autoRoute?: boolean;
  /** When true, flip the default L-shape direction for the auto-route preview. */
  autoRouteFlip?: boolean;
}

const SELECTION_COLOR = '#ffd84d';
const HOVER_COLOR = '#5cdcff';
const PIN_COLOR = '#3ba3ff';
const SNAP_COLOR = '#00ff00';
const SNAP_GRID_COLOR = '#ffd84d';

export const render2d = (
  ctx: CanvasRenderingContext2D,
  project: Project,
  editor: EditorState,
  opts: RenderOptions
): void => {
  const { width, height, dpr } = opts;
  ctx.save();
  // Clear
  ctx.setTransform(1, 0, 0, 1, 0, 0);
  ctx.clearRect(0, 0, width * dpr, height * dpr);
  ctx.scale(dpr, dpr);

  const sheet = project.sheets[project.activeSheetId];
  if (!sheet) {
    ctx.restore();
    return;
  }

  const v = editor.viewport;

  // Background
  ctx.fillStyle = sheet.background ?? '#0a0e14';
  ctx.fillRect(0, 0, width, height);

  // Grid
  drawGrid(ctx, editor, project, opts);

  // Page boundary
  drawPageBoundary(ctx, sheet, editor, opts);

  // Entities
  ctx.save();
  // Set up world-to-screen transform.
  // x' = (x - vx) * z + W/2 ; y' = -(y - vy) * z + H/2
  // i.e. setTransform(z, 0, 0, -z, W/2 - vx*z, H/2 + vy*z)
  ctx.setTransform(
    dpr * v.zoom,
    0,
    0,
    -dpr * v.zoom,
    dpr * (width / 2 - v.x * v.zoom),
    dpr * (height / 2 + v.y * v.zoom)
  );

  const layerVisible = (id: string) => project.layers[id]?.visible ?? true;

  // Resolve filter / overlay state. These editor fields are optional —
  // honored only when present on the EditorState (forward-compatible).
  const editorAny = editor as unknown as Record<string, unknown>;
  const phaseFilter = (editorAny.phaseFilter as string | undefined) ?? 'all';
  const systemFilter = (editorAny.systemFilter as string | undefined) ?? 'all';
  const complianceOverlay = editorAny.complianceOverlay as
    | 'none'
    | 'fill'
    | 'segregation'
    | 'support-spacing'
    | undefined;

  // Render underlays first (so they sit behind everything else), then the
  // remaining entities in their natural order. Auto-generated fittings get
  // a slight transparency so manual placements stand out.
  const underlayIds: string[] = [];
  const otherIds: string[] = [];
  for (const id of sheet.entityOrder) {
    const e = sheet.entities[id];
    if (!e) continue;
    if ((e as { kind?: string }).kind === 'underlay') underlayIds.push(id);
    else otherIds.push(id);
  }
  const orderedIds = [...underlayIds, ...otherIds];

  for (const entityId of orderedIds) {
    const e = sheet.entities[entityId];
    if (!e || !e.visible) continue;
    const layer = project.layers[e.layerId];
    if (!layer || !layer.visible) continue;
    const isSelected = editor.selection.has(entityId);
    const isHovered = editor.hover === entityId && !isSelected;

    // Filter handling: render filtered-out entities at low opacity grey so
    // the user can still see the surrounding context without losing
    // orientation. We apply a saved alpha around the draw call.
    const eAny = e as unknown as Record<string, unknown>;
    const phaseOk =
      phaseFilter === 'all' ||
      eAny.phase === undefined ||
      eAny.phase === phaseFilter;
    const systemOk =
      systemFilter === 'all' ||
      eAny.systemId === undefined ||
      eAny.systemId === systemFilter;
    const filteredOut = !phaseOk || !systemOk;

    if (filteredOut) {
      ctx.save();
      ctx.globalAlpha = 0.25;
    }

    // Auto-generated fittings render at slightly reduced opacity so manual
    // placements stand out.
    const kind = (e as { kind?: string }).kind;
    let autoFade = false;
    if (kind === 'fitting' && (eAny.autoGenerated as boolean | undefined)) {
      autoFade = true;
      ctx.save();
      ctx.globalAlpha = (ctx.globalAlpha ?? 1) * 0.7;
    }

    drawEntity(ctx, e, layer, opts, {
      isSelected,
      isHovered,
      zoom: v.zoom,
      filteredOut,
      complianceOverlay,
      project,
    });

    if (autoFade) ctx.restore();
    if (filteredOut) ctx.restore();
  }

  // Compliance overlay — applied after entities so the tint sits on top
  // of containment runs without leaking under labels.
  if (complianceOverlay && complianceOverlay !== 'none') {
    drawComplianceOverlay(ctx, sheet, project, complianceOverlay);
  }

  // Drafting preview
  if (editor.drafting) {
    drawDrafting(ctx, editor, opts);
  }

  // Symbol placement preview
  if (editor.tool === 'symbol' && editor.pendingSymbol) {
    const def = opts.symbolLookup(editor.pendingSymbol);
    if (def) {
      const pos = editor.cursorSnap ?? editor.cursor;
      drawSymbolPrimitives(ctx, def.primitives, {
        position: pos,
        rotation: 0,
        scale: 1,
        mirror: false,
      }, '#5cdcff', 0.4, true);
    }
  }

  // Pin highlights at cursor
  drawPinHighlights(ctx, sheet, editor, opts, layerVisible);

  ctx.restore();

  // Snap indicator (in screen space, no transform)
  if (editor.cursorSnap && editor.snap.enabled) {
    drawSnapIndicator(ctx, editor, opts);
  }

  // Crosshair
  drawCrosshair(ctx, editor, opts);

  ctx.restore();
};

const drawGrid = (
  ctx: CanvasRenderingContext2D,
  editor: EditorState,
  project: Project,
  opts: RenderOptions
) => {
  const { width, height } = opts;
  const v = editor.viewport;
  const gs = editor.snap.gridSize || 5;
  // Compute world bounds of viewport
  const wMinX = (-width / 2) / v.zoom + v.x;
  const wMaxX = (width / 2) / v.zoom + v.x;
  const wMinY = -(height / 2) / v.zoom + v.y;
  const wMaxY = (height / 2) / v.zoom + v.y;

  const pxPerUnit = v.zoom * gs;
  if (pxPerUnit < 4) return; // too dense, skip

  const major = 5; // every 5 grid units = a major line

  ctx.lineWidth = 1;
  // Minor grid
  ctx.strokeStyle = '#141a25';
  ctx.beginPath();
  const startX = Math.floor(wMinX / gs) * gs;
  const endX = Math.ceil(wMaxX / gs) * gs;
  const startY = Math.floor(wMinY / gs) * gs;
  const endY = Math.ceil(wMaxY / gs) * gs;
  for (let x = startX; x <= endX; x += gs) {
    if (Math.round(x / gs) % major === 0) continue;
    const sx = (x - v.x) * v.zoom + width / 2;
    ctx.moveTo(sx, 0);
    ctx.lineTo(sx, height);
  }
  for (let y = startY; y <= endY; y += gs) {
    if (Math.round(y / gs) % major === 0) continue;
    const sy = -(y - v.y) * v.zoom + height / 2;
    ctx.moveTo(0, sy);
    ctx.lineTo(width, sy);
  }
  ctx.stroke();

  // Major grid
  ctx.strokeStyle = '#1f2a3d';
  ctx.beginPath();
  for (let x = startX; x <= endX; x += gs) {
    if (Math.round(x / gs) % major !== 0) continue;
    const sx = (x - v.x) * v.zoom + width / 2;
    ctx.moveTo(sx, 0);
    ctx.lineTo(sx, height);
  }
  for (let y = startY; y <= endY; y += gs) {
    if (Math.round(y / gs) % major !== 0) continue;
    const sy = -(y - v.y) * v.zoom + height / 2;
    ctx.moveTo(0, sy);
    ctx.lineTo(width, sy);
  }
  ctx.stroke();

  // Origin axes
  const ox = (0 - v.x) * v.zoom + width / 2;
  const oy = -(0 - v.y) * v.zoom + height / 2;
  ctx.strokeStyle = '#3a4660';
  ctx.lineWidth = 1;
  ctx.beginPath();
  if (ox >= 0 && ox <= width) {
    ctx.moveTo(ox, 0);
    ctx.lineTo(ox, height);
  }
  if (oy >= 0 && oy <= height) {
    ctx.moveTo(0, oy);
    ctx.lineTo(width, oy);
  }
  ctx.stroke();
};

const drawPageBoundary = (
  ctx: CanvasRenderingContext2D,
  sheet: Sheet,
  editor: EditorState,
  opts: RenderOptions
) => {
  const { width, height } = opts;
  const v = editor.viewport;
  // Page from (0,0) to (width, height) in mm
  const a = worldToScreen({ x: 0, y: 0 }, v, width, height);
  const b = worldToScreen({ x: sheet.width, y: sheet.height }, v, width, height);
  // page interior
  const x = Math.min(a.x, b.x);
  const y = Math.min(a.y, b.y);
  const w = Math.abs(b.x - a.x);
  const h = Math.abs(b.y - a.y);

  // shadow
  ctx.fillStyle = 'rgba(0,0,0,0.5)';
  ctx.fillRect(x + 4, y + 4, w, h);

  // page background slightly lighter
  ctx.fillStyle = '#0d131c';
  ctx.fillRect(x, y, w, h);

  // border
  ctx.strokeStyle = '#445575';
  ctx.lineWidth = 1.5;
  ctx.strokeRect(x, y, w, h);

  // title block area in lower-right (60mm wide x 30mm tall)
  const tbW = Math.min(60 * v.zoom, w * 0.45);
  const tbH = Math.min(30 * v.zoom, h * 0.25);
  ctx.strokeStyle = '#445575';
  ctx.lineWidth = 1;
  ctx.strokeRect(x + w - tbW - 4, y + h - tbH - 4, tbW, tbH);
  // sub-divisions
  ctx.strokeStyle = '#2c3a52';
  ctx.beginPath();
  ctx.moveTo(x + w - tbW - 4, y + h - tbH * 0.66 - 4);
  ctx.lineTo(x + w - 4, y + h - tbH * 0.66 - 4);
  ctx.moveTo(x + w - tbW - 4, y + h - tbH * 0.33 - 4);
  ctx.lineTo(x + w - 4, y + h - tbH * 0.33 - 4);
  ctx.moveTo(x + w - tbW * 0.5 - 4, y + h - tbH - 4);
  ctx.lineTo(x + w - tbW * 0.5 - 4, y + h - 4);
  ctx.stroke();

  // Title block text (rendered when zoomed enough)
  if (tbW > 80) {
    ctx.fillStyle = '#9aa3b2';
    ctx.font = `${Math.min(10, tbH * 0.2)}px ui-monospace, monospace`;
    ctx.textBaseline = 'top';
    ctx.fillText('OPENCAD ELECTRICAL', x + w - tbW + 2, y + h - tbH);
    ctx.fillStyle = '#e6e8ec';
    ctx.font = `${Math.min(11, tbH * 0.22)}px sans-serif`;
    ctx.fillText(sheet.name, x + w - tbW + 2, y + h - tbH + tbH * 0.34);
    ctx.fillStyle = '#9aa3b2';
    ctx.font = `${Math.min(9, tbH * 0.18)}px ui-monospace, monospace`;
    ctx.fillText(`SHEET ${sheet.number}`, x + w - tbW + 2, y + h - tbH + tbH * 0.7);
    ctx.fillText(sheet.kind.toUpperCase(), x + w - tbW * 0.5 + 2, y + h - tbH + tbH * 0.7);
  }
};

type DrawState = {
  isSelected: boolean;
  isHovered: boolean;
  zoom: number;
  filteredOut?: boolean;
  complianceOverlay?: 'none' | 'fill' | 'segregation' | 'support-spacing';
  project?: Project;
};

const drawEntity = (
  ctx: CanvasRenderingContext2D,
  e: Entity,
  layer: Layer,
  opts: RenderOptions,
  state: DrawState
) => {
  const color = e.color ?? layer.color;
  const lineWidth = (e.lineWidth ?? layer.lineWidth) * 1.0;
  const dash = e.lineDash ?? layer.lineDash;

  // Inverse-scale line width so it renders at constant pixel width-ish but still scales a bit
  const effectiveWidth = lineWidth;

  ctx.strokeStyle = state.isSelected ? SELECTION_COLOR : state.isHovered ? HOVER_COLOR : color;
  ctx.lineWidth = effectiveWidth;
  ctx.setLineDash(dash ?? []);
  ctx.lineCap = 'round';
  ctx.lineJoin = 'round';

  // Dispatch new entity kinds before the strict-typed switch. The kinds
  // below aren't part of the Entity union yet — handlers operate on a
  // structurally-typed AnyEntity record so the file still typechecks
  // strictly while gracefully handling missing fields at runtime.
  const kind = (e as { kind?: string }).kind;
  if (NEW_ENTITY_KINDS.has(kind ?? '')) {
    const ae = e as unknown as AnyEntity;
    switch (kind) {
      case 'fitting':
        drawFitting(ctx, ae, color, effectiveWidth, state);
        break;
      case 'support':
        drawSupport(ctx, ae, color, effectiveWidth, state);
        break;
      case 'equipment':
        drawEquipment(ctx, ae, color, effectiveWidth, state);
        break;
      case 'riser':
        drawRiser(ctx, ae, color, effectiveWidth, state);
        break;
      case 'fire-barrier':
        drawFireBarrier(ctx, ae, color, effectiveWidth, state);
        break;
      case 'penetration':
        drawPenetration(ctx, ae, color, effectiveWidth, state);
        break;
      case 'leader':
        drawLeader(ctx, ae, color, effectiveWidth, state);
        break;
      case 'section-marker':
        drawSectionMarker(ctx, ae, color, effectiveWidth, state);
        break;
      case 'level-marker':
        drawLevelMarker(ctx, ae, color, effectiveWidth, state);
        break;
      case 'north-arrow':
        drawNorthArrow(ctx, ae, color, effectiveWidth, state);
        break;
      case 'scale-bar':
        drawScaleBar(ctx, ae, color, effectiveWidth, state);
        break;
      case 'grid-line':
        drawGridLine(ctx, ae, color, effectiveWidth, state);
        break;
      case 'revision-cloud':
      case 'cloud':
        drawCloudEntity(ctx, ae, kind === 'revision-cloud', color, effectiveWidth, state);
        break;
      case 'underlay':
        drawUnderlay(ctx, ae);
        break;
    }
    if (state.isSelected) drawSelectionBoxFor(ctx, ae);
    return;
  }

  switch (e.kind) {
    case 'line':
      ctx.beginPath();
      ctx.moveTo(e.a.x, e.a.y);
      ctx.lineTo(e.b.x, e.b.y);
      ctx.stroke();
      break;
    case 'polyline':
      if (e.points.length >= 2) {
        ctx.beginPath();
        ctx.moveTo(e.points[0].x, e.points[0].y);
        for (let i = 1; i < e.points.length; i++) ctx.lineTo(e.points[i].x, e.points[i].y);
        if (e.closed) ctx.closePath();
        ctx.stroke();
      }
      break;
    case 'wire': {
      // wires get a slight glow on hover/selection and connection dots at junctions
      ctx.strokeStyle = state.isSelected
        ? SELECTION_COLOR
        : state.isHovered
        ? HOVER_COLOR
        : color || '#ff3a3a';
      if (e.points.length >= 2) {
        ctx.beginPath();
        ctx.moveTo(e.points[0].x, e.points[0].y);
        for (let i = 1; i < e.points.length; i++) ctx.lineTo(e.points[i].x, e.points[i].y);
        ctx.stroke();
      }
      // wire number label
      if (e.wireNumber) {
        const mid = e.points[Math.floor(e.points.length / 2) - 1] ?? e.points[0];
        const next = e.points[Math.floor(e.points.length / 2)] ?? e.points[1];
        if (mid && next) {
          const cx = (mid.x + next.x) / 2;
          const cy = (mid.y + next.y) / 2;
          ctx.save();
          ctx.scale(1, -1);
          ctx.fillStyle = '#ffd84d';
          ctx.font = '3px ui-monospace, monospace';
          ctx.textAlign = 'center';
          ctx.textBaseline = 'middle';
          ctx.fillText(e.wireNumber, cx, -cy + 2.5);
          ctx.restore();
        }
      }
      break;
    }
    case 'bus':
      if (e.points.length >= 2) {
        ctx.lineWidth = effectiveWidth * 3;
        ctx.beginPath();
        ctx.moveTo(e.points[0].x, e.points[0].y);
        for (let i = 1; i < e.points.length; i++) ctx.lineTo(e.points[i].x, e.points[i].y);
        ctx.stroke();
      }
      break;
    case 'rectangle': {
      const x = Math.min(e.a.x, e.b.x);
      const y = Math.min(e.a.y, e.b.y);
      const w = Math.abs(e.b.x - e.a.x);
      const h = Math.abs(e.b.y - e.a.y);
      if (e.fill) {
        ctx.fillStyle = e.fill;
        ctx.fillRect(x, y, w, h);
      }
      ctx.strokeRect(x, y, w, h);
      break;
    }
    case 'circle':
      ctx.beginPath();
      ctx.arc(e.center.x, e.center.y, e.radius, 0, Math.PI * 2);
      if (e.fill) {
        ctx.fillStyle = e.fill;
        ctx.fill();
      }
      ctx.stroke();
      break;
    case 'arc':
      ctx.beginPath();
      ctx.arc(e.center.x, e.center.y, e.radius, e.startAngle, e.endAngle);
      ctx.stroke();
      break;
    case 'ellipse':
      ctx.beginPath();
      ctx.ellipse(e.center.x, e.center.y, e.rx, e.ry, e.rotation, 0, Math.PI * 2);
      ctx.stroke();
      break;
    case 'text':
      // Canvas y-flip means text rendering needs to be flipped
      ctx.save();
      ctx.translate(e.position.x, e.position.y);
      ctx.scale(1, -1);
      ctx.rotate(-e.rotation);
      ctx.fillStyle = state.isSelected ? SELECTION_COLOR : color;
      ctx.font = `${e.fontSize}px sans-serif`;
      ctx.textAlign = (e.align ?? 'left') as CanvasTextAlign;
      ctx.textBaseline = 'alphabetic';
      ctx.fillText(e.text, 0, 0);
      ctx.restore();
      break;
    case 'symbol': {
      drawSymbol(ctx, e, opts, state, layer);
      break;
    }
    case 'dimension':
      drawDimension(ctx, e, color, effectiveWidth, state);
      break;
    case 'wire-label':
      ctx.save();
      ctx.translate(e.position.x, e.position.y);
      ctx.scale(1, -1);
      ctx.rotate(-e.rotation);
      ctx.fillStyle = state.isSelected ? SELECTION_COLOR : '#ffd84d';
      ctx.font = '3px ui-monospace, monospace';
      ctx.textAlign = 'center';
      ctx.textBaseline = 'middle';
      ctx.fillText(e.text, 0, 0);
      ctx.restore();
      break;
    case 'containment':
      drawContainment(ctx, e, color, state);
      break;
    case 'wall':
      drawWall(ctx, e, color, state);
      break;
    case 'room':
      drawRoom(ctx, e, layer, color, state);
      break;
    case 'group':
      break;
  }

  // Selection bounding box
  if (state.isSelected) {
    drawSelectionBox(ctx, e, opts);
  }
};

const drawSymbol = (
  ctx: CanvasRenderingContext2D,
  sym: SymbolEntity,
  opts: RenderOptions,
  state: { isSelected: boolean; isHovered: boolean; zoom: number },
  layer: Layer
) => {
  const def = opts.symbolLookup(sym.symbolId);
  if (!def) {
    // missing symbol — draw placeholder
    ctx.save();
    ctx.translate(sym.position.x, sym.position.y);
    ctx.fillStyle = '#ff5d5d';
    ctx.font = '3px sans-serif';
    ctx.fillText('?', -1, 0);
    ctx.strokeStyle = '#ff5d5d';
    ctx.strokeRect(-5, -5, 10, 10);
    ctx.restore();
    return;
  }
  const color = state.isSelected
    ? SELECTION_COLOR
    : state.isHovered
    ? HOVER_COLOR
    : sym.color ?? layer.color;

  drawSymbolPrimitives(ctx, def.primitives, sym, color, sym.lineWidth ?? layer.lineWidth);

  // Tag label (above symbol)
  if (sym.tag) {
    ctx.save();
    ctx.translate(sym.position.x, sym.position.y + def.bounds.maxY * sym.scale + 1.5);
    ctx.scale(1, -1);
    ctx.fillStyle = state.isSelected ? SELECTION_COLOR : '#9ad65a';
    ctx.font = 'bold 3px ui-monospace, monospace';
    ctx.textAlign = 'center';
    ctx.fillText(sym.tag, 0, 0);
    ctx.restore();
  }
  // Description label (below symbol)
  if (sym.description) {
    ctx.save();
    ctx.translate(sym.position.x, sym.position.y + def.bounds.minY * sym.scale - 1.5);
    ctx.scale(1, -1);
    ctx.fillStyle = '#9aa3b2';
    ctx.font = '2.4px sans-serif';
    ctx.textAlign = 'center';
    ctx.textBaseline = 'top';
    ctx.fillText(sym.description, 0, 0);
    ctx.restore();
  }

  // Pins (small dots)
  ctx.fillStyle = state.isSelected ? SELECTION_COLOR : PIN_COLOR;
  for (const p of def.pins) {
    const wp = transformSymbolPoint(sym, p.position);
    ctx.beginPath();
    ctx.arc(wp.x, wp.y, 0.6, 0, Math.PI * 2);
    ctx.fill();
  }
};

export const drawSymbolPrimitives = (
  ctx: CanvasRenderingContext2D,
  primitives: SymbolPrimitive[],
  sym: Pick<SymbolEntity, 'position' | 'rotation' | 'scale' | 'mirror'>,
  color: string,
  lineWidth: number,
  ghost = false
): void => {
  ctx.save();
  ctx.translate(sym.position.x, sym.position.y);
  ctx.rotate(sym.rotation);
  ctx.scale(sym.scale * (sym.mirror ? -1 : 1), sym.scale);
  ctx.strokeStyle = color;
  ctx.fillStyle = color;
  ctx.lineWidth = lineWidth;
  ctx.lineCap = 'round';
  ctx.lineJoin = 'round';
  if (ghost) {
    ctx.globalAlpha = 0.55;
    ctx.setLineDash([1, 1]);
  } else {
    ctx.setLineDash([]);
  }

  for (const p of primitives) {
    switch (p.kind) {
      case 'line':
        ctx.lineWidth = (p.lineWidth ?? lineWidth);
        ctx.beginPath();
        ctx.moveTo(p.a.x, p.a.y);
        ctx.lineTo(p.b.x, p.b.y);
        ctx.stroke();
        break;
      case 'circle':
        ctx.lineWidth = (p.lineWidth ?? lineWidth);
        ctx.beginPath();
        ctx.arc(p.c.x, p.c.y, p.r, 0, Math.PI * 2);
        if (p.fill) {
          const prev: string | CanvasGradient | CanvasPattern = ctx.fillStyle;
          ctx.fillStyle = p.fill;
          ctx.fill();
          ctx.fillStyle = prev;
        }
        ctx.stroke();
        break;
      case 'arc':
        ctx.lineWidth = (p.lineWidth ?? lineWidth);
        ctx.beginPath();
        ctx.arc(p.c.x, p.c.y, p.r, p.start, p.end);
        ctx.stroke();
        break;
      case 'rect': {
        const x = Math.min(p.a.x, p.b.x);
        const y = Math.min(p.a.y, p.b.y);
        const w = Math.abs(p.b.x - p.a.x);
        const h = Math.abs(p.b.y - p.a.y);
        ctx.lineWidth = (p.lineWidth ?? lineWidth);
        if (p.fill) {
          const prev: string | CanvasGradient | CanvasPattern = ctx.fillStyle;
          ctx.fillStyle = p.fill;
          ctx.fillRect(x, y, w, h);
          ctx.fillStyle = prev;
        }
        ctx.strokeRect(x, y, w, h);
        break;
      }
      case 'polyline':
        ctx.lineWidth = (p.lineWidth ?? lineWidth);
        if (p.points.length >= 2) {
          ctx.beginPath();
          ctx.moveTo(p.points[0].x, p.points[0].y);
          for (let i = 1; i < p.points.length; i++) ctx.lineTo(p.points[i].x, p.points[i].y);
          if (p.closed) ctx.closePath();
          if (p.fill) {
            const prev: string | CanvasGradient | CanvasPattern = ctx.fillStyle;
            ctx.fillStyle = p.fill;
            ctx.fill();
            ctx.fillStyle = prev;
          }
          ctx.stroke();
        }
        break;
      case 'text':
        ctx.save();
        ctx.translate(p.p.x, p.p.y);
        ctx.scale(1, -1);
        ctx.fillStyle = color;
        ctx.font = `${p.size}px sans-serif`;
        ctx.textAlign = (p.align ?? 'left') as CanvasTextAlign;
        ctx.textBaseline = 'middle';
        ctx.fillText(p.text, 0, 0);
        ctx.restore();
        break;
    }
  }
  ctx.restore();
};

const drawDimension = (
  ctx: CanvasRenderingContext2D,
  e: import('../types').DimensionEntity,
  color: string,
  lineWidth: number,
  state: { isSelected: boolean }
) => {
  const dx = e.b.x - e.a.x;
  const dy = e.b.y - e.a.y;
  const len = Math.sqrt(dx * dx + dy * dy);
  if (len < 0.001) return;
  const nx = -dy / len;
  const ny = dx / len;
  const ax = e.a.x + nx * e.offset;
  const ay = e.a.y + ny * e.offset;
  const bx = e.b.x + nx * e.offset;
  const by = e.b.y + ny * e.offset;

  ctx.strokeStyle = state.isSelected ? SELECTION_COLOR : color;
  ctx.lineWidth = lineWidth;
  ctx.beginPath();
  // extension lines
  ctx.moveTo(e.a.x, e.a.y);
  ctx.lineTo(ax, ay);
  ctx.moveTo(e.b.x, e.b.y);
  ctx.lineTo(bx, by);
  // dimension line
  ctx.moveTo(ax, ay);
  ctx.lineTo(bx, by);
  ctx.stroke();

  // arrowheads
  const arrSize = 1.5;
  const angle = Math.atan2(by - ay, bx - ax);
  drawArrowhead(ctx, ax, ay, angle, arrSize);
  drawArrowhead(ctx, bx, by, angle + Math.PI, arrSize);

  // text
  const cx = (ax + bx) / 2;
  const cy = (ay + by) / 2;
  ctx.save();
  ctx.translate(cx, cy);
  ctx.scale(1, -1);
  ctx.rotate(-angle);
  ctx.fillStyle = state.isSelected ? SELECTION_COLOR : color;
  ctx.font = '2.4px ui-monospace, monospace';
  ctx.textAlign = 'center';
  ctx.textBaseline = 'bottom';
  ctx.fillText(e.text ?? `${len.toFixed(1)}mm`, 0, -0.5);
  ctx.restore();
};

const drawArrowhead = (
  ctx: CanvasRenderingContext2D,
  x: number,
  y: number,
  angle: number,
  size: number
) => {
  ctx.beginPath();
  ctx.moveTo(x, y);
  ctx.lineTo(x + Math.cos(angle - Math.PI + 0.4) * size, y + Math.sin(angle - Math.PI + 0.4) * size);
  ctx.lineTo(x + Math.cos(angle - Math.PI - 0.4) * size, y + Math.sin(angle - Math.PI - 0.4) * size);
  ctx.closePath();
  ctx.fill();
};

const drawSelectionBox = (ctx: CanvasRenderingContext2D, e: Entity, opts: RenderOptions) => {
  let bb = entityBounds(e);
  if (e.kind === 'symbol') {
    const def = opts.symbolLookup(e.symbolId);
    if (def) {
      const corners = [
        { x: def.bounds.minX, y: def.bounds.minY },
        { x: def.bounds.maxX, y: def.bounds.minY },
        { x: def.bounds.maxX, y: def.bounds.maxY },
        { x: def.bounds.minX, y: def.bounds.maxY },
      ].map((c) => transformSymbolPoint(e, c));
      bb = corners.reduce(
        (b, c) => ({
          minX: Math.min(b.minX, c.x),
          minY: Math.min(b.minY, c.y),
          maxX: Math.max(b.maxX, c.x),
          maxY: Math.max(b.maxY, c.y),
        }),
        { minX: Infinity, minY: Infinity, maxX: -Infinity, maxY: -Infinity }
      );
    }
  }
  if (!isFinite(bb.minX)) return;
  const pad = 1.5;
  ctx.save();
  ctx.strokeStyle = SELECTION_COLOR;
  ctx.lineWidth = 0.3;
  ctx.setLineDash([1.2, 1]);
  ctx.strokeRect(bb.minX - pad, bb.minY - pad, bb.maxX - bb.minX + pad * 2, bb.maxY - bb.minY + pad * 2);
  ctx.setLineDash([]);
  // grips at corners and midpoints
  const grips: Vec2[] = [
    { x: bb.minX, y: bb.minY },
    { x: bb.maxX, y: bb.minY },
    { x: bb.maxX, y: bb.maxY },
    { x: bb.minX, y: bb.maxY },
    { x: (bb.minX + bb.maxX) / 2, y: bb.minY },
    { x: bb.maxX, y: (bb.minY + bb.maxY) / 2 },
    { x: (bb.minX + bb.maxX) / 2, y: bb.maxY },
    { x: bb.minX, y: (bb.minY + bb.maxY) / 2 },
  ];
  ctx.fillStyle = SELECTION_COLOR;
  for (const g of grips) {
    ctx.fillRect(g.x - 0.6, g.y - 0.6, 1.2, 1.2);
  }
  ctx.restore();
};

// Render a containment run (trunking / basket / tray / conduit) as a thick
// band along its polyline. Different types layer on extra strokes to read
// distinctly in plan view.
const drawContainment = (
  ctx: CanvasRenderingContext2D,
  e: import('../types').ContainmentEntity,
  color: string,
  state: { isSelected: boolean; isHovered: boolean; zoom: number }
) => {
  if (e.points.length < 2) return;
  const w = e.width ?? 50;
  const stroke = state.isSelected
    ? SELECTION_COLOR
    : state.isHovered
    ? HOVER_COLOR
    : color;

  ctx.save();
  ctx.lineCap = e.containmentType === 'conduit' ? 'round' : 'butt';
  ctx.lineJoin = 'round';
  ctx.setLineDash([]);

  // Build the polyline path.
  const path = new Path2D();
  path.moveTo(e.points[0].x, e.points[0].y);
  for (let i = 1; i < e.points.length; i++) {
    path.lineTo(e.points[i].x, e.points[i].y);
  }

  if (e.containmentType === 'conduit') {
    // Round tube — single thick line, plus a thin centerline highlight.
    ctx.strokeStyle = stroke;
    ctx.globalAlpha = 0.55;
    ctx.lineWidth = w;
    ctx.stroke(path);
    ctx.globalAlpha = 1;
    ctx.strokeStyle = stroke;
    ctx.lineWidth = Math.max(0.4, w * 0.06);
    ctx.stroke(path);
  } else {
    // Filled band for the cross-section.
    ctx.strokeStyle = stroke;
    ctx.globalAlpha = e.containmentType === 'basket' ? 0.18 : 0.32;
    ctx.lineWidth = w;
    ctx.stroke(path);
    ctx.globalAlpha = 1;

    // Edge highlights — outline the band with thinner lines on either side
    // of the centerline by re-stroking with reduced width using a lighter
    // alpha, then a thin centerline.
    ctx.strokeStyle = stroke;
    ctx.lineWidth = 0.5;
    ctx.stroke(path);

    // Type-specific overlay markings drawn as evenly-spaced ticks along the
    // path so the type is recognizable at a glance.
    drawContainmentTicks(ctx, e, w, stroke);
  }

  ctx.restore();
};

// Walk each segment of a containment run and draw short perpendicular
// "ticks" (the rungs of a basket, the perforations of a tray) at fixed
// world-space intervals.
const drawContainmentTicks = (
  ctx: CanvasRenderingContext2D,
  e: import('../types').ContainmentEntity,
  w: number,
  color: string
) => {
  if (e.containmentType === 'trunking') return; // smooth band, no ticks

  const spacing = e.containmentType === 'tray' ? Math.max(8, w * 0.4) : Math.max(6, w * 0.35);
  ctx.strokeStyle = color;
  ctx.lineWidth = e.containmentType === 'tray' ? 0.4 : 0.5;
  ctx.setLineDash([]);

  for (let i = 0; i < e.points.length - 1; i++) {
    const a = e.points[i];
    const b = e.points[i + 1];
    const dx = b.x - a.x;
    const dy = b.y - a.y;
    const len = Math.hypot(dx, dy);
    if (len < 1e-3) continue;
    const ux = dx / len;
    const uy = dy / len;
    const px = -uy; // perpendicular
    const py = ux;
    const half = w / 2;

    for (let s = spacing / 2; s < len; s += spacing) {
      const cx = a.x + ux * s;
      const cy = a.y + uy * s;
      if (e.containmentType === 'basket') {
        // X-shaped crossings at each rung
        ctx.beginPath();
        ctx.moveTo(cx + ux * (spacing * 0.3) - px * half, cy + uy * (spacing * 0.3) - py * half);
        ctx.lineTo(cx - ux * (spacing * 0.3) + px * half, cy - uy * (spacing * 0.3) + py * half);
        ctx.moveTo(cx - ux * (spacing * 0.3) - px * half, cy - uy * (spacing * 0.3) - py * half);
        ctx.lineTo(cx + ux * (spacing * 0.3) + px * half, cy + uy * (spacing * 0.3) + py * half);
        ctx.stroke();
      } else if (e.containmentType === 'tray') {
        // Single perpendicular line — perforated tray rung
        ctx.beginPath();
        ctx.moveTo(cx - px * half, cy - py * half);
        ctx.lineTo(cx + px * half, cy + py * half);
        ctx.stroke();
      }
    }
  }
};

// Render a wall as the standard architectural double-line: a thick translucent
// band at the wall's true thickness with a thin centerline outline so corners
// read cleanly in plan view.
const drawWall = (
  ctx: CanvasRenderingContext2D,
  e: import('../types').WallEntity,
  color: string,
  state: { isSelected: boolean; isHovered: boolean; zoom: number }
) => {
  if (e.points.length < 2) return;
  const stroke = state.isSelected
    ? SELECTION_COLOR
    : state.isHovered
    ? HOVER_COLOR
    : color;
  const t = e.thickness ?? 200;

  ctx.save();
  ctx.lineCap = 'butt';
  ctx.lineJoin = 'miter';
  ctx.setLineDash([]);

  const path = new Path2D();
  path.moveTo(e.points[0].x, e.points[0].y);
  for (let i = 1; i < e.points.length; i++) {
    path.lineTo(e.points[i].x, e.points[i].y);
  }

  // Thick translucent band at full wall thickness.
  ctx.strokeStyle = stroke;
  ctx.globalAlpha = 0.5;
  ctx.lineWidth = t;
  ctx.stroke(path);
  ctx.globalAlpha = 1;

  // Thin centerline outline so corners read cleanly.
  ctx.strokeStyle = stroke;
  ctx.lineWidth = Math.max(0.4, t * 0.04);
  ctx.stroke(path);

  ctx.restore();
};

// Render a room as a translucent rectangular floor patch with a dashed
// boundary, plus an optional centered name label.
const drawRoom = (
  ctx: CanvasRenderingContext2D,
  e: import('../types').RoomEntity,
  layer: Layer,
  color: string,
  state: { isSelected: boolean; isHovered: boolean; zoom: number }
) => {
  const x = Math.min(e.a.x, e.b.x);
  const y = Math.min(e.a.y, e.b.y);
  const w = Math.abs(e.b.x - e.a.x);
  const h = Math.abs(e.b.y - e.a.y);
  if (w <= 0 || h <= 0) return;
  const stroke = state.isSelected
    ? SELECTION_COLOR
    : state.isHovered
    ? HOVER_COLOR
    : color;

  ctx.save();
  // Translucent floor fill.
  ctx.fillStyle = e.floorColor ?? layer.color;
  ctx.globalAlpha = 0.12;
  ctx.fillRect(x, y, w, h);
  ctx.globalAlpha = 1;

  // Dashed boundary in the layer color.
  ctx.strokeStyle = stroke;
  ctx.lineWidth = 0.4;
  ctx.setLineDash([2, 1.5]);
  ctx.lineCap = 'butt';
  ctx.lineJoin = 'miter';
  ctx.strokeRect(x, y, w, h);
  ctx.setLineDash([]);

  // Centered room name label (unflipped — see text case for pattern).
  if (e.name) {
    const cx = x + w / 2;
    const cy = y + h / 2;
    const size = Math.max(3, Math.min(10, Math.min(w, h) * 0.08));
    ctx.save();
    ctx.scale(1, -1);
    ctx.fillStyle = state.isSelected ? SELECTION_COLOR : color;
    ctx.font = `${size}px sans-serif`;
    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';
    ctx.fillText(e.name, cx, -cy);
    ctx.restore();
  }
  ctx.restore();
};

const drawDrafting = (
  ctx: CanvasRenderingContext2D,
  editor: EditorState,
  _opts: RenderOptions
) => {
  const d = editor.drafting!;
  if (d.points.length === 0) return;
  const cur = editor.cursorSnap ?? editor.cursor;
  ctx.save();
  ctx.strokeStyle = '#5cdcff';
  ctx.fillStyle = '#5cdcff';
  ctx.lineWidth = 0.4;
  ctx.setLineDash([1, 1]);
  ctx.lineCap = 'round';
  ctx.lineJoin = 'round';

  switch (d.tool) {
    case 'line':
      ctx.beginPath();
      ctx.moveTo(d.points[0].x, d.points[0].y);
      ctx.lineTo(cur.x, cur.y);
      ctx.stroke();
      break;
    case 'rectangle': {
      const a = d.points[0];
      ctx.strokeRect(
        Math.min(a.x, cur.x),
        Math.min(a.y, cur.y),
        Math.abs(cur.x - a.x),
        Math.abs(cur.y - a.y)
      );
      break;
    }
    case 'circle': {
      const a = d.points[0];
      const r = Math.hypot(cur.x - a.x, cur.y - a.y);
      ctx.beginPath();
      ctx.arc(a.x, a.y, r, 0, Math.PI * 2);
      ctx.stroke();
      break;
    }
    case 'arc': {
      if (d.points.length === 1) {
        // center -> radius
        const a = d.points[0];
        const r = Math.hypot(cur.x - a.x, cur.y - a.y);
        ctx.beginPath();
        ctx.arc(a.x, a.y, r, 0, Math.PI * 2);
        ctx.stroke();
      } else if (d.points.length === 2) {
        const c = d.points[0];
        const start = Math.atan2(d.points[1].y - c.y, d.points[1].x - c.x);
        const end = Math.atan2(cur.y - c.y, cur.x - c.x);
        const r = Math.hypot(d.points[1].x - c.x, d.points[1].y - c.y);
        ctx.beginPath();
        ctx.arc(c.x, c.y, r, start, end);
        ctx.stroke();
      }
      break;
    }
    case 'polyline':
    case 'wire':
    case 'bus': {
      if (d.tool === 'bus') ctx.lineWidth = 1.2;
      if (d.tool === 'wire') ctx.strokeStyle = '#ff7a7a';

      // Auto-route wire preview: show the L-shaped orthogonal path instead
      // of a straight line from the last draft point to the cursor.
      if (d.tool === 'wire' && _opts.autoRoute && d.points.length === 1) {
        const start = d.points[0];
        const dx = Math.abs(cur.x - start.x);
        const dy = Math.abs(cur.y - start.y);
        const defaultHFirst = dx >= dy;
        const horizontalFirst = _opts.autoRouteFlip ? !defaultHFirst : defaultHFirst;
        const route = computeOrthogonalRoute({
          startX: start.x,
          startY: start.y,
          endX: cur.x,
          endY: cur.y,
          preferHorizontalFirst: horizontalFirst,
        });
        ctx.setLineDash([1.5, 1]);
        ctx.lineWidth = 0.5;
        ctx.beginPath();
        ctx.moveTo(route[0].x, route[0].y);
        for (let i = 1; i < route.length; i++) ctx.lineTo(route[i].x, route[i].y);
        ctx.stroke();
        break;
      }

      ctx.beginPath();
      ctx.moveTo(d.points[0].x, d.points[0].y);
      for (let i = 1; i < d.points.length; i++) ctx.lineTo(d.points[i].x, d.points[i].y);
      ctx.lineTo(cur.x, cur.y);
      ctx.stroke();
      break;
    }
    case 'trunking':
    case 'basket':
    case 'tray':
    case 'conduit': {
      // Preview the band at its real width with a translucent fill so the
      // user can see the run's footprint while drafting.
      const widths: Record<string, number> = {
        trunking: 100,
        basket: 100,
        tray: 150,
        conduit: 25,
      };
      const w = widths[d.tool] ?? 50;
      ctx.save();
      ctx.lineCap = d.tool === 'conduit' ? 'round' : 'butt';
      ctx.lineJoin = 'round';
      ctx.setLineDash([]);
      ctx.globalAlpha = 0.25;
      ctx.lineWidth = w;
      ctx.beginPath();
      ctx.moveTo(d.points[0].x, d.points[0].y);
      for (let i = 1; i < d.points.length; i++) ctx.lineTo(d.points[i].x, d.points[i].y);
      ctx.lineTo(cur.x, cur.y);
      ctx.stroke();
      // Centerline on top
      ctx.globalAlpha = 1;
      ctx.lineWidth = 0.5;
      ctx.setLineDash([1, 1]);
      ctx.beginPath();
      ctx.moveTo(d.points[0].x, d.points[0].y);
      for (let i = 1; i < d.points.length; i++) ctx.lineTo(d.points[i].x, d.points[i].y);
      ctx.lineTo(cur.x, cur.y);
      ctx.stroke();
      ctx.restore();
      break;
    }
    case 'wall': {
      // Translucent band preview at the default wall thickness, plus a
      // dashed centerline overlay for the in-progress polyline.
      const t = 200;
      ctx.save();
      ctx.lineCap = 'butt';
      ctx.lineJoin = 'miter';
      ctx.setLineDash([]);
      ctx.globalAlpha = 0.25;
      ctx.lineWidth = t;
      ctx.beginPath();
      ctx.moveTo(d.points[0].x, d.points[0].y);
      for (let i = 1; i < d.points.length; i++) ctx.lineTo(d.points[i].x, d.points[i].y);
      ctx.lineTo(cur.x, cur.y);
      ctx.stroke();
      // Centerline on top
      ctx.globalAlpha = 1;
      ctx.lineWidth = 0.5;
      ctx.setLineDash([1, 1]);
      ctx.beginPath();
      ctx.moveTo(d.points[0].x, d.points[0].y);
      for (let i = 1; i < d.points.length; i++) ctx.lineTo(d.points[i].x, d.points[i].y);
      ctx.lineTo(cur.x, cur.y);
      ctx.stroke();
      ctx.restore();
      break;
    }
    case 'room': {
      const a = d.points[0];
      ctx.strokeRect(
        Math.min(a.x, cur.x),
        Math.min(a.y, cur.y),
        Math.abs(cur.x - a.x),
        Math.abs(cur.y - a.y)
      );
      break;
    }
    case 'dimension': {
      if (d.points.length === 1) {
        ctx.beginPath();
        ctx.moveTo(d.points[0].x, d.points[0].y);
        ctx.lineTo(cur.x, cur.y);
        ctx.stroke();
      }
      break;
    }
    case 'measure': {
      if (d.points.length === 1) {
        const a = d.points[0];
        ctx.beginPath();
        ctx.moveTo(a.x, a.y);
        ctx.lineTo(cur.x, cur.y);
        ctx.stroke();
      }
      break;
    }
  }
  ctx.restore();
};

const drawPinHighlights = (
  ctx: CanvasRenderingContext2D,
  sheet: Sheet,
  editor: EditorState,
  opts: RenderOptions,
  layerVisible: (id: string) => boolean
) => {
  // pulse pin on hover
  const cursor = editor.cursorSnap ?? editor.cursor;
  for (const id of sheet.entityOrder) {
    const e = sheet.entities[id];
    if (!e || !e.visible || !layerVisible(e.layerId)) continue;
    if (e.kind !== 'symbol') continue;
    const def = opts.symbolLookup(e.symbolId);
    if (!def) continue;
    for (const pin of def.pins) {
      const wp = transformSymbolPoint(e, pin.position);
      const d = Math.hypot(wp.x - cursor.x, wp.y - cursor.y);
      if (d < 3) {
        ctx.save();
        ctx.strokeStyle = PIN_COLOR;
        ctx.fillStyle = 'rgba(59,163,255,0.2)';
        ctx.lineWidth = 0.3;
        ctx.beginPath();
        ctx.arc(wp.x, wp.y, 1.4, 0, Math.PI * 2);
        ctx.fill();
        ctx.stroke();
        ctx.restore();
      }
    }
  }
};

const drawSnapIndicator = (
  ctx: CanvasRenderingContext2D,
  editor: EditorState,
  opts: RenderOptions
) => {
  const v = editor.viewport;
  const w = opts.width;
  const h = opts.height;
  const sp = worldToScreen(editor.cursorSnap!, v, w, h);
  const kind = editor.cursorSnapKind;

  ctx.save();
  ctx.lineWidth = 1.5;

  // Grid snap uses the original amber color; object snaps use green
  const isOSnap = kind !== 'grid' && kind !== 'none';
  const color = isOSnap ? SNAP_COLOR : SNAP_GRID_COLOR;
  ctx.strokeStyle = color;
  ctx.fillStyle = color;

  const sz = 5; // half-size of markers in screen pixels

  switch (kind) {
    case 'endpoint':
      // Small square, unfilled
      ctx.strokeRect(sp.x - sz, sp.y - sz, sz * 2, sz * 2);
      break;
    case 'midpoint':
      // Small triangle pointing up
      ctx.beginPath();
      ctx.moveTo(sp.x, sp.y - sz);
      ctx.lineTo(sp.x - sz, sp.y + sz);
      ctx.lineTo(sp.x + sz, sp.y + sz);
      ctx.closePath();
      ctx.stroke();
      break;
    case 'center':
      // Circle with crosshair
      ctx.beginPath();
      ctx.arc(sp.x, sp.y, sz, 0, Math.PI * 2);
      ctx.stroke();
      ctx.beginPath();
      ctx.moveTo(sp.x - sz * 0.6, sp.y);
      ctx.lineTo(sp.x + sz * 0.6, sp.y);
      ctx.moveTo(sp.x, sp.y - sz * 0.6);
      ctx.lineTo(sp.x, sp.y + sz * 0.6);
      ctx.stroke();
      break;
    case 'intersection':
      // X mark
      ctx.beginPath();
      ctx.moveTo(sp.x - sz, sp.y - sz);
      ctx.lineTo(sp.x + sz, sp.y + sz);
      ctx.moveTo(sp.x + sz, sp.y - sz);
      ctx.lineTo(sp.x - sz, sp.y + sz);
      ctx.stroke();
      break;
    case 'pin':
      // Diamond shape
      ctx.beginPath();
      ctx.moveTo(sp.x, sp.y - sz);
      ctx.lineTo(sp.x + sz, sp.y);
      ctx.lineTo(sp.x, sp.y + sz);
      ctx.lineTo(sp.x - sz, sp.y);
      ctx.closePath();
      ctx.stroke();
      break;
    case 'perpendicular':
      // Perpendicular symbol: L-shape rotated
      ctx.beginPath();
      ctx.moveTo(sp.x - sz, sp.y + sz);
      ctx.lineTo(sp.x - sz, sp.y - sz);
      ctx.lineTo(sp.x + sz, sp.y - sz);
      ctx.stroke();
      // Small square at the corner
      ctx.strokeRect(sp.x - sz, sp.y - sz, sz * 0.6, sz * 0.6);
      break;
    case 'grid':
    default:
      // Small square with inner cross (original style)
      ctx.strokeRect(sp.x - sz, sp.y - sz, sz * 2, sz * 2);
      ctx.beginPath();
      ctx.moveTo(sp.x - 2, sp.y);
      ctx.lineTo(sp.x + 2, sp.y);
      ctx.moveTo(sp.x, sp.y - 2);
      ctx.lineTo(sp.x, sp.y + 2);
      ctx.stroke();
      break;
  }

  // Label the snap type for non-grid snaps
  if (isOSnap) {
    const labels: Record<string, string> = {
      endpoint: 'END',
      midpoint: 'MID',
      center: 'CEN',
      intersection: 'INT',
      pin: 'PIN',
      perpendicular: 'PER',
    };
    const label = labels[kind] ?? '';
    if (label) {
      ctx.font = '9px ui-monospace, monospace';
      ctx.textAlign = 'left';
      ctx.textBaseline = 'bottom';
      ctx.fillText(label, sp.x + sz + 3, sp.y - sz);
    }
  }

  ctx.restore();
};

const drawCrosshair = (
  ctx: CanvasRenderingContext2D,
  editor: EditorState,
  opts: RenderOptions
) => {
  const v = editor.viewport;
  const c = editor.cursorSnap ?? editor.cursor;
  const sp = worldToScreen(c, v, opts.width, opts.height);
  ctx.save();
  ctx.strokeStyle = 'rgba(155, 200, 255, 0.4)';
  ctx.lineWidth = 0.7;
  ctx.setLineDash([2, 3]);
  ctx.beginPath();
  ctx.moveTo(0, sp.y);
  ctx.lineTo(opts.width, sp.y);
  ctx.moveTo(sp.x, 0);
  ctx.lineTo(sp.x, opts.height);
  ctx.stroke();
  ctx.setLineDash([]);
  ctx.restore();
};

export const getEntityIds = (sheet: Sheet): EntityId[] => sheet.entityOrder;

// ============================================================================
// New entity-kind support
// ----------------------------------------------------------------------------
// These entity kinds aren't yet part of the strict Entity union in types.ts.
// They are handled via a structural AnyEntity record so the renderer can draw
// them today and seamlessly upgrade to typed access once types.ts catches up.
// ============================================================================

/** Catalog of entity kinds the early-dispatch handles. */
const NEW_ENTITY_KINDS = new Set<string>([
  'fitting',
  'support',
  'equipment',
  'riser',
  'fire-barrier',
  'penetration',
  'leader',
  'section-marker',
  'level-marker',
  'north-arrow',
  'scale-bar',
  'grid-line',
  'revision-cloud',
  'cloud',
  'underlay',
]);

/** Loose record type used by the new-kind handlers. */
type AnyEntity = {
  id: string;
  kind: string;
  layerId: string;
  visible?: boolean;
  locked?: boolean;
  color?: string;
  lineWidth?: number;
  lineDash?: number[];
  // common positional fields that the new entities pull from
  position?: Vec2;
  rotation?: number;
  size?: number;
  width?: number;
  height?: number;
  a?: Vec2;
  b?: Vec2;
  points?: Vec2[];
  // fitting / support
  fittingKind?: string;
  supportKind?: string;
  containmentId?: string;
  autoGenerated?: boolean;
  // equipment
  equipmentKind?: string;
  tag?: string;
  connections?: Vec2[];
  // riser
  fromElevation?: number;
  toElevation?: number;
  riserType?: string;
  // fire-barrier
  rating?: number | string;
  fireRating?: number | string;
  // penetration
  status?: 'approved' | 'pending' | 'flagged' | 'failed';
  reference?: string;
  // leader
  text?: string;
  arrowStyle?: string;
  // section-marker
  viewDirection?: number;
  label?: string;
  // level-marker
  elevation?: number;
  // north-arrow
  northAngle?: number;
  // scale-bar
  segmentLength?: number;
  segments?: number;
  scale?: number | string;
  // grid-line
  // revision-cloud
  revisionTag?: string;
  // underlay
  imageDataUrl?: string;
  vectors?: { a: Vec2; b: Vec2 }[];
  opacity?: number;
};

/** Compute a generous bounds rectangle for any new-kind entity. */
const newKindBounds = (e: AnyEntity): { minX: number; minY: number; maxX: number; maxY: number } | null => {
  const expand = (b: { minX: number; minY: number; maxX: number; maxY: number }, p: Vec2) => {
    if (p.x < b.minX) b.minX = p.x;
    if (p.y < b.minY) b.minY = p.y;
    if (p.x > b.maxX) b.maxX = p.x;
    if (p.y > b.maxY) b.maxY = p.y;
  };
  const b = { minX: Infinity, minY: Infinity, maxX: -Infinity, maxY: -Infinity };
  if (e.position) expand(b, e.position);
  if (e.a) expand(b, e.a);
  if (e.b) expand(b, e.b);
  if (e.points) for (const p of e.points) expand(b, p);
  if (!isFinite(b.minX)) return null;
  // Pad single-point entities so the selection box reads
  if (e.size || e.width || e.height) {
    const pad = Math.max(e.size ?? 0, e.width ?? 0, e.height ?? 0) * 0.5;
    b.minX -= pad; b.minY -= pad; b.maxX += pad; b.maxY += pad;
  } else if (b.minX === b.maxX && b.minY === b.maxY) {
    const pad = 5;
    b.minX -= pad; b.minY -= pad; b.maxX += pad; b.maxY += pad;
  }
  return b;
};

/** Selection box for new-kind entities. Mirrors drawSelectionBox style. */
const drawSelectionBoxFor = (ctx: CanvasRenderingContext2D, e: AnyEntity) => {
  const bb = newKindBounds(e);
  if (!bb) return;
  const pad = 1.5;
  ctx.save();
  ctx.strokeStyle = SELECTION_COLOR;
  ctx.lineWidth = 0.3;
  ctx.setLineDash([1.2, 1]);
  ctx.strokeRect(
    bb.minX - pad,
    bb.minY - pad,
    bb.maxX - bb.minX + pad * 2,
    bb.maxY - bb.minY + pad * 2
  );
  ctx.setLineDash([]);
  ctx.restore();
};

const strokeColorFor = (state: { isSelected: boolean; isHovered: boolean }, base: string): string =>
  state.isSelected ? SELECTION_COLOR : state.isHovered ? HOVER_COLOR : base;

/** Render text in the y-flipped world frame. */
const drawWorldText = (
  ctx: CanvasRenderingContext2D,
  text: string,
  x: number,
  y: number,
  size: number,
  color: string,
  align: CanvasTextAlign = 'center',
  baseline: CanvasTextBaseline = 'middle',
  font = 'sans-serif'
) => {
  ctx.save();
  ctx.translate(x, y);
  ctx.scale(1, -1);
  ctx.fillStyle = color;
  ctx.font = `${size}px ${font}`;
  ctx.textAlign = align;
  ctx.textBaseline = baseline;
  ctx.fillText(text, 0, 0);
  ctx.restore();
};

// ----- fitting -----------------------------------------------------------

const drawFitting = (
  ctx: CanvasRenderingContext2D,
  e: AnyEntity,
  color: string,
  lineWidth: number,
  state: DrawState
) => {
  const pos = e.position ?? { x: 0, y: 0 };
  const rot = e.rotation ?? 0;
  const w = Math.max(4, e.width ?? e.size ?? 8);
  const stroke = strokeColorFor(state, color);

  ctx.save();
  ctx.translate(pos.x, pos.y);
  ctx.rotate(rot);
  ctx.strokeStyle = stroke;
  ctx.fillStyle = stroke;
  ctx.lineWidth = lineWidth;

  const half = w / 2;
  switch (e.fittingKind) {
    case 'flat-bend':
    case 'inside-riser':
    case 'outside-riser':
      ctx.beginPath();
      ctx.arc(0, 0, half, 0, Math.PI / 2);
      ctx.stroke();
      break;
    case 'tee':
      ctx.beginPath();
      ctx.moveTo(-half, 0);
      ctx.lineTo(half, 0);
      ctx.moveTo(0, 0);
      ctx.lineTo(0, half);
      ctx.stroke();
      break;
    case 'cross':
      ctx.beginPath();
      ctx.moveTo(-half, 0);
      ctx.lineTo(half, 0);
      ctx.moveTo(0, -half);
      ctx.lineTo(0, half);
      ctx.stroke();
      break;
    case 'reducer':
      ctx.beginPath();
      ctx.moveTo(-half, -half);
      ctx.lineTo(half, -half * 0.5);
      ctx.lineTo(half, half * 0.5);
      ctx.lineTo(-half, half);
      ctx.closePath();
      ctx.stroke();
      break;
    case 'end-cap':
      ctx.strokeRect(-half, -half, w, w);
      ctx.beginPath();
      ctx.moveTo(half, -half);
      ctx.lineTo(half, half);
      ctx.lineWidth = lineWidth * 2;
      ctx.stroke();
      break;
    case 'coupler':
      ctx.strokeRect(-half, -half * 0.4, w, w * 0.4);
      break;
    case 'end-plate':
      ctx.strokeRect(-half * 0.6, -half * 0.6, w * 0.6, w * 0.6);
      break;
    default:
      // Generic glyph — small diamond
      ctx.beginPath();
      ctx.moveTo(0, -half);
      ctx.lineTo(half, 0);
      ctx.lineTo(0, half);
      ctx.lineTo(-half, 0);
      ctx.closePath();
      ctx.stroke();
  }
  ctx.restore();

  // Hover/select label with the fittingKind code (e.g. "B45")
  if (state.isSelected || state.isHovered) {
    const code = (e.fittingKind ?? '').slice(0, 6).toUpperCase();
    if (code) {
      drawWorldText(ctx, code, pos.x, pos.y - w * 0.9, Math.max(2.4, w * 0.4), '#9aa3b2', 'center', 'top', 'ui-monospace, monospace');
    }
  }
};

// ----- support ----------------------------------------------------------

const drawSupport = (
  ctx: CanvasRenderingContext2D,
  e: AnyEntity,
  _color: string,
  lineWidth: number,
  state: DrawState
) => {
  // Hide at very low zoom — supports are dense and mostly noise far out.
  if (state.zoom < 1) return;
  const pos = e.position ?? { x: 0, y: 0 };
  const rot = e.rotation ?? 0;
  const w = Math.max(4, e.width ?? e.size ?? 12);
  const stroke = strokeColorFor(state, '#a8aab0');

  ctx.save();
  ctx.translate(pos.x, pos.y);
  ctx.rotate(rot);
  ctx.strokeStyle = stroke;
  ctx.fillStyle = stroke;
  ctx.lineWidth = Math.max(0.4, lineWidth * 0.8);

  const half = w / 2;
  switch (e.supportKind) {
    case 'trapeze-hanger':
      // ∩ shape
      ctx.beginPath();
      ctx.moveTo(-half, 0);
      ctx.lineTo(-half, -half);
      ctx.lineTo(half, -half);
      ctx.lineTo(half, 0);
      ctx.stroke();
      break;
    case 'wall-bracket':
    case 'cantilever-arm':
      ctx.beginPath();
      ctx.moveTo(0, -half);
      ctx.lineTo(half, 0);
      ctx.lineTo(0, half);
      ctx.closePath();
      ctx.stroke();
      break;
    case 'saddle-clip':
      ctx.beginPath();
      ctx.arc(0, 0, half * 0.7, 0, Math.PI * 2);
      ctx.stroke();
      break;
    case 'beam-clamp':
      ctx.strokeRect(-half * 0.6, -half * 0.4, w * 0.6, w * 0.8);
      ctx.beginPath();
      ctx.moveTo(-half, -half);
      ctx.lineTo(half, -half);
      ctx.stroke();
      break;
    default:
      ctx.strokeRect(-half * 0.5, -half * 0.5, w * 0.5, w * 0.5);
  }
  ctx.restore();
};

// ----- equipment --------------------------------------------------------

const equipmentColors: Record<string, { fill: string; border: string }> = {
  'distribution-board': { fill: '#3b2e6b', border: '#bb8cff' },
  'panelboard': { fill: '#3b2e6b', border: '#bb8cff' },
  'mcc': { fill: '#3b2e6b', border: '#bb8cff' },
  'switchboard': { fill: '#3b2e6b', border: '#bb8cff' },
  'transformer': { fill: '#1f3a1f', border: '#5fbf5f' },
  'generator': { fill: '#3a2a14', border: '#ff9a3a' },
  'ups': { fill: '#3a2a14', border: '#ff9a3a' },
  'motor': { fill: '#1c2a40', border: '#5cdcff' },
  'pump': { fill: '#1c2a40', border: '#5cdcff' },
  'fan': { fill: '#1c2a40', border: '#5cdcff' },
  'fire-alarm-panel': { fill: '#3a1414', border: '#ff5d5d' },
  'comms-rack': { fill: '#1f2229', border: '#7a8593' },
};

const drawEquipment = (
  ctx: CanvasRenderingContext2D,
  e: AnyEntity,
  color: string,
  lineWidth: number,
  state: DrawState
) => {
  const a = e.a ?? e.position ?? { x: 0, y: 0 };
  const b = e.b ?? { x: a.x + (e.width ?? 100), y: a.y + (e.height ?? 60) };
  const rot = e.rotation ?? 0;
  const cx = (a.x + b.x) / 2;
  const cy = (a.y + b.y) / 2;
  const w = Math.abs(b.x - a.x);
  const h = Math.abs(b.y - a.y);
  if (w <= 0 || h <= 0) return;

  const palette = equipmentColors[e.equipmentKind ?? ''] ?? { fill: '#2a3040', border: '#a8aab0' };
  const border = state.isSelected ? SELECTION_COLOR : state.isHovered ? HOVER_COLOR : (color || palette.border);

  ctx.save();
  ctx.translate(cx, cy);
  ctx.rotate(rot);
  ctx.fillStyle = palette.fill;
  ctx.strokeStyle = border;
  ctx.lineWidth = Math.max(0.5, lineWidth);
  ctx.fillRect(-w / 2, -h / 2, w, h);
  ctx.strokeRect(-w / 2, -h / 2, w, h);

  // Tag label centered
  if (e.tag) {
    const fs = Math.min(h / 3, 24);
    ctx.save();
    ctx.scale(1, -1);
    ctx.fillStyle = '#e6e8ec';
    ctx.font = `bold ${Math.max(2.5, fs)}px sans-serif`;
    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';
    ctx.fillText(e.tag, 0, 0);
    ctx.restore();
  }
  ctx.restore();

  // Connection dots in world space
  if (e.connections && e.connections.length > 0) {
    ctx.fillStyle = PIN_COLOR;
    for (const p of e.connections) {
      ctx.beginPath();
      ctx.arc(p.x, p.y, Math.max(0.6, lineWidth * 1.2), 0, Math.PI * 2);
      ctx.fill();
    }
  }
};

// ----- riser ------------------------------------------------------------

const drawRiser = (
  ctx: CanvasRenderingContext2D,
  e: AnyEntity,
  color: string,
  lineWidth: number,
  state: DrawState
) => {
  const pos = e.position ?? { x: 0, y: 0 };
  const w = e.width ?? e.size ?? 30;
  const h = e.height ?? w;
  const stroke = strokeColorFor(state, color);
  const goingUp = (e.fromElevation ?? 0) < (e.toElevation ?? 1);

  ctx.save();
  ctx.translate(pos.x, pos.y);
  ctx.strokeStyle = stroke;
  ctx.fillStyle = stroke;
  ctx.lineWidth = Math.max(0.4, lineWidth);
  ctx.setLineDash([2, 1.5]);
  ctx.strokeRect(-w / 2, -h / 2, w, h);
  ctx.setLineDash([]);

  // Direction arrow inside the box
  const arrow = goingUp ? '↑' : '↓';
  drawWorldText(ctx, arrow, 0, 0, Math.min(w, h) * 0.7, stroke, 'center', 'middle');
  ctx.restore();

  // Label below
  const label = e.riserType ?? (goingUp ? 'RISER UP' : 'RISER DN');
  drawWorldText(ctx, label, pos.x, pos.y - h / 2 - 2, Math.max(2.5, h * 0.18), '#9aa3b2', 'center', 'top', 'ui-monospace, monospace');
};

// ----- fire-barrier -----------------------------------------------------

const drawFireBarrier = (
  ctx: CanvasRenderingContext2D,
  e: AnyEntity,
  _color: string,
  lineWidth: number,
  state: DrawState
) => {
  const pts = e.points ?? [];
  if (pts.length < 2) return;
  const stroke = strokeColorFor(state, '#ff5d5d');

  ctx.save();
  ctx.strokeStyle = stroke;
  ctx.lineWidth = Math.max(1.0, lineWidth * 2);
  ctx.setLineDash([4, 2]);
  ctx.beginPath();
  ctx.moveTo(pts[0].x, pts[0].y);
  for (let i = 1; i < pts.length; i++) ctx.lineTo(pts[i].x, pts[i].y);
  ctx.stroke();
  ctx.setLineDash([]);
  ctx.restore();

  // Label near midpoint with fire rating (e.g. "FB-60")
  const midIdx = Math.floor(pts.length / 2);
  const m1 = pts[midIdx - 1] ?? pts[0];
  const m2 = pts[midIdx] ?? pts[pts.length - 1];
  const mx = (m1.x + m2.x) / 2;
  const my = (m1.y + m2.y) / 2;
  const rating = e.fireRating ?? e.rating;
  const ratingLabel = rating !== undefined ? `FB-${rating}` : 'FB';
  drawWorldText(ctx, ratingLabel, mx, my + 3, 3, '#ff7a7a', 'center', 'middle', 'ui-monospace, monospace');
};

// ----- penetration ------------------------------------------------------

const drawPenetration = (
  ctx: CanvasRenderingContext2D,
  e: AnyEntity,
  _color: string,
  lineWidth: number,
  state: DrawState
) => {
  const pos = e.position ?? { x: 0, y: 0 };
  const r = (e.size ?? e.width ?? 8) / 2;
  const statusColor: Record<string, string> = {
    approved: '#5fbf5f',
    flagged: '#ffb14d',
    failed: '#ff5d5d',
  };
  const base = statusColor[e.status ?? ''] ?? '#9aa3b2';
  const stroke = strokeColorFor(state, base);

  ctx.save();
  ctx.translate(pos.x, pos.y);
  ctx.strokeStyle = stroke;
  ctx.fillStyle = stroke;
  ctx.lineWidth = Math.max(0.4, lineWidth);
  ctx.beginPath();
  ctx.arc(0, 0, r, 0, Math.PI * 2);
  ctx.stroke();
  // Diagonal cross — fire-stop symbol
  const d = r * 0.7;
  ctx.beginPath();
  ctx.moveTo(-d, -d);
  ctx.lineTo(d, d);
  ctx.moveTo(-d, d);
  ctx.lineTo(d, -d);
  ctx.stroke();
  ctx.restore();

  if (e.reference) {
    drawWorldText(ctx, e.reference, pos.x + r + 1.5, pos.y, 2.4, '#9aa3b2', 'left', 'middle', 'ui-monospace, monospace');
  }
};

// ----- leader -----------------------------------------------------------

const drawLeader = (
  ctx: CanvasRenderingContext2D,
  e: AnyEntity,
  color: string,
  lineWidth: number,
  state: DrawState
) => {
  const pts = e.points ?? [];
  if (pts.length < 2) return;
  const stroke = strokeColorFor(state, color);

  ctx.save();
  ctx.strokeStyle = stroke;
  ctx.fillStyle = stroke;
  ctx.lineWidth = Math.max(0.4, lineWidth);
  ctx.beginPath();
  ctx.moveTo(pts[0].x, pts[0].y);
  for (let i = 1; i < pts.length; i++) ctx.lineTo(pts[i].x, pts[i].y);
  ctx.stroke();

  // Arrow at points[0]
  const tip = pts[0];
  const next = pts[1];
  const ang = Math.atan2(next.y - tip.y, next.x - tip.x);
  const sz = e.arrowStyle === 'dot' ? 0 : 1.5;
  if (e.arrowStyle === 'dot') {
    ctx.beginPath();
    ctx.arc(tip.x, tip.y, 0.8, 0, Math.PI * 2);
    ctx.fill();
  } else {
    drawArrowhead(ctx, tip.x, tip.y, ang + Math.PI, sz);
  }
  ctx.restore();

  // Text at the last point
  if (e.text) {
    const last = pts[pts.length - 1];
    drawWorldText(ctx, e.text, last.x + 1.5, last.y, 3, stroke, 'left', 'middle');
  }
};

// ----- section-marker --------------------------------------------------

const drawSectionMarker = (
  ctx: CanvasRenderingContext2D,
  e: AnyEntity,
  _color: string,
  lineWidth: number,
  state: DrawState
) => {
  const a = e.a ?? { x: 0, y: 0 };
  const b = e.b ?? { x: a.x + 50, y: a.y };
  const stroke = strokeColorFor(state, '#1f2229');

  ctx.save();
  ctx.strokeStyle = stroke;
  ctx.fillStyle = stroke;
  ctx.lineWidth = Math.max(0.8, lineWidth * 1.6);
  ctx.beginPath();
  ctx.moveTo(a.x, a.y);
  ctx.lineTo(b.x, b.y);
  ctx.stroke();

  // Arrows at each end pointing in viewDirection
  const dir = e.viewDirection ?? Math.atan2(b.y - a.y, b.x - a.x) + Math.PI / 2;
  const arrLen = 4;
  for (const p of [a, b]) {
    const tipX = p.x + Math.cos(dir) * arrLen;
    const tipY = p.y + Math.sin(dir) * arrLen;
    ctx.beginPath();
    ctx.moveTo(p.x, p.y);
    ctx.lineTo(tipX, tipY);
    ctx.stroke();
    drawArrowhead(ctx, tipX, tipY, dir, 1.5);
  }

  // Bubble at midpoint
  const cx = (a.x + b.x) / 2;
  const cy = (a.y + b.y) / 2;
  ctx.fillStyle = '#0d131c';
  ctx.beginPath();
  ctx.arc(cx, cy, 4, 0, Math.PI * 2);
  ctx.fill();
  ctx.stroke();
  ctx.restore();

  if (e.label) {
    drawWorldText(ctx, e.label, cx, cy, 3, '#e6e8ec', 'center', 'middle', 'ui-monospace, monospace');
  }
};

// ----- level-marker ----------------------------------------------------

const drawLevelMarker = (
  ctx: CanvasRenderingContext2D,
  e: AnyEntity,
  color: string,
  lineWidth: number,
  state: DrawState
) => {
  const pos = e.position ?? { x: 0, y: 0 };
  const stroke = strokeColorFor(state, color);

  ctx.save();
  ctx.translate(pos.x, pos.y);
  ctx.strokeStyle = stroke;
  ctx.fillStyle = stroke;
  ctx.lineWidth = Math.max(0.4, lineWidth);
  // Triangle pointing up at the level mark
  ctx.beginPath();
  ctx.moveTo(0, 0);
  ctx.lineTo(-2.5, 4);
  ctx.lineTo(2.5, 4);
  ctx.closePath();
  ctx.stroke();
  // Horizontal reference line
  ctx.beginPath();
  ctx.moveTo(-6, 4);
  ctx.lineTo(6, 4);
  ctx.stroke();
  ctx.restore();

  const elev = e.elevation ?? 0;
  const sign = elev >= 0 ? '+' : '';
  const label = `FFL ${sign}${elev.toFixed(2)}`;
  drawWorldText(ctx, label, pos.x + 7, pos.y + 4, 3, '#e6e8ec', 'left', 'middle', 'ui-monospace, monospace');
};

// ----- north-arrow -----------------------------------------------------

const drawNorthArrow = (
  ctx: CanvasRenderingContext2D,
  e: AnyEntity,
  _color: string,
  lineWidth: number,
  state: DrawState
) => {
  const pos = e.position ?? { x: 0, y: 0 };
  const size = e.size ?? 200;
  const r = size / 2;
  const angle = e.northAngle ?? 0;
  const stroke = strokeColorFor(state, '#e6e8ec');

  ctx.save();
  ctx.translate(pos.x, pos.y);
  ctx.rotate(angle);
  ctx.strokeStyle = stroke;
  ctx.fillStyle = stroke;
  ctx.lineWidth = Math.max(0.6, lineWidth);

  // Outer circle
  ctx.beginPath();
  ctx.arc(0, 0, r, 0, Math.PI * 2);
  ctx.stroke();

  // Stylised arrow pointing up
  ctx.beginPath();
  ctx.moveTo(0, r * 0.85);
  ctx.lineTo(-r * 0.25, -r * 0.25);
  ctx.lineTo(0, 0);
  ctx.lineTo(r * 0.25, -r * 0.25);
  ctx.closePath();
  ctx.fill();

  ctx.beginPath();
  ctx.moveTo(0, 0);
  ctx.lineTo(0, -r * 0.7);
  ctx.stroke();

  // "N" label at top of circle
  ctx.save();
  ctx.translate(0, r * 0.55);
  ctx.scale(1, -1);
  ctx.fillStyle = stroke;
  ctx.font = `bold ${Math.max(4, r * 0.35)}px sans-serif`;
  ctx.textAlign = 'center';
  ctx.textBaseline = 'middle';
  ctx.fillText('N', 0, 0);
  ctx.restore();

  ctx.restore();
};

// ----- scale-bar -------------------------------------------------------

const drawScaleBar = (
  ctx: CanvasRenderingContext2D,
  e: AnyEntity,
  _color: string,
  lineWidth: number,
  state: DrawState
) => {
  const pos = e.position ?? { x: 0, y: 0 };
  const segLen = e.segmentLength ?? 10;
  const segs = Math.max(1, Math.floor(e.segments ?? 5));
  const total = segLen * segs;
  const h = Math.max(2, segLen * 0.3);
  const stroke = strokeColorFor(state, '#e6e8ec');

  ctx.save();
  ctx.translate(pos.x, pos.y);
  ctx.strokeStyle = stroke;
  ctx.lineWidth = Math.max(0.4, lineWidth);
  ctx.strokeRect(0, 0, total, h);

  for (let i = 0; i < segs; i++) {
    if (i % 2 === 0) {
      ctx.fillStyle = stroke;
      ctx.fillRect(i * segLen, 0, segLen, h);
    }
    // tick label below each junction
    const tickVal = i * segLen;
    drawWorldText(ctx, String(tickVal), i * segLen, -1, Math.max(1.8, h * 0.6), '#9aa3b2', 'center', 'top', 'ui-monospace, monospace');
  }
  // last tick
  drawWorldText(ctx, String(total), total, -1, Math.max(1.8, h * 0.6), '#9aa3b2', 'center', 'top', 'ui-monospace, monospace');

  ctx.restore();

  const scaleLabel = e.scale !== undefined ? `SCALE 1:${e.scale}` : 'SCALE BAR';
  drawWorldText(ctx, scaleLabel, pos.x + total / 2, pos.y - h * 1.6, Math.max(2.4, h), '#e6e8ec', 'center', 'top', 'sans-serif');
};

// ----- grid-line -------------------------------------------------------

const drawGridLine = (
  ctx: CanvasRenderingContext2D,
  e: AnyEntity,
  color: string,
  lineWidth: number,
  state: DrawState
) => {
  const a = e.a ?? e.position;
  const b = e.b;
  if (!a || !b) return;
  const stroke = strokeColorFor(state, color || '#5d6473');

  ctx.save();
  ctx.strokeStyle = stroke;
  ctx.lineWidth = Math.max(0.2, lineWidth * 0.6);
  ctx.setLineDash([6, 3, 1, 3]);
  ctx.beginPath();
  ctx.moveTo(a.x, a.y);
  ctx.lineTo(b.x, b.y);
  ctx.stroke();
  ctx.setLineDash([]);

  // Bubble at start endpoint with the label
  const r = 4;
  ctx.fillStyle = '#0d131c';
  ctx.beginPath();
  ctx.arc(a.x, a.y, r, 0, Math.PI * 2);
  ctx.fill();
  ctx.stroke();
  ctx.restore();

  if (e.label) {
    drawWorldText(ctx, e.label, a.x, a.y, 3, '#e6e8ec', 'center', 'middle', 'ui-monospace, monospace');
  }
};

// ----- revision-cloud / cloud ------------------------------------------

const drawCloudEntity = (
  ctx: CanvasRenderingContext2D,
  e: AnyEntity,
  isRevision: boolean,
  color: string,
  lineWidth: number,
  state: DrawState
) => {
  const pts = e.points ?? [];
  if (pts.length < 2) return;
  const stroke = strokeColorFor(state, color);

  ctx.save();
  ctx.strokeStyle = stroke;
  ctx.lineWidth = Math.max(0.4, lineWidth);
  ctx.setLineDash([1.5, 1]);

  // Render a series of arc bumps along each segment so the boundary reads
  // as a "cloud" without expensive Bezier offset math.
  const arcRadius = 3;
  for (let i = 0; i < pts.length; i++) {
    const a = pts[i];
    const b = pts[(i + 1) % pts.length];
    const dx = b.x - a.x;
    const dy = b.y - a.y;
    const len = Math.hypot(dx, dy);
    if (len < 0.001) continue;
    const ux = dx / len;
    const uy = dy / len;
    const px = -uy;
    const py = ux;
    const segCount = Math.max(1, Math.round(len / (arcRadius * 1.6)));
    const segLen = len / segCount;
    for (let s = 0; s < segCount; s++) {
      const cx = a.x + ux * (segLen * (s + 0.5));
      const cy = a.y + uy * (segLen * (s + 0.5));
      const ang = Math.atan2(uy, ux);
      // Outward bump (px,py points to the left of the segment direction)
      ctx.beginPath();
      ctx.arc(cx + px * arcRadius * 0.0, cy + py * arcRadius * 0.0, segLen / 2, ang + Math.PI, ang);
      ctx.stroke();
    }
  }
  ctx.setLineDash([]);
  ctx.restore();

  if (isRevision && pts.length > 0) {
    const p = pts[0];
    const sz = 4;
    ctx.save();
    ctx.fillStyle = '#ff7a7a';
    ctx.strokeStyle = '#ff7a7a';
    ctx.lineWidth = 0.4;
    ctx.beginPath();
    ctx.moveTo(p.x - sz, p.y + sz);
    ctx.lineTo(p.x + sz, p.y + sz);
    ctx.lineTo(p.x, p.y);
    ctx.closePath();
    ctx.fill();
    ctx.restore();
    if (e.revisionTag) {
      drawWorldText(ctx, e.revisionTag, p.x, p.y + sz + 0.5, 2.5, '#0d131c', 'center', 'middle', 'ui-monospace, monospace');
    }
  }
};

// ----- underlay --------------------------------------------------------

// Cache decoded underlay images by data-URL so we don't decode every frame.
const underlayImageCache = new Map<string, HTMLImageElement>();
const getUnderlayImage = (dataUrl: string): HTMLImageElement | null => {
  const cached = underlayImageCache.get(dataUrl);
  if (cached) return cached.complete && cached.naturalWidth > 0 ? cached : null;
  const img = new Image();
  img.src = dataUrl;
  underlayImageCache.set(dataUrl, img);
  return img.complete && img.naturalWidth > 0 ? img : null;
};

const drawUnderlay = (ctx: CanvasRenderingContext2D, e: AnyEntity) => {
  const opacity = e.opacity ?? 0.5;
  ctx.save();
  ctx.globalAlpha = opacity;

  if (e.imageDataUrl) {
    const img = getUnderlayImage(e.imageDataUrl);
    if (img) {
      const w = e.width ?? img.naturalWidth;
      const h = e.height ?? img.naturalHeight;
      const pos = e.position ?? { x: 0, y: 0 };
      // y is flipped — drawImage expects screen-orientation coords. Mirror Y so
      // the image reads upright in the world view.
      ctx.save();
      ctx.translate(pos.x, pos.y + h);
      ctx.scale(1, -1);
      try {
        ctx.drawImage(img, 0, 0, w, h);
      } catch {
        // ignore decode errors
      }
      ctx.restore();
    }
  }

  if (e.vectors && e.vectors.length > 0) {
    ctx.strokeStyle = e.color ?? '#7a8593';
    ctx.lineWidth = e.lineWidth ?? 0.3;
    ctx.beginPath();
    for (const seg of e.vectors) {
      ctx.moveTo(seg.a.x, seg.a.y);
      ctx.lineTo(seg.b.x, seg.b.y);
    }
    ctx.stroke();
  }

  ctx.restore();
};

// ----- compliance overlay ----------------------------------------------

const drawComplianceOverlay = (
  ctx: CanvasRenderingContext2D,
  sheet: Sheet,
  project: Project,
  mode: 'fill' | 'segregation' | 'support-spacing'
): void => {
  if (mode === 'support-spacing') return; // stub for now

  // Try to access cable schedule and standards profile via untyped lookups so
  // this works with both the current project shape and future extensions.
  const projAny = project as unknown as Record<string, unknown>;
  const schedule = projAny.cableSchedule as
    | { cables?: Array<Record<string, unknown>> }
    | undefined;
  const cables = schedule?.cables ?? [];
  const standards = projAny.standardsProfile;

  // Map containmentId -> assigned cable list
  const assigned = new Map<string, Array<Record<string, unknown>>>();
  for (const c of cables) {
    const route = (c.route as { containmentIds?: string[] } | undefined)?.containmentIds ?? [];
    for (const cid of route) {
      const arr = assigned.get(cid) ?? [];
      arr.push(c);
      assigned.set(cid, arr);
    }
  }

  for (const id of sheet.entityOrder) {
    const e = sheet.entities[id] as Entity | undefined;
    if (!e || e.kind !== 'containment') continue;
    const cont = e as import('../types').ContainmentEntity;
    const pts = cont.points;
    if (pts.length < 2) continue;
    const w = cont.width ?? 50;

    if (mode === 'fill') {
      const fillRatio = computeContainmentFillSafe(cont, assigned.get(id) ?? [], standards);
      if (fillRatio === null) continue;
      let tint = '#5fbf5f'; // green
      if (fillRatio > 0.45) tint = '#ff5d5d';
      else if (fillRatio >= 0.35) tint = '#ffb14d';

      ctx.save();
      ctx.strokeStyle = tint;
      ctx.globalAlpha = 0.45;
      ctx.lineWidth = w;
      ctx.lineCap = cont.containmentType === 'conduit' ? 'round' : 'butt';
      ctx.lineJoin = 'round';
      ctx.beginPath();
      ctx.moveTo(pts[0].x, pts[0].y);
      for (let i = 1; i < pts.length; i++) ctx.lineTo(pts[i].x, pts[i].y);
      ctx.stroke();
      ctx.globalAlpha = 1;
      // Percentage label near the start
      drawWorldText(
        ctx,
        `${Math.round(fillRatio * 100)}%`,
        pts[0].x,
        pts[0].y + w * 0.6,
        3,
        tint,
        'center',
        'middle',
        'ui-monospace, monospace'
      );
      ctx.restore();
    } else if (mode === 'segregation') {
      const list = assigned.get(id) ?? [];
      const cats = new Set<string>();
      for (const c of list) {
        const cat = (c.category as string | undefined) ?? (c.segregationGroup as string | undefined);
        if (cat) cats.add(cat);
      }
      if (cats.size > 1) {
        ctx.save();
        ctx.strokeStyle = '#ff5d5d';
        ctx.lineWidth = Math.max(1.0, w * 0.12);
        ctx.setLineDash([3, 2]);
        ctx.beginPath();
        ctx.moveTo(pts[0].x, pts[0].y);
        for (let i = 1; i < pts.length; i++) ctx.lineTo(pts[i].x, pts[i].y);
        ctx.stroke();
        ctx.setLineDash([]);
        ctx.restore();
      }
    }
  }
};

/**
 * Best-effort fill computation. Tries to call computeContainmentFill from
 * '../calc/fill' if present in the project; otherwise falls back to a coarse
 * approximation derived from cable counts and outside diameters.
 */
const computeContainmentFillSafe = (
  cont: import('../types').ContainmentEntity,
  cables: Array<Record<string, unknown>>,
  _standards: unknown
): number | null => {
  if (cables.length === 0) return null;
  const w = cont.width ?? 50;
  const h = cont.height ?? w;
  const containmentArea =
    cont.containmentType === 'conduit'
      ? Math.PI * (w / 2) * (w / 2)
      : w * h;
  if (containmentArea <= 0) return null;
  let cableArea = 0;
  for (const c of cables) {
    const od = (c.outsideDiameter as number | undefined) ?? (c.od as number | undefined) ?? 8;
    cableArea += Math.PI * (od / 2) * (od / 2);
  }
  return Math.min(2, cableArea / containmentArea);
};
