import { afterEach, describe, expect, it, vi } from 'vitest';
import type { ContainmentEntity, FittingEntity, Project, SupportEntity } from '../../types';
import type { InstallationRecord } from '../../models/installation';
import { installationActivities } from '../../models/installation';
import { createEmptyProject } from '../../state/store';
import { loadStoredProject, migrateProject, saveStoredProject } from '../persist';
import { exportProjectJSON, importProjectJSON } from '../project';

const completed: InstallationRecord = {
  status: 'completed', updatedAt: 2000, completedAt: 2000, activities: [
    { id: 'comment', kind: 'comment', text: 'Cable entry and end plate checked', author: 'Installer', createdAt: 1000 },
    { id: 'status', kind: 'status', status: 'completed', previousStatus: 'planned', createdAt: 2000 },
  ],
};
const planned: InstallationRecord = { status: 'planned', updatedAt: 1000, activities: [] };

function buildProject(record: InstallationRecord | undefined = completed): Project {
  const project = createEmptyProject();
  const base = { layerId: project.activeLayerId, visible: true, locked: false };
  const route: ContainmentEntity = {
    ...base, id: 'route', kind: 'containment', containmentType: 'tray', width: 300, height: 100,
    points: [{ x: 0, y: 0 }, { x: 3000, y: 0 }],
  };
  const fitting: FittingEntity = {
    ...base, id: 'fitting', kind: 'fitting', fittingKind: 'end-plate', containmentId: 'route',
    position: { x: 0, y: 0 }, rotation: 0, width: 310, height: 110, autoGenerated: true,
    ...(record ? { installation: structuredClone(record) } : {}),
  };
  const support: SupportEntity = {
    ...base, id: 'support', kind: 'support', supportKind: 'wall-bracket',
    position: { x: 800, y: 0 }, rotation: 0.3, elevation: 2700, rodLength: 725, channelLength: 450,
    anchorType: 'channel-nut', supportingContainmentIds: ['route'], autoGenerated: true,
    ...(record ? { installation: structuredClone(record) } : {}),
  };
  const sheet = project.sheets[project.activeSheetId];
  project.sheets = {
    [sheet.id]: { ...sheet, entities: { route, fitting, support }, entityOrder: ['route', 'fitting', 'support'] },
    untouched: { ...sheet, id: 'untouched', entities: {}, entityOrder: [] },
  };
  project.sheetOrder = [sheet.id, 'untouched'];
  return project;
}

function freezeDeep(value: unknown): void {
  if (!value || typeof value !== 'object' || Object.isFrozen(value)) return;
  Object.freeze(value);
  Object.values(value).forEach(freezeDeep);
}

afterEach(() => vi.unstubAllGlobals());

describe('installation-safe project migrations', () => {
  it.each([completed, planned])('preserves every recorded fitting and support, including empty planned records', record => {
    const original = buildProject(record);
    const before = structuredClone(original);
    freezeDeep(original);
    const migrated = migrateProject(original);
    const sheetId = original.activeSheetId;
    expect(migrated.sheets[sheetId]).toBe(original.sheets[sheetId]);
    expect(migrated.sheets[sheetId].entities.fitting).toEqual(before.sheets[sheetId].entities.fitting);
    expect(migrated.sheets[sheetId].entities.support).toEqual(before.sheets[sheetId].entities.support);
    expect(migrated.sheets[sheetId].entityOrder).toContain('fitting');
    expect(original).toEqual(before);
    expect(installationActivities(migrated)).toEqual(installationActivities(before));
  });

  it('keeps fitting completion, notes and recorded support geometry through file export and repeated reloads', () => {
    const original = buildProject();
    const sheetId = original.activeSheetId;
    let restored = migrateProject(original);
    for (let reload = 0; reload < 3; reload++) restored = importProjectJSON(exportProjectJSON(restored));
    expect(restored.sheets[sheetId].entities.fitting).toEqual(original.sheets[sheetId].entities.fitting);
    expect(restored.sheets[sheetId].entities.support).toEqual(original.sheets[sheetId].entities.support);
    expect(restored.sheets[sheetId].entities.fitting.installation).toEqual(completed);
    expect(installationActivities(restored)).toEqual(installationActivities(original));
    expect(restored.sheets[sheetId].entityOrder).toEqual(original.sheets[sheetId].entityOrder);
  });

  it('preserves recorded fittings and support dimensions on the actual autosave restore path', () => {
    const entries = new Map<string, string>();
    vi.stubGlobal('localStorage', {
      getItem: (key: string) => entries.get(key) ?? null,
      setItem: (key: string, value: string) => entries.set(key, value),
      removeItem: (key: string) => entries.delete(key),
    });
    const original = buildProject();
    expect(saveStoredProject(migrateProject(original)).ok).toBe(true);
    const restored = loadStoredProject()!;
    expect(restored.sheets[restored.activeSheetId].entities).toEqual(original.sheets[original.activeSheetId].entities);
    expect(installationActivities(restored)).toEqual(installationActivities(original));
    expect(saveStoredProject(restored).ok).toBe(true);
    expect(loadStoredProject()!.sheets[restored.activeSheetId].entityOrder).toHaveLength(3);
  });

  it('still migrates unrecorded legacy parts without mutating frozen caller sheets or entities', () => {
    const original = buildProject();
    const originalSheet = original.sheets[original.activeSheetId];
    delete originalSheet.entities.fitting.installation;
    delete originalSheet.entities.support.installation;
    const before = structuredClone(original);
    freezeDeep(original);
    const migrated = migrateProject(original);
    const nextSheet = migrated.sheets[migrated.activeSheetId];
    expect(nextSheet.entities.fitting).toBeUndefined();
    expect(nextSheet.entityOrder).toEqual(['route', 'support']);
    expect(nextSheet.entities.support).toMatchObject({
      supportKind: 'trapeze-hanger', channelLength: 660, rodLength: 725,
      position: { x: 800, y: 0 }, elevation: 2700,
    });
    expect(original).toEqual(before);
    expect(originalSheet.entities.fitting).toBeDefined();
    expect(originalSheet.entities.support).toMatchObject({ supportKind: 'wall-bracket', channelLength: 450 });
    expect(migrated.sheets.untouched).toBe(original.sheets.untouched);
    expect(nextSheet.entities.route).toBe(originalSheet.entities.route);
  });

  it('handles a mixed sheet without losing recorded parts while removing only unrecorded legacy blockers', () => {
    const original = buildProject();
    const oldSheet = original.sheets[original.activeSheetId];
    const fitting = oldSheet.entities.fitting as FittingEntity;
    oldSheet.entities.legacy = { ...fitting, id: 'legacy', installation: undefined };
    oldSheet.entityOrder.push('legacy');
    const support = oldSheet.entities.support as SupportEntity;
    oldSheet.entities.legacySupport = { ...support, id: 'legacySupport', installation: undefined };
    oldSheet.entityOrder.push('legacySupport');
    freezeDeep(original);
    const migrated = migrateProject(original);
    const entities = migrated.sheets[migrated.activeSheetId].entities;
    expect(entities.legacy).toBeUndefined();
    expect(entities.fitting).toBe(oldSheet.entities.fitting);
    expect(entities.support).toBe(oldSheet.entities.support);
    expect(entities.legacySupport).toMatchObject({ supportKind: 'trapeze-hanger', channelLength: 660 });
    expect(oldSheet.entityOrder).toContain('legacy');
    expect(oldSheet.entities.legacySupport).toMatchObject({ supportKind: 'wall-bracket', channelLength: 450 });
  });
});
