import { create } from 'zustand';
import type { Entity, Project, RoutePoint } from '../types';
import { componentFromEntity, createComponentEntity, type InsertableComponent } from '../lib/component-library';
import { polylineLength } from '../lib/fittings';
import {
  alignRoutePoint, hasSpatialWorkspace, isPhysicalEntity, physicalElevation, resizeRoute,
  snapPhysicalConnection, transformPhysicalEntity, type ConnectionSnap, type PhysicalEntity,
} from '../lib/scene-edit';
import { shouldRejectLocalProjectMutation } from './collaboration-guard';
import { commitPhysicalEntity, physicalEditProblem, routePointEdit } from './scene-actions';
import { useStore } from './store';
import { dismissNotification, notify } from './notifications';
import { distance3, equipmentPorts, routePath, withRoutePath, type Point3 } from '../lib/route-path';
import { discoverRouteConnections } from '../lib/route-connections';

export type PlacementOperation = 'insert' | 'move' | 'duplicate' | 'endpoint' | 'extend' | 'route';
export interface PlacementOptions {
  rotation: number;
  length?: number;
  elevation?: number;
  repeat: boolean;
  keepJoined?: boolean;
  legAngle?: number;
}
export interface ComponentPlacement extends PlacementOptions {
  component: InsertableComponent;
  prototype: Entity;
  project: Project;
  sheetId: string;
  layerId: string;
  viewMode: '2d' | 'split' | '3d';
  surface: '2d' | '3d';
  hint: string;
  operation: PlacementOperation;
  source?: PhysicalEntity;
  endpointIndex?: number;
  drag?: { pointerId: number; clientX: number; clientY: number };
  routePoints?: Point3[];
  routeSteps?: number[];
  reverseRoute?: boolean;
}
type StartOptions = Partial<PlacementOptions> & Pick<Partial<ComponentPlacement>, 'operation' | 'source' | 'endpointIndex' | 'drag'>;

export const useComponentPlacement = create<{
  pending: ComponentPlacement | null;
  position: RoutePoint | null;
  connection: ConnectionSnap | null;
}>(() => ({ pending: null, position: null, connection: null }));

const placementProblem = (project: Project, layerId: string): string | null => {
  if (shouldRejectLocalProjectMutation()) return 'This collaboration session is read-only.';
  if (!project.sheets[project.activeSheetId]) return 'Open a drawing before adding a component.';
  const layer = project.layers[layerId];
  if (!layer) return 'Choose a layer before adding a component.';
  if (layer.locked) return 'Unlock the active layer before adding a component.';
  if (!layer.visible) return 'Show the active layer before adding a component.';
  return null;
};
const reportPlacementProblem = (message: string): void => {
  useStore.getState().setStatus(message);
  notify('warning', message, { id: 'component-placement', timeoutMs: 6000 });
};
export function cancelComponentPlacement(message = ''): void {
  if (!useComponentPlacement.getState().pending) return;
  useComponentPlacement.setState({ pending: null, position: null, connection: null });
  if (message) reportPlacementProblem(message);
  else useStore.getState().setStatus('');
}

/** Previews stay outside project/history. Identity is allocated once per insertion. */
export function beginComponentPlacement(component: InsertableComponent, options: StartOptions = {}): boolean {
  cancelComponentPlacement();
  const state = useStore.getState();
  const problem = options.source ? physicalEditProblem(options.source, state.project)
    : placementProblem(state.project, state.project.activeLayerId);
  if (problem) { reportPlacementProblem(problem); return false; }
  let prototype: Entity;
  const operation = options.operation ?? 'insert';
  try {
    // Editing belongs to the selected part's layer, even when the current
    // drawing layer is different. Only new identities need the factory.
    prototype = options.source && operation !== 'duplicate' ? options.source
      : createComponentEntity(component, { x: 0, y: 0 }, options.source
        ? { ...state.project, activeLayerId: options.source.layerId } : state.project);
    if (options.source) {
      const source = options.source;
      if (operation !== 'duplicate') prototype = source;
      else {
        const fresh = prototype;
        prototype = { ...source, id: fresh.id, installation: undefined };
        if (prototype.kind === 'containment') prototype = { ...prototype, assignedCableIds: undefined, connections: undefined, connectionsLocked: false };
        if (prototype.kind === 'equipment' && fresh.kind === 'equipment') prototype = { ...prototype, tag: fresh.tag };
        if (prototype.kind === 'support') prototype = { ...prototype, autoGenerated: false, supportingContainmentIds: [] };
      }
    }
  } catch (error) {
    reportPlacementProblem(error instanceof Error ? error.message : 'This component cannot be added to the current drawing.');
    return false;
  }
  const sheet = state.project.sheets[state.project.activeSheetId];
  const hiddenUnderground = sheet.sceneStyle !== 'containment' && prototype.kind === 'containment' && prototype.subType === 'underground-duct';
  const canPlaceIn3D = state.editor.viewMode === '3d' && hasSpatialWorkspace(state.project) && isPhysicalEntity(prototype) && !hiddenUnderground;
  const surface = canPlaceIn3D ? '3d' : '2d';
  const selected = state.project.sheets[state.project.activeSheetId]?.entities[[...state.editor.selection][0]];
  const elevation = options.elevation ?? (prototype.kind === 'support' && selected?.kind === 'containment'
    ? physicalElevation(selected, state.project) : isPhysicalEntity(prototype) ? physicalElevation(prototype, state.project) : undefined);
  dismissNotification('component-placement');
  state.setTool('select');
  state.setPendingSymbol(null);
  state.clearSelection();
  if (surface === '2d' && state.editor.viewMode !== '2d') state.setViewMode('2d');
  const current = useStore.getState();
  const verb = operation === 'move' ? 'Move' : operation === 'endpoint' ? 'Reshape' : operation === 'extend' ? 'Extend' : 'Place';
  const hint = verb + ' ' + component.title + (surface === '2d' ? ' in 2D' : '') + ' · '
    + (options.drag ? 'Drag to adjust' : 'Click to place') + ' · Esc to cancel';
  useComponentPlacement.setState({
    pending: {
      component, prototype, operation, source: options.source, endpointIndex: options.endpointIndex, drag: options.drag,
      project: current.project, sheetId: current.project.activeSheetId, layerId: current.project.activeLayerId,
      viewMode: current.editor.viewMode, surface, hint, rotation: options.rotation ?? 0,
      length: options.length ?? (prototype.kind === 'containment' && operation !== 'route' ? polylineLength(prototype.points) : undefined),
      elevation, repeat: options.repeat ?? false, keepJoined: options.keepJoined ?? true,
      ...(operation === 'route' ? { routePoints: [], routeSteps: [] } : {}),
    }, position: null, connection: null,
  });
  current.setStatus(hint);
  return true;
}

export function beginEntityPlacement(id: string, operation: Exclude<PlacementOperation, 'insert'>, endpointIndex?: number, drag?: ComponentPlacement['drag']): boolean {
  const state = useStore.getState();
  const source = state.project.sheets[state.project.activeSheetId]?.entities[id];
  if (!isPhysicalEntity(source) || state.editor.viewMode !== '3d') return false;
  const elevation = source.kind === 'containment' && (operation === 'endpoint' || operation === 'extend')
    ? routePath(source, state.project.floors?.[state.project.sheets[state.project.activeSheetId].floorId ?? ''])[endpointIndex ?? 0]?.z : undefined;
  return beginComponentPlacement(componentFromEntity(source), { operation, source, endpointIndex, drag, elevation });
}

export function beginRouteDrawing(component: InsertableComponent, sourceId?: string, fromStart = false): boolean {
  const state = useStore.getState();
  const source = sourceId ? state.project.sheets[state.project.activeSheetId]?.entities[sourceId] : undefined;
  if (source && source.kind !== 'containment') return false;
  if (source?.connectionsLocked && source.connections?.some(connection => connection.end === (fromStart ? 'start' : 'end'))) {
    reportPlacementProblem('Release this end’s connection before extending it.'); return false;
  }
  const points = source?.kind === 'containment' ? routePath(source, state.project.floors?.[state.project.sheets[state.project.activeSheetId].floorId ?? '']) : [];
  if (fromStart) points.reverse();
  if (!beginComponentPlacement(component, { operation: 'route', source, elevation: points.at(-1)?.z })) return false;
  const pending = useComponentPlacement.getState().pending!;
  if (pending.surface !== '3d' || pending.prototype.kind !== 'containment') { cancelComponentPlacement(); return false; }
  useComponentPlacement.setState({ pending: { ...pending, routePoints: points, routeSteps: [], reverseRoute: fromStart, hint: 'Click points to draw · Enter to finish · Esc to cancel' } });
  return true;
}

function routePreviewPoints(pending: ComponentPlacement, position: RoutePoint): Point3[] {
  const points = pending.routePoints ?? [];
  const end = { ...position, z: position.z ?? pending.elevation ?? 0 };
  const last = points.at(-1);
  if (!last) return [end];
  const extension: Point3[] = [];
  if (Math.abs(last.z - end.z) > 0.01) {
    const boardPort = Object.values(pending.project.sheets[pending.sheetId].entities).some(e =>
      e.kind === 'equipment' && equipmentPorts(e).some(port => distance3(port.position, end) < 1));
    const corner = boardPort ? { x: end.x, y: end.y, z: last.z } : { x: last.x, y: last.y, z: end.z };
    if (distance3(last, corner) >= 1) extension.push(corner);
  }
  if (distance3(extension.at(-1) ?? last, end) >= 1) extension.push(end);
  return [...points, ...extension];
}

export function addRouteDrawingPoint(position: RoutePoint): boolean {
  const { pending } = useComponentPlacement.getState();
  if (pending?.operation !== 'route') return false;
  const points = routePreviewPoints(pending, position);
  if (points.length === pending.routePoints?.length || points.some(p => ![p.x, p.y, p.z].every(Number.isFinite))) return false;
  useComponentPlacement.setState({ pending: { ...pending, routePoints: points,
    routeSteps: [...(pending.routeSteps ?? []), pending.routePoints?.length ?? 0], elevation: points.at(-1)?.z ?? pending.elevation, length: undefined, legAngle: undefined }, connection: null });
  return true;
}

export function undoRouteDrawingPoint(): void {
  const { pending } = useComponentPlacement.getState();
  if (pending?.operation !== 'route' || !pending.routeSteps?.length) return;
  const points = pending.routePoints!.slice(0, pending.routeSteps.at(-1));
  useComponentPlacement.setState({ pending: { ...pending, routePoints: points, routeSteps: pending.routeSteps.slice(0, -1),
    elevation: points.at(-1)?.z ?? pending.elevation }, connection: null });
}

export function finishRouteDrawing(): Entity | null {
  const { pending } = useComponentPlacement.getState();
  if (pending?.operation !== 'route' || pending.prototype.kind !== 'containment' || !pending.routePoints || pending.routePoints.length < 2
    || useStore.getState().project !== pending.project) return null;
  const path = pending.reverseRoute ? [...pending.routePoints].reverse() : pending.routePoints;
  let entity = withRoutePath(pending.prototype, path);
  entity = { ...entity, connectionsLocked: !!pending.keepJoined, connections: discoverRouteConnections(entity, pending.project, 1) };
  const inserted = commitPhysicalEntity(entity, pending.project, !pending.source);
  if (!inserted) return null;
  cancelComponentPlacement();
  useStore.getState().setSelection([inserted.id]);
  useStore.getState().setStatus('Route finished · ' + (polylineLength(path) / 1000).toFixed(2) + ' m');
  return inserted;
}

export function updatePlacementOptions(options: Partial<PlacementOptions>): boolean {
  const pending = useComponentPlacement.getState().pending;
  if (!pending) return false;
  if ((options.length != null && (!Number.isFinite(options.length) || options.length < 10 || options.length > 1_000_000))
    || (options.rotation != null && !Number.isFinite(options.rotation)) || (options.legAngle != null && !Number.isFinite(options.legAngle))
    || (options.elevation != null && (!Number.isFinite(options.elevation) || Math.abs(options.elevation) > 100_000))) {
    reportPlacementProblem('Enter a valid length, elevation or angle.'); return false;
  }
  useComponentPlacement.setState({ pending: { ...pending, ...options }, connection: null });
  return true;
}

export function setComponentPlacementPosition(position: RoutePoint | null, connection: ConnectionSnap | null = null): void {
  if (!useComponentPlacement.getState().pending) return;
  if (position && (!Number.isFinite(position.x) || !Number.isFinite(position.y))) return;
  useComponentPlacement.setState({ position, connection });
}

function placementEntity(pending: ComponentPlacement, position: RoutePoint): Entity {
  let entity = pending.prototype;
  if (isPhysicalEntity(entity)) {
    if (pending.operation === 'route' && entity.kind === 'containment') return withRoutePath(entity, routePreviewPoints(pending, position));
    if ((pending.operation === 'endpoint' || pending.operation === 'extend') && pending.source) {
      return routePointEdit(pending.source, pending.endpointIndex ?? 0, { ...position, z: position.z ?? pending.elevation }, pending.operation === 'extend');
    }
    if (entity.kind === 'containment' && pending.length != null) entity = resizeRoute(entity, pending.length);
    entity = transformPhysicalEntity(entity, position, pending.rotation);
    const elevation = position.z ?? pending.elevation;
    if (entity.kind === 'containment' && entity.points.some(p => p.z != null) && elevation != null) {
      const delta = elevation - physicalElevation(entity, pending.project);
      return withRoutePath(entity, routePath(entity).map(p => ({ ...p, z: p.z + delta })));
    }
    return { ...entity, ...(elevation != null ? { elevation } : {}) };
  }
  return entity.kind === 'symbol' ? { ...entity, position: { ...position }, rotation: pending.rotation } : entity;
}

export function componentPlacementPreview(position: RoutePoint): Entity | null {
  const pending = useComponentPlacement.getState().pending;
  if (!pending) return null;
  try { return { ...placementEntity(pending, position), id: 'component-placement-preview' }; }
  catch (error) {
    cancelComponentPlacement(error instanceof Error ? error.message : 'This component cannot be added to the current drawing.'); return null;
  }
}

export function resolvePlacementPosition(position: RoutePoint, tolerance: number, forceOrtho = false): { position: RoutePoint; connection: ConnectionSnap | null } {
  const pending = useComponentPlacement.getState().pending;
  const snap = useStore.getState().editor.snap;
  if (!pending) return { position, connection: null };
  const pointOnly = pending.operation === 'endpoint' || pending.operation === 'extend' || pending.operation === 'route';
  let point: RoutePoint = { ...position, ...(pending.surface === '3d' ? { z: position.z ?? pending.elevation ?? 0 } : {}) };
  if (pending.operation === 'route' && pending.routePoints?.length) {
    const last = pending.routePoints.at(-1)!;
    const aligned = alignRoutePoint(point, last, forceOrtho);
    const angle = pending.legAngle ?? Math.atan2(aligned.y - last.y, aligned.x - last.x);
    const length = pending.length ?? Math.hypot(aligned.x - last.x, aligned.y - last.y);
    point = { ...point, x: last.x + Math.cos(angle) * length, y: last.y + Math.sin(angle) * length };
  }
  if ((pending.operation === 'endpoint' || pending.operation === 'extend') && pending.source?.kind === 'containment') {
    const source = pending.source;
    const index = pending.endpointIndex ?? 0;
    const anchor = pending.operation === 'extend' ? source.points[index]
      : source.points[index === 0 ? 1 : index - 1];
    if (anchor) point = { ...point, ...alignRoutePoint(point, anchor, forceOrtho) };
  }
  if (snap.enabled && snap.grid && snap.gridSize > 0 && pending.length == null) point = { ...point, x: Math.round(point.x / snap.gridSize) * snap.gridSize, y: Math.round(point.y / snap.gridSize) * snap.gridSize };
  const preview = placementEntity(pending, point);
  const connection = snap.enabled && snap.osnap && snap.endpoint && isPhysicalEntity(preview)
    && (pending.operation !== 'route' || pending.length == null)
    ? snapPhysicalConnection(preview, point, pending.project, tolerance, { pointOnly, excludeId: pending.source?.id,
      sourceEnd: pending.endpointIndex === 0 ? 'start' : 'end' }) : null;
  return { position: connection?.position ?? point, connection };
}

export function commitComponentPlacement(position: RoutePoint): Entity | null {
  const { pending, connection } = useComponentPlacement.getState();
  if (!pending || !Number.isFinite(position.x) || !Number.isFinite(position.y)) return null;
  const state = useStore.getState();
  if (state.project !== pending.project || state.project.activeSheetId !== pending.sheetId || state.editor.viewMode !== pending.viewMode) {
    cancelComponentPlacement(); return null;
  }
  if (pending.operation === 'route') { addRouteDrawingPoint(position); return null; }
  let entity: Entity;
  try { entity = placementEntity(pending, position); }
  catch (error) { cancelComponentPlacement(error instanceof Error ? error.message : 'This component cannot be added.'); return null; }
  const problem = placementProblem(state.project, entity.layerId);
  if (problem) { cancelComponentPlacement(problem); return null; }
  if (entity.kind === 'support') entity = { ...entity, supportingContainmentIds: connection ? [connection.entityId] : [] };
  if (entity.kind === 'containment' && connection && pending.keepJoined) entity = { ...entity, connectionsLocked: true,
    connections: [...(entity.connections ?? []).filter(link => link.end !== connection.sourceEnd),
      { end: connection.sourceEnd, targetId: connection.entityId, target: connection.attachment }] };
  useComponentPlacement.setState({ pending: null, position: null, connection: null });
  let inserted: Entity | null | undefined;
  if (isPhysicalEntity(entity)) inserted = commitPhysicalEntity(entity, pending.project, pending.operation === 'insert' || pending.operation === 'duplicate');
  else { state.addEntity(entity); inserted = useStore.getState().project.sheets[pending.sheetId]?.entities[entity.id]; }
  if (!inserted) return null;
  if (pending.repeat && (pending.operation === 'insert' || pending.operation === 'duplicate')) {
    const { source, operation, rotation, length, elevation, repeat } = pending;
    beginComponentPlacement(pending.component, { source, operation, rotation, length, elevation, repeat });
  }
  state.setSelection([inserted.id]);
  state.setStatus((pending.operation === 'insert' || pending.operation === 'duplicate' ? 'Added ' : 'Updated ') + pending.component.title);
  return inserted;
}

const stopWatching = useStore.subscribe((state) => {
  const pending = useComponentPlacement.getState().pending;
  if (pending && (state.project !== pending.project || state.project.activeLayerId !== pending.layerId
    || state.editor.viewMode !== pending.viewMode || state.editor.tool !== 'select')) cancelComponentPlacement();
});
const onKeyDown = (event: KeyboardEvent): void => {
  const pending = useComponentPlacement.getState().pending;
  if (!pending) return;
  const target = event.target as HTMLElement | null;
  if (target?.matches('input, textarea, select, [contenteditable="true"]')) return;
  if (event.key === 'Escape') { event.preventDefault(); cancelComponentPlacement(); }
  if (pending.operation === 'route' && event.key === 'Enter') { event.preventDefault(); event.stopImmediatePropagation(); finishRouteDrawing(); }
  if (pending.operation === 'route' && event.key === 'Backspace') { event.preventDefault(); event.stopImmediatePropagation(); undoRouteDrawingPoint(); }
  if (event.key.toLowerCase() === 'r' && !event.metaKey && !event.ctrlKey && !event.altKey
    && pending.surface === '3d' && pending.operation !== 'endpoint' && pending.operation !== 'extend') {
    event.preventDefault(); event.stopImmediatePropagation();
    if (pending.operation === 'route') updatePlacementOptions({ legAngle: (pending.legAngle ?? 0) + (event.shiftKey ? -1 : 1) * Math.PI / 2 });
    else updatePlacementOptions({ rotation: pending.rotation + (event.shiftKey ? -1 : 1) * Math.PI / 2 });
  }
};
if (typeof window !== 'undefined') window.addEventListener('keydown', onKeyDown, true);
if (import.meta.hot) import.meta.hot.dispose(() => {
  stopWatching();
  if (typeof window !== 'undefined') window.removeEventListener('keydown', onKeyDown, true);
});
