import { create } from 'zustand';
import type { Entity, Project, Vec2 } from '../types';
import { componentFromEntity, createComponentEntity, type InsertableComponent } from '../lib/component-library';
import { polylineLength } from '../lib/fittings';
import {
  alignRoutePoint, hasSpatialWorkspace, isPhysicalEntity, physicalElevation, resizeRoute,
  snapPhysicalConnection, transformPhysicalEntity, type ConnectionSnap, type PhysicalEntity,
} from '../lib/scene-edit';
import { shouldRejectLocalProjectMutation } from './collaboration-guard';
import { commitPhysicalEntity, physicalEditProblem, routePointEdit } from './scene-actions';
import { useStore } from './store';
import { dismissNotification, notify } from './notifications';

export type PlacementOperation = 'insert' | 'move' | 'duplicate' | 'endpoint' | 'extend';
export interface PlacementOptions {
  rotation: number;
  length?: number;
  elevation?: number;
  repeat: boolean;
}
export interface ComponentPlacement extends PlacementOptions {
  component: InsertableComponent;
  prototype: Entity;
  project: Project;
  sheetId: string;
  layerId: string;
  viewMode: '2d' | 'split' | '3d';
  surface: '2d' | '3d';
  hint: string;
  operation: PlacementOperation;
  source?: PhysicalEntity;
  endpointIndex?: number;
  drag?: { pointerId: number; clientX: number; clientY: number };
}
type StartOptions = Partial<PlacementOptions> & Pick<Partial<ComponentPlacement>, 'operation' | 'source' | 'endpointIndex' | 'drag'>;

export const useComponentPlacement = create<{
  pending: ComponentPlacement | null;
  position: Vec2 | null;
  connection: ConnectionSnap | null;
}>(() => ({ pending: null, position: null, connection: null }));

const placementProblem = (project: Project, layerId: string): string | null => {
  if (shouldRejectLocalProjectMutation()) return 'This collaboration session is read-only.';
  if (!project.sheets[project.activeSheetId]) return 'Open a drawing before adding a component.';
  const layer = project.layers[layerId];
  if (!layer) return 'Choose a layer before adding a component.';
  if (layer.locked) return 'Unlock the active layer before adding a component.';
  if (!layer.visible) return 'Show the active layer before adding a component.';
  return null;
};
const reportPlacementProblem = (message: string): void => {
  useStore.getState().setStatus(message);
  notify('warning', message, { id: 'component-placement', timeoutMs: 6000 });
};
export function cancelComponentPlacement(message = ''): void {
  if (!useComponentPlacement.getState().pending) return;
  useComponentPlacement.setState({ pending: null, position: null, connection: null });
  if (message) reportPlacementProblem(message);
  else useStore.getState().setStatus('');
}

/** Previews stay outside project/history. Identity is allocated once per insertion. */
export function beginComponentPlacement(component: InsertableComponent, options: StartOptions = {}): boolean {
  cancelComponentPlacement();
  const state = useStore.getState();
  const problem = options.source ? physicalEditProblem(options.source, state.project)
    : placementProblem(state.project, state.project.activeLayerId);
  if (problem) { reportPlacementProblem(problem); return false; }
  let prototype: Entity;
  const operation = options.operation ?? 'insert';
  try {
    // Editing belongs to the selected part's layer, even when the current
    // drawing layer is different. Only new identities need the factory.
    prototype = options.source && operation !== 'duplicate' ? options.source
      : createComponentEntity(component, { x: 0, y: 0 }, options.source
        ? { ...state.project, activeLayerId: options.source.layerId } : state.project);
    if (options.source) {
      const source = options.source;
      if (operation !== 'duplicate') prototype = source;
      else {
        const fresh = prototype;
        prototype = { ...source, id: fresh.id, installation: undefined };
        if (prototype.kind === 'containment') prototype = { ...prototype, assignedCableIds: undefined };
        if (prototype.kind === 'equipment' && fresh.kind === 'equipment') prototype = { ...prototype, tag: fresh.tag };
        if (prototype.kind === 'support') prototype = { ...prototype, autoGenerated: false, supportingContainmentIds: [] };
      }
    }
  } catch (error) {
    reportPlacementProblem(error instanceof Error ? error.message : 'This component cannot be added to the current drawing.');
    return false;
  }
  const sheet = state.project.sheets[state.project.activeSheetId];
  const hiddenUnderground = sheet.sceneStyle !== 'containment' && prototype.kind === 'containment' && prototype.subType === 'underground-duct';
  const canPlaceIn3D = state.editor.viewMode === '3d' && hasSpatialWorkspace(state.project) && isPhysicalEntity(prototype) && !hiddenUnderground;
  const surface = canPlaceIn3D ? '3d' : '2d';
  const selected = state.project.sheets[state.project.activeSheetId]?.entities[[...state.editor.selection][0]];
  const elevation = options.elevation ?? (prototype.kind === 'support' && selected?.kind === 'containment'
    ? physicalElevation(selected, state.project) : isPhysicalEntity(prototype) ? physicalElevation(prototype, state.project) : undefined);
  dismissNotification('component-placement');
  state.setTool('select');
  state.setPendingSymbol(null);
  state.clearSelection();
  if (surface === '2d' && state.editor.viewMode !== '2d') state.setViewMode('2d');
  const current = useStore.getState();
  const verb = operation === 'move' ? 'Move' : operation === 'endpoint' ? 'Reshape' : operation === 'extend' ? 'Extend' : 'Place';
  const hint = verb + ' ' + component.title + (surface === '2d' ? ' in 2D' : '') + ' · '
    + (options.drag ? 'Drag to adjust' : 'Click to place') + ' · Esc to cancel';
  useComponentPlacement.setState({
    pending: {
      component, prototype, operation, source: options.source, endpointIndex: options.endpointIndex, drag: options.drag,
      project: current.project, sheetId: current.project.activeSheetId, layerId: current.project.activeLayerId,
      viewMode: current.editor.viewMode, surface, hint, rotation: options.rotation ?? 0,
      length: options.length ?? (prototype.kind === 'containment' ? polylineLength(prototype.points) : undefined),
      elevation, repeat: options.repeat ?? false,
    }, position: null, connection: null,
  });
  current.setStatus(hint);
  return true;
}

export function beginEntityPlacement(id: string, operation: Exclude<PlacementOperation, 'insert'>, endpointIndex?: number, drag?: ComponentPlacement['drag']): boolean {
  const state = useStore.getState();
  const source = state.project.sheets[state.project.activeSheetId]?.entities[id];
  if (!isPhysicalEntity(source) || state.editor.viewMode !== '3d') return false;
  return beginComponentPlacement(componentFromEntity(source), { operation, source, endpointIndex, drag });
}

export function updatePlacementOptions(options: Partial<PlacementOptions>): boolean {
  const pending = useComponentPlacement.getState().pending;
  if (!pending) return false;
  if ((options.length != null && (!Number.isFinite(options.length) || options.length < 10 || options.length > 1_000_000))
    || (options.rotation != null && !Number.isFinite(options.rotation))
    || (options.elevation != null && (!Number.isFinite(options.elevation) || Math.abs(options.elevation) > 100_000))) {
    reportPlacementProblem('Enter a valid length, elevation or angle.'); return false;
  }
  useComponentPlacement.setState({ pending: { ...pending, ...options }, connection: null });
  return true;
}

export function setComponentPlacementPosition(position: Vec2 | null, connection: ConnectionSnap | null = null): void {
  if (!useComponentPlacement.getState().pending) return;
  if (position && (!Number.isFinite(position.x) || !Number.isFinite(position.y))) return;
  useComponentPlacement.setState({ position, connection });
}

function placementEntity(pending: ComponentPlacement, position: Vec2): Entity {
  let entity = pending.prototype;
  if (isPhysicalEntity(entity)) {
    if ((pending.operation === 'endpoint' || pending.operation === 'extend') && pending.source) {
      return routePointEdit(pending.source, pending.endpointIndex ?? 0, position, pending.operation === 'extend');
    }
    if (entity.kind === 'containment' && pending.length != null) entity = resizeRoute(entity, pending.length);
    entity = transformPhysicalEntity(entity, position, pending.rotation);
    return { ...entity, ...(pending.elevation != null ? { elevation: pending.elevation } : {}) };
  }
  return entity.kind === 'symbol' ? { ...entity, position: { ...position }, rotation: pending.rotation } : entity;
}

export function componentPlacementPreview(position: Vec2): Entity | null {
  const pending = useComponentPlacement.getState().pending;
  if (!pending) return null;
  try { return { ...placementEntity(pending, position), id: 'component-placement-preview' }; }
  catch (error) {
    cancelComponentPlacement(error instanceof Error ? error.message : 'This component cannot be added to the current drawing.'); return null;
  }
}

export function resolvePlacementPosition(position: Vec2, tolerance: number, forceOrtho = false): { position: Vec2; connection: ConnectionSnap | null } {
  const pending = useComponentPlacement.getState().pending;
  const snap = useStore.getState().editor.snap;
  if (!pending) return { position, connection: null };
  const pointOnly = pending.operation === 'endpoint' || pending.operation === 'extend';
  let point = position;
  if (pointOnly && pending.source?.kind === 'containment') {
    const source = pending.source;
    const index = pending.endpointIndex ?? 0;
    const anchor = pending.operation === 'extend' ? source.points[index]
      : source.points[index === 0 ? 1 : index - 1];
    if (anchor) point = alignRoutePoint(point, anchor, forceOrtho);
  }
  if (snap.enabled && snap.grid && snap.gridSize > 0) point = { x: Math.round(point.x / snap.gridSize) * snap.gridSize, y: Math.round(point.y / snap.gridSize) * snap.gridSize };
  const preview = placementEntity(pending, point);
  const connection = snap.enabled && snap.osnap && snap.endpoint && isPhysicalEntity(preview)
    ? snapPhysicalConnection(preview, point, pending.project, tolerance, { pointOnly, excludeId: pending.source?.id }) : null;
  return { position: connection?.position ?? point, connection };
}

export function commitComponentPlacement(position: Vec2): Entity | null {
  const { pending, connection } = useComponentPlacement.getState();
  if (!pending || !Number.isFinite(position.x) || !Number.isFinite(position.y)) return null;
  const state = useStore.getState();
  if (state.project !== pending.project || state.project.activeSheetId !== pending.sheetId || state.editor.viewMode !== pending.viewMode) {
    cancelComponentPlacement(); return null;
  }
  let entity: Entity;
  try { entity = placementEntity(pending, position); }
  catch (error) { cancelComponentPlacement(error instanceof Error ? error.message : 'This component cannot be added.'); return null; }
  const problem = placementProblem(state.project, entity.layerId);
  if (problem) { cancelComponentPlacement(problem); return null; }
  if (entity.kind === 'support') entity = { ...entity, supportingContainmentIds: connection ? [connection.entityId] : [] };
  useComponentPlacement.setState({ pending: null, position: null, connection: null });
  let inserted: Entity | null | undefined;
  if (isPhysicalEntity(entity)) inserted = commitPhysicalEntity(entity, pending.project, pending.operation === 'insert' || pending.operation === 'duplicate');
  else { state.addEntity(entity); inserted = useStore.getState().project.sheets[pending.sheetId]?.entities[entity.id]; }
  if (!inserted) return null;
  if (pending.repeat && (pending.operation === 'insert' || pending.operation === 'duplicate')) {
    const { source, operation, rotation, length, elevation, repeat } = pending;
    beginComponentPlacement(pending.component, { source, operation, rotation, length, elevation, repeat });
  }
  state.setSelection([inserted.id]);
  state.setStatus((pending.operation === 'insert' || pending.operation === 'duplicate' ? 'Added ' : 'Updated ') + pending.component.title);
  return inserted;
}

const stopWatching = useStore.subscribe((state) => {
  const pending = useComponentPlacement.getState().pending;
  if (pending && (state.project !== pending.project || state.project.activeLayerId !== pending.layerId
    || state.editor.viewMode !== pending.viewMode || state.editor.tool !== 'select')) cancelComponentPlacement();
});
const onKeyDown = (event: KeyboardEvent): void => {
  const pending = useComponentPlacement.getState().pending;
  if (!pending) return;
  const target = event.target as HTMLElement | null;
  if (target?.matches('input, textarea, select, [contenteditable="true"]')) return;
  if (event.key === 'Escape') { event.preventDefault(); cancelComponentPlacement(); }
  if (event.key.toLowerCase() === 'r' && !event.metaKey && !event.ctrlKey && !event.altKey
    && pending.surface === '3d' && pending.operation !== 'endpoint' && pending.operation !== 'extend') {
    event.preventDefault(); event.stopImmediatePropagation();
    updatePlacementOptions({ rotation: pending.rotation + (event.shiftKey ? -1 : 1) * Math.PI / 2 });
  }
};
if (typeof window !== 'undefined') window.addEventListener('keydown', onKeyDown, true);
if (import.meta.hot) import.meta.hot.dispose(() => {
  stopWatching();
  if (typeof window !== 'undefined') window.removeEventListener('keydown', onKeyDown, true);
});
