import type { Project, Vec2 } from '../types';
import { projectWithAutoFeatures } from '../lib/auto-feature-actions';
import { containmentTouchesPoint } from '../lib/fittings';
import {
  isPhysicalEntity, physicalAnchor, physicalElevation, physicalHeading, resizeRoute, transformPhysicalEntity, type PhysicalEntity,
} from '../lib/scene-edit';
import { shouldRejectLocalProjectMutation } from './collaboration-guard';
import { notify } from './notifications';
import { useStore } from './store';

export function physicalEditProblem(entity: PhysicalEntity, project: Project): string | null {
  if (shouldRejectLocalProjectMutation()) return 'This collaboration session is read-only.';
  const layer = project.layers[entity.layerId];
  if (entity.locked || layer?.locked) return 'Unlock this part and its layer before editing.';
  if (entity.visible === false || layer?.visible === false || !layer) return 'Show this part and its layer before editing.';
  return null;
}

export function reportSceneEditProblem(message: string): void {
  notify('warning', message, { id: 'scene-edit', timeoutMs: 5000 });
  useStore.getState().setStatus(message);
}

function connectedRoutes(entity: PhysicalEntity, project: Project): string[] {
  if (entity.kind !== 'containment' || entity.points.length < 2) return [];
  const ends = [entity.points[0], entity.points.at(-1)!];
  return Object.values(project.sheets[project.activeSheetId].entities).flatMap(other => {
    if (other.kind !== 'containment' || other.id === entity.id || other.points.length < 2
      || other.containmentType !== entity.containmentType
      || Math.abs(physicalElevation(other, project) - physicalElevation(entity, project)) > 1) return [];
    return ends.some(point => containmentTouchesPoint(other, point))
      || [other.points[0], other.points.at(-1)!].some(point => containmentTouchesPoint(entity, point)) ? [other.id] : [];
  });
}

/** Route, fittings and existing supports are committed together, never as intermediate states. */
export function commitPhysicalEntity(entity: PhysicalEntity, expectedProject: Project, add = false): PhysicalEntity | null {
  const state = useStore.getState();
  if (state.project !== expectedProject) return null;
  const sheet = expectedProject.sheets[expectedProject.activeSheetId];
  const previous = sheet?.entities[entity.id];
  if (!sheet || (!add && !isPhysicalEntity(previous))) return null;
  const problem = physicalEditProblem(add ? entity : previous as PhysicalEntity, expectedProject);
  if (problem) { reportSceneEditProblem(problem); return null; }
  if (entity.kind === 'containment' && (entity.points.length < 2 || entity.points.some((p, i, points) =>
    !Number.isFinite(p.x) || !Number.isFinite(p.y) || (i > 0 && Math.hypot(p.x - points[i - 1].x, p.y - points[i - 1].y) < 1)))) {
    reportSceneEditProblem('Keep at least 1 mm between route points.'); return null;
  }
  if (!add && JSON.stringify(previous) === JSON.stringify(entity)) return previous as PhysicalEntity;
  if (entity.kind === 'support' && !add) entity = { ...entity, autoGenerated: false };
  const updatedSheet = { ...sheet, entities: { ...sheet.entities, [entity.id]: entity },
    entityOrder: add ? [...sheet.entityOrder, entity.id] : sheet.entityOrder };
  let staged = { ...expectedProject, sheets: { ...expectedProject.sheets, [sheet.id]: updatedSheet } };
  let retainedParts = 0;
  try {
    if (entity.kind === 'containment') {
      // Junctions on either side of a changed route must refresh too. Locked
      // routes keep their recorded accessories and are never edited indirectly.
      const ids = [...new Set([entity.id, ...connectedRoutes(entity, staged),
        ...(isPhysicalEntity(previous) ? connectedRoutes(previous, expectedProject) : [])])]
        .filter(id => { const route = updatedSheet.entities[id]; return isPhysicalEntity(route) && !physicalEditProblem(route, staged); });
      const regeneration = projectWithAutoFeatures(staged, ids, { supports: 'existing' });
      staged = regeneration.project;
      retainedParts = regeneration.result.retainedCount;
    }
  } catch (error) {
    reportSceneEditProblem(error instanceof Error ? error.message : 'Could not update the route.'); return null;
  }
  state.setProjectPatch({ sheets: staged.sheets, penetrationSeals: staged.penetrationSeals });
  if (retainedParts) notify('warning', retainedParts + ' recorded part' + (retainedParts === 1 ? '' : 's')
    + ' retained as manual after this route edit. Review the installation records.', { id: 'scene-edit-history', timeoutMs: 7000 });
  return useStore.getState().project.sheets[sheet.id]?.entities[entity.id] as PhysicalEntity ?? null;
}

export type PhysicalProperty = 'width' | 'depth' | 'height' | 'length' | 'elevation' | 'rotation' | 'x' | 'y';
export function updatePhysicalProperty(id: string, property: PhysicalProperty, value: number): boolean {
  const { project } = useStore.getState();
  const entity = project.sheets[project.activeSheetId]?.entities[id];
  if (!isPhysicalEntity(entity)) return false;
  if (!Number.isFinite(value) || Math.abs(value) > 1_000_000
    || (['width', 'depth', 'height', 'length'].includes(property) && value <= 0)) {
    reportSceneEditProblem('Enter a valid dimension in millimetres.'); return false;
  }
  let updated: PhysicalEntity = entity;
  const anchor = physicalAnchor(entity);
  try {
    if (property === 'rotation') updated = transformPhysicalEntity(entity, anchor, value * Math.PI / 180 - physicalHeading(entity));
    else if (property === 'x' || property === 'y') {
      updated = transformPhysicalEntity(entity, { ...anchor, [property]: value });
      if (updated.kind === 'support') updated = { ...updated, supportingContainmentIds: [] };
    }
    else if (property === 'elevation') updated = { ...entity, elevation: value };
    else if (entity.kind === 'containment') {
      if (property === 'length') updated = resizeRoute(entity, value);
      else {
        const oldSize = `${entity.width} × ${entity.height}`;
        const dimensions = property === 'width' ? { width: value } : { height: value };
        const changed = { ...entity, ...dimensions };
        updated = { ...changed, innerCsaMm2: undefined, catalogProductId: undefined, catalogPartNumber: undefined, manufacturer: undefined,
          label: entity.label?.replace(oldSize, `${changed.width} × ${changed.height}`) };
      }
    } else if (entity.kind === 'equipment') {
      const width = property === 'width' ? value : Math.abs(entity.b.x - entity.a.x);
      const depth = property === 'depth' ? value : Math.abs(entity.b.y - entity.a.y);
      updated = { ...entity, a: { x: anchor.x - width / 2, y: anchor.y - depth / 2 }, b: { x: anchor.x + width / 2, y: anchor.y + depth / 2 },
        height: property === 'height' ? value : entity.height, catalogProductId: undefined, partNumber: undefined, manufacturer: undefined };
    } else updated = { ...entity, ...(property === 'length' ? { channelLength: value } : { rodLength: value }), autoGenerated: false, catalogProductId: undefined };
  } catch (error) {
    reportSceneEditProblem(error instanceof Error ? error.message : 'Could not change this dimension.'); return false;
  }
  return !!commitPhysicalEntity(updated, project);
}

export function rotatePhysicalEntity(id: string): void {
  const state = useStore.getState();
  const entity = state.project.sheets[state.project.activeSheetId]?.entities[id];
  if (isPhysicalEntity(entity)) updatePhysicalProperty(id, 'rotation', physicalHeading(entity) * 180 / Math.PI + 90);
}

/** Explicitly requested support layout; the stored profile remains the source of spacing. */
export function addRouteSupports(id: string): void {
  const state = useStore.getState();
  const entity = state.project.sheets[state.project.activeSheetId]?.entities[id];
  if (entity?.kind !== 'containment') return;
  const problem = physicalEditProblem(entity, state.project);
  if (problem) { reportSceneEditProblem(problem); return; }
  try {
    const staged = projectWithAutoFeatures(state.project, [id]).project;
    if (staged !== state.project) state.setProjectPatch({ sheets: staged.sheets, penetrationSeals: staged.penetrationSeals });
  } catch (error) { reportSceneEditProblem(error instanceof Error ? error.message : 'Could not lay out supports.'); }
}

export function routePointEdit(entity: PhysicalEntity, index: number, point: Vec2, extend: boolean): PhysicalEntity {
  if (entity.kind !== 'containment') return entity;
  const points = [...entity.points];
  if (extend) { if (index === 0) points.unshift(point); else points.push(point); }
  else points[index] = point;
  return { ...entity, points };
}
