import type { ContainmentEntity, FittingEntity, Project, SupportEntity } from '../types';
import { emptyCableSchedule } from '../models/cable';
import { DEFAULT_STANDARDS } from '../models/standards';
import { loadDefaultCatalogues } from '../data/catalogues';
import { pickSupportKind, trapezeChannelLength } from '../lib/support-placer';
import { containmentTouchesPoint } from '../lib/fittings';
import { dismissNotification, notify, useNotifications } from '../state/notifications';
import { markSaved, markSaveError, markSaving } from '../state/save-status';
import { projectStructureDefects, repairProjectStructure } from './project-validation';

// Bump this whenever the bundled sample project changes meaningfully —
// users with an autosave from a previous demo will skip it and load the
// new sample on next reload.
const STORAGE_KEY = 'opencad.project.v8';
// Last-good copy, written only when autosave refuses to overwrite the main
// key with a structurally broken project. Read as a fallback when the main
// key is missing or fails validation, so a bad state can never destroy the
// last good one.
const BACKUP_KEY = 'opencad.project.v8.bak';
// Older keys are read once for migration and then evicted, so users with
// a v5 (or earlier) save aren't dropped back to a fresh demo.
const LEGACY_KEYS = ['opencad.project.v7', 'opencad.project.v6', 'opencad.project.v5', 'opencad.project.v4'];

// Apply migrations to projects saved by older app versions. Whole-site
// fields are optional in the type, so the migration is mostly about
// filling in derived defaults so downstream code can stop guarding for
// `undefined` on long-lived fields like the cable schedule and standards
// profile.
export function migrateProject(parsed: Project): Project {
  const next: Project = { ...parsed };
  if (!next.cableSchedule) next.cableSchedule = emptyCableSchedule();
  if (!next.standardsProfile) next.standardsProfile = DEFAULT_STANDARDS.BS7671;
  // Catalogues are large but bundled with the app — we always rehydrate
  // them so the Catalogue Browser populates after a reload (saved
  // projects don't need to round-trip 366 products through localStorage).
  if (!next.catalogues || Object.keys(next.catalogues).length === 0) {
    next.catalogues = loadDefaultCatalogues();
  }
  migrateAutoGeneratedFittingBlockers(next);
  migrateAutoGeneratedSupports(next);
  // sites / buildings / floors / zones / systems are intentionally left
  // undefined — the UI handles their absence and treats the project as a
  // single-sheet drawing rather than a whole-site project.
  // penetrationSeals / itpItems / markups likewise stay undefined;
  // introducing empty records would burden every consumer with a "show
  // empty list" branch.
  return next;
}

function isOpenContainment(containment: ContainmentEntity): boolean {
  return (
    containment.containmentType === 'tray' ||
    containment.containmentType === 'basket' ||
    containment.containmentType === 'ladder'
  );
}

function migrateAutoGeneratedFittingBlockers(project: Project): void {
  for (const sheet of Object.values(project.sheets)) {
    const containments = new Map<string, ContainmentEntity>();
    for (const entity of Object.values(sheet.entities)) {
      if (entity?.kind === 'containment') containments.set(entity.id, entity);
    }

    const staleIds: string[] = [];
    for (const entity of Object.values(sheet.entities)) {
      if (entity?.kind !== 'fitting' || !entity.autoGenerated) continue;
      const fitting = entity as FittingEntity;
      if (fitting.fittingKind !== 'end-cap' && fitting.fittingKind !== 'end-plate') continue;
      const parent = containments.get(fitting.containmentId);
      if (!parent) continue;
      if (isOpenContainment(parent)) {
        staleIds.push(fitting.id);
        continue;
      }
      const connected = Array.from(containments.values()).some((containment) => (
        containment.id !== parent.id && containmentTouchesPoint(containment, fitting.position)
      ));
      if (connected) staleIds.push(fitting.id);
    }

    if (staleIds.length === 0) continue;
    const stale = new Set(staleIds);
    for (const id of stale) delete sheet.entities[id];
    sheet.entityOrder = sheet.entityOrder.filter((id) => !stale.has(id));
  }
}

function migrateAutoGeneratedSupports(project: Project): void {
  for (const sheet of Object.values(project.sheets)) {
    const containments = new Map<string, ContainmentEntity>();
    for (const entity of Object.values(sheet.entities)) {
      if (entity?.kind === 'containment') containments.set(entity.id, entity);
    }
    for (const entity of Object.values(sheet.entities)) {
      if (entity?.kind !== 'support' || !entity.autoGenerated) continue;
      const support = entity as SupportEntity;
      const parentId = support.supportingContainmentIds?.[0];
      const parent = parentId ? containments.get(parentId) : undefined;
      if (!parent) continue;
      support.supportKind = pickSupportKind(parent);
      if (support.supportKind === 'trapeze-hanger') {
        support.rodLength ??= 500;
        support.channelLength = trapezeChannelLength(parent.width ?? 200);
      }
    }
  }
}

// Distinguishes "key was never written" (a normal first visit — stay quiet)
// from "key held data we could not use" (potential data loss — the user must
// be told before the app falls back to a fresh sample).
type StoredReadResult =
  | { status: 'ok'; project: Project; raw: string; repairs: string[] }
  | { status: 'absent' }
  | { status: 'damaged' };

function readKey(key: string): StoredReadResult {
  let raw: string | null = null;
  try {
    raw = localStorage.getItem(key);
  } catch {
    // Storage itself is unavailable (private mode, disabled) — there is no
    // stored data to lose, so treat it like a first visit.
    return { status: 'absent' };
  }
  if (!raw) return { status: 'absent' };
  try {
    const parsed = JSON.parse(raw);
    // Safe repairs first (drop dangling order ids, rebuild derivable
    // fields), then the hard structural check — same order as File → Open.
    const repairs = repairProjectStructure(parsed);
    const defects = projectStructureDefects(parsed);
    if (defects.length > 0) {
      console.warn(`[opencad] stored project under "${key}" failed validation: ${defects.join('; ')}`);
      return { status: 'damaged' };
    }
    if (repairs.length > 0) {
      console.warn(`[opencad] stored project under "${key}" needed repairs: ${repairs.join('; ')}`);
    }
    return { status: 'ok', project: parsed as Project, raw, repairs };
  } catch {
    console.warn(`[opencad] stored project under "${key}" is not valid JSON`);
    return { status: 'damaged' };
  }
}

export function loadStoredProject(): Project | null {
  // Try the current key first.
  const current = readKey(STORAGE_KEY);
  if (current.status === 'ok') {
    // Backup policy: the last-known-good copy is refreshed here, on
    // validated load, rather than on every successful save. A load happens
    // once per session and the blob has just proven it parses and
    // validates, so this costs one localStorage write per launch instead of
    // one per autosave tick (autosave fires every few hundred ms while the
    // user works) — that keeps the quota pressure of holding two copies
    // bounded while still guaranteeing every session starts with a
    // restorable backup. The identical-value check skips the write on the
    // common nothing-changed reload. saveStoredProject additionally copies
    // the main blob aside before refusing to overwrite it with an invalid
    // in-memory project, so mid-session corruption is covered too.
    try {
      if (localStorage.getItem(BACKUP_KEY) !== current.raw) {
        localStorage.setItem(BACKUP_KEY, current.raw);
      }
    } catch {
      // Best-effort — quota pressure here must never block loading.
    }
    if (current.repairs.length > 0) {
      notify('warning', 'Autosaved project needed minor repairs', {
        detail: current.repairs.join('; '),
        id: 'autosave-repairs',
      });
    }
    return migrateProject(current.project);
  }

  // The main key is gone or damaged — prefer the backup copy (newer than
  // any legacy key) and tell the user what happened. notify() is safe here:
  // toasts queue until the Toast UI mounts.
  const backup = readKey(BACKUP_KEY);
  if (backup.status === 'ok') {
    notify('warning', 'Restored project from backup autosave', {
      detail: 'The most recent autosave was missing or damaged, so the last good backup copy was loaded instead.',
    });
    return migrateProject(backup.project);
  }

  // Track whether any slot held data we could not use, so the no-result
  // path below can distinguish data loss from a plain first visit.
  let sawDamage = current.status === 'damaged' || backup.status === 'damaged';

  // Fall back to legacy keys, run the migration shim, then evict the
  // legacy entry so the next save lands on the new key cleanly.
  for (const key of LEGACY_KEYS) {
    const legacy = readKey(key);
    if (legacy.status === 'absent') continue;
    if (legacy.status === 'damaged') {
      sawDamage = true;
      continue;
    }
    const migrated = migrateProject(legacy.project);
    try {
      localStorage.removeItem(key);
    } catch {
      // ignore
    }
    if (sawDamage) {
      // The recent autosave was damaged but an older save survived — still
      // worth a heads-up, since recent work may be missing from it.
      notify('warning', 'Restored an older saved project', {
        detail: 'The most recent autosave was damaged, so an older saved copy was loaded instead. Recent changes may be missing.',
      });
    }
    return migrated;
  }

  // Nothing restorable. On a true first visit (no stored data anywhere)
  // stay silent — the caller loads the bundled sample as normal. But if a
  // stored project existed and could not be read, the user is about to see
  // a fresh canvas where their work used to be: never let that happen
  // without an explanation.
  if (sawDamage) {
    notify('error', 'Stored project could not be restored', {
      detail:
        'The autosaved project in browser storage was damaged and no usable backup was found. ' +
        'A sample project will be loaded instead — if you previously downloaded a copy, use File → Open to restore it.',
    });
  }
  return null;
}

export interface SaveResult {
  ok: boolean;
  reason?: 'quota' | 'unavailable' | 'unknown' | 'invalid';
  bytes?: number;
}

// Stable toast id so repeated failures replace the toast in place instead of
// stacking — autosave fires every few hundred ms while the user works.
const AUTOSAVE_TOAST_ID = 'autosave-failure';

// Per-reason copy for the failure toast and the status-bar indicator. The
// toast message tells the user what to do (File → Save downloads a copy);
// the short label feeds the status bar's "Not saved — …" text.
const FAILURE_COPY: Record<NonNullable<SaveResult['reason']>, { short: string; message: string; detail: string }> = {
  quota: {
    short: 'storage full',
    message: 'Autosave failed — browser storage is full',
    detail: 'Your latest changes are not saved. Use File → Save to download a copy, then free up browser storage.',
  },
  unavailable: {
    short: 'storage unavailable',
    message: 'Autosave failed — browser storage is unavailable',
    detail: 'Use File → Save to download a copy of your project.',
  },
  unknown: {
    short: 'save failed',
    message: 'Autosave failed — project could not be serialised',
    detail: 'Use File → Save to download a copy of your project.',
  },
  invalid: {
    short: 'project damaged',
    message: 'Autosave suspended — the project in memory is damaged',
    detail: 'Your last good autosave was kept instead of being overwritten. Use File → Save to download what is currently in memory, then reload to return to the last good copy.',
  },
};

function reportSaveFailure(reason: NonNullable<SaveResult['reason']>, bytes?: number): void {
  const copy = FAILURE_COPY[reason];
  markSaveError(copy.short);
  // Sticky (errors default to no timeout) and deduped via the stable id —
  // the user sees one toast no matter how many saves fail behind it.
  notify('error', copy.message, { detail: copy.detail, id: AUTOSAVE_TOAST_ID });
  console.warn(`[opencad] autosave failed (${reason}${bytes !== undefined ? `, ${bytes} bytes` : ''}). ${copy.detail}`);
}

export function saveStoredProject(p: Project): SaveResult {
  markSaving();
  // Never overwrite the last good autosave with a structurally broken
  // project — readKey would reject the blob on the next launch anyway, so
  // writing it only destroys the previous good copy. Instead we copy the
  // current good blob to the backup key (belt-and-braces in case anything
  // else writes the main key) and surface a sticky failure toast.
  const defects = projectStructureDefects(p);
  if (defects.length > 0) {
    try {
      const lastGood = localStorage.getItem(STORAGE_KEY);
      if (lastGood) localStorage.setItem(BACKUP_KEY, lastGood);
    } catch {
      // The backup copy is best-effort — the refusal to overwrite below is
      // what actually protects the main key.
    }
    reportSaveFailure('invalid');
    console.warn(`[opencad] autosave refused — project failed validation: ${defects.join('; ')}`);
    return { ok: false, reason: 'invalid' };
  }
  // Strip the catalogues before serialising — they're 100KB+ of static
  // product data we re-load from the bundle on the next visit. Cuts the
  // typical save from ~250KB to ~150KB and leaves more room before
  // hitting the localStorage 5MB quota.
  const { catalogues: _omit, ...stripped } = p;
  let serialized = '';
  try {
    serialized = JSON.stringify(stripped);
  } catch {
    reportSaveFailure('unknown');
    return { ok: false, reason: 'unknown' };
  }
  try {
    localStorage.setItem(STORAGE_KEY, serialized);
    markSaved();
    // Clear a lingering failure toast once saving recovers, but only if one
    // is actually showing — dismiss() rebuilds the toast array, and autosave
    // runs far too often to churn the store on every success.
    if (useNotifications.getState().toasts.some((t) => t.id === AUTOSAVE_TOAST_ID)) {
      dismissNotification(AUTOSAVE_TOAST_ID);
    }
    return { ok: true, bytes: serialized.length };
  } catch (err) {
    const isQuota =
      err instanceof DOMException &&
      // Various browsers report quota differently — name covers Firefox/Safari/Chromium.
      (err.name === 'QuotaExceededError' ||
        err.name === 'NS_ERROR_DOM_QUOTA_REACHED' ||
        err.code === 22 ||
        err.code === 1014);
    const reason = isQuota ? 'quota' : 'unavailable';
    reportSaveFailure(reason, serialized.length);
    return isQuota
      ? { ok: false, reason, bytes: serialized.length }
      : { ok: false, reason };
  }
}

export function clearStoredProject(): void {
  try {
    localStorage.removeItem(STORAGE_KEY);
    localStorage.removeItem(BACKUP_KEY);
    for (const key of LEGACY_KEYS) localStorage.removeItem(key);
  } catch {
    // ignore
  }
}
