import type { ContainmentEntity, FittingEntity, Project, SupportEntity } from '../types';
import { emptyCableSchedule } from '../models/cable';
import { DEFAULT_STANDARDS } from '../models/standards';
import { loadDefaultCatalogues } from '../data/catalogues';
import { pickSupportKind, placeSupportsForContainment, trapezeChannelLength } from '../lib/support-placer';
import { containmentTouchesPoint } from '../lib/fittings';

// Bump this whenever the bundled sample project changes meaningfully —
// users with an autosave from a previous demo will skip it and load the
// new sample on next reload.
const STORAGE_KEY = 'opencad.project.v7';
// Older keys are read once for migration and then evicted, so users with
// a v5 (or earlier) save aren't dropped back to a fresh demo.
const LEGACY_KEYS = ['opencad.project.v6', 'opencad.project.v5', 'opencad.project.v4'];

const GALV_CONTAINMENT_COLOR = '#bcc1c8';
const PLANT_LADDER_Y = 9000;
const PLANT_POWER_BRANCH_Y = 7200;
const PLANT_DATA_BASKET_Y = 11200;
const PLANT_DATA_ENTRY_DOGLEG_Y = 11350;

// Apply migrations to projects saved by older app versions. Whole-site
// fields are optional in the type, so the migration is mostly about
// filling in derived defaults so downstream code can stop guarding for
// `undefined` on long-lived fields like the cable schedule and standards
// profile.
function migrateProject(parsed: Project): Project {
  const next: Project = { ...parsed };
  if (!next.cableSchedule) next.cableSchedule = emptyCableSchedule();
  if (!next.standardsProfile) next.standardsProfile = DEFAULT_STANDARDS.BS7671;
  // Catalogues are large but bundled with the app — we always rehydrate
  // them so the Catalogue Browser populates after a reload (saved
  // projects don't need to round-trip 366 products through localStorage).
  if (!next.catalogues || Object.keys(next.catalogues).length === 0) {
    next.catalogues = loadDefaultCatalogues();
  }
  migrateWholeSiteDemoTrunking(next);
  migrateWholeSiteDemoPlantLanes(next);
  migrateAutoGeneratedFittingBlockers(next);
  migrateAutoGeneratedSupports(next);
  // sites / buildings / floors / zones / systems are intentionally left
  // undefined — the UI handles their absence and treats the project as a
  // single-sheet drawing rather than a whole-site project.
  // penetrationSeals / itpItems / markups likewise stay undefined;
  // introducing empty records would burden every consumer with a "show
  // empty list" branch.
  return next;
}

function migrateWholeSiteDemoTrunking(project: Project): void {
  if (project.name !== 'Whole-Site Containment Demo' && project.name !== 'Building Containment Demo') return;
  for (const sheet of Object.values(project.sheets)) {
    for (const entity of Object.values(sheet.entities)) {
      if (entity?.kind === 'containment') {
        const containment = entity as ContainmentEntity;
        if (containment.label === 'Lighting feeder trunking — 150×100') {
          containment.containmentType = 'basket';
          containment.label = 'Lighting basket — 150×100';
          containment.color = GALV_CONTAINMENT_COLOR;
        }
        if (
          containment.containmentType === 'trunking' &&
          containment.width === 400 &&
          containment.height === 250 &&
          (containment.cableCategory == null || containment.cableCategory === 'power')
        ) {
          containment.width = 100;
          containment.height = 100;
          if (containment.label === 'Main power trunking — 400×250') {
            containment.label = 'Main power trunking — 100×100';
          }
        }
        if (containment.containmentType === 'trunking') {
          containment.color = GALV_CONTAINMENT_COLOR;
        }
      } else if (
        entity?.kind === 'leader' &&
        (entity as { text?: string }).text === 'Main power trunking — 400×250'
      ) {
        (entity as { text: string }).text = 'Main power trunking — 100×100';
      }
    }
  }
}

function setPointY(containment: ContainmentEntity, index: number, y: number): boolean {
  const point = containment.points[index];
  if (!point || point.y === y) return false;
  point.y = y;
  return true;
}

function rewritePlantBranch(
  containment: ContainmentEntity,
  branchY: number,
): boolean {
  if (containment.points.length < 4) return false;
  let changed = false;
  changed ||= setPointY(containment, 0, PLANT_LADDER_Y);
  changed ||= setPointY(containment, 1, branchY);
  changed ||= setPointY(containment, 2, branchY);
  return changed;
}

function removeAutoSupportsFor(sheet: Project['sheets'][string], containmentIds: Set<string>): void {
  if (containmentIds.size === 0) return;
  const staleIds = new Set<string>();
  for (const id of sheet.entityOrder) {
    const entity = sheet.entities[id];
    if (
      entity?.kind === 'support' &&
      entity.autoGenerated &&
      entity.supportingContainmentIds.some((cid) => containmentIds.has(cid))
    ) {
      staleIds.add(id);
    }
  }
  if (staleIds.size === 0) return;
  for (const id of staleIds) delete sheet.entities[id];
  sheet.entityOrder = sheet.entityOrder.filter((id) => !staleIds.has(id));
}

function regenerateAutoSupportsFor(sheet: Project['sheets'][string], containmentIds: Set<string>): void {
  for (const containmentId of containmentIds) {
    const containment = sheet.entities[containmentId];
    if (containment?.kind !== 'containment') continue;
    const supports = placeSupportsForContainment(containment);
    for (const support of supports) {
      sheet.entities[support.id] = support;
      sheet.entityOrder.push(support.id);
    }
  }
}

function migrateWholeSiteDemoPlantLanes(project: Project): void {
  if (project.name !== 'Whole-Site Containment Demo' && project.name !== 'Building Containment Demo') return;

  for (const sheet of Object.values(project.sheets)) {
    const changedContainments = new Set<string>();

    for (const entity of Object.values(sheet.entities)) {
      if (entity?.kind !== 'containment') continue;
      const containment = entity as ContainmentEntity;
      let changed = false;

      if (containment.label === 'Data basket — 300 mm') {
        for (let i = 0; i < containment.points.length; i++) {
          changed ||= setPointY(containment, i, PLANT_DATA_BASKET_Y);
        }
      } else if (containment.label === 'Branch to CAB-PL-G') {
        changed ||= setPointY(containment, 0, PLANT_DATA_BASKET_Y);
        changed ||= setPointY(containment, 1, PLANT_DATA_BASKET_Y);
      } else if (
        containment.label === 'MCC-room sub-main feeder' ||
        containment.label === 'Branch to DB-PL-D'
      ) {
        changed ||= rewritePlantBranch(containment, PLANT_POWER_BRANCH_Y);
      } else if (containment.label === 'Plant data duct entry sleeve') {
        changed ||= setPointY(containment, 0, 9300);
        changed ||= setPointY(containment, 1, PLANT_DATA_ENTRY_DOGLEG_Y);
        changed ||= setPointY(containment, 2, PLANT_DATA_ENTRY_DOGLEG_Y);
        changed ||= setPointY(containment, 3, PLANT_DATA_BASKET_Y);
      }

      if (changed) changedContainments.add(containment.id);
    }

    removeAutoSupportsFor(sheet, changedContainments);
    regenerateAutoSupportsFor(sheet, changedContainments);
  }
}

function isOpenContainment(containment: ContainmentEntity): boolean {
  return (
    containment.containmentType === 'tray' ||
    containment.containmentType === 'basket' ||
    containment.containmentType === 'ladder'
  );
}

function migrateAutoGeneratedFittingBlockers(project: Project): void {
  for (const sheet of Object.values(project.sheets)) {
    const containments = new Map<string, ContainmentEntity>();
    for (const entity of Object.values(sheet.entities)) {
      if (entity?.kind === 'containment') containments.set(entity.id, entity);
    }

    const staleIds: string[] = [];
    for (const entity of Object.values(sheet.entities)) {
      if (entity?.kind !== 'fitting' || !entity.autoGenerated) continue;
      const fitting = entity as FittingEntity;
      if (fitting.fittingKind !== 'end-cap' && fitting.fittingKind !== 'end-plate') continue;
      const parent = containments.get(fitting.containmentId);
      if (!parent) continue;
      if (isOpenContainment(parent)) {
        staleIds.push(fitting.id);
        continue;
      }
      const connected = Array.from(containments.values()).some((containment) => (
        containment.id !== parent.id && containmentTouchesPoint(containment, fitting.position)
      ));
      if (connected) staleIds.push(fitting.id);
    }

    if (staleIds.length === 0) continue;
    const stale = new Set(staleIds);
    for (const id of stale) delete sheet.entities[id];
    sheet.entityOrder = sheet.entityOrder.filter((id) => !stale.has(id));
  }
}

function migrateAutoGeneratedSupports(project: Project): void {
  for (const sheet of Object.values(project.sheets)) {
    const containments = new Map<string, ContainmentEntity>();
    for (const entity of Object.values(sheet.entities)) {
      if (entity?.kind === 'containment') containments.set(entity.id, entity);
    }
    for (const entity of Object.values(sheet.entities)) {
      if (entity?.kind !== 'support' || !entity.autoGenerated) continue;
      const support = entity as SupportEntity;
      const parentId = support.supportingContainmentIds?.[0];
      const parent = parentId ? containments.get(parentId) : undefined;
      if (!parent) continue;
      support.supportKind = pickSupportKind(parent);
      if (support.supportKind === 'trapeze-hanger') {
        support.rodLength ??= 500;
        support.channelLength = trapezeChannelLength(parent.width ?? 200);
      }
    }
  }
}

function readKey(key: string): Project | null {
  try {
    const raw = localStorage.getItem(key);
    if (!raw) return null;
    const parsed = JSON.parse(raw) as Project;
    if (!parsed || !parsed.id || !parsed.sheets || !parsed.sheetOrder) return null;
    return parsed;
  } catch {
    return null;
  }
}

export function loadStoredProject(): Project | null {
  // Try the current key first.
  const current = readKey(STORAGE_KEY);
  if (current) return migrateProject(current);

  // Fall back to legacy keys, run the migration shim, then evict the
  // legacy entry so the next save lands on the new key cleanly.
  for (const key of LEGACY_KEYS) {
    const legacy = readKey(key);
    if (!legacy) continue;
    const migrated = migrateProject(legacy);
    try {
      localStorage.removeItem(key);
    } catch {
      // ignore
    }
    return migrated;
  }
  return null;
}

export interface SaveResult {
  ok: boolean;
  reason?: 'quota' | 'unavailable' | 'unknown';
  bytes?: number;
}

let quotaWarned = false;

export function saveStoredProject(p: Project): SaveResult {
  // Strip the catalogues before serialising — they're 100KB+ of static
  // product data we re-load from the bundle on the next visit. Cuts the
  // typical save from ~250KB to ~150KB and leaves more room before
  // hitting the localStorage 5MB quota.
  const { catalogues: _omit, ...stripped } = p;
  let serialized = '';
  try {
    serialized = JSON.stringify(stripped);
  } catch {
    return { ok: false, reason: 'unknown' };
  }
  try {
    localStorage.setItem(STORAGE_KEY, serialized);
    return { ok: true, bytes: serialized.length };
  } catch (err) {
    const isQuota =
      err instanceof DOMException &&
      // Various browsers report quota differently — name covers Firefox/Safari/Chromium.
      (err.name === 'QuotaExceededError' ||
        err.name === 'NS_ERROR_DOM_QUOTA_REACHED' ||
        err.code === 22 ||
        err.code === 1014);
    if (isQuota) {
      if (!quotaWarned) {
        quotaWarned = true;
        // Tell the user once per session — repeated alerts on every keystroke
        // would be its own kind of bug.
        console.warn(`[opencad] localStorage full (${serialized.length} bytes). Autosave is paused until you free space or save the project to disk via File → Save.`);
      }
      return { ok: false, reason: 'quota', bytes: serialized.length };
    }
    return { ok: false, reason: 'unavailable' };
  }
}

export function clearStoredProject(): void {
  try {
    localStorage.removeItem(STORAGE_KEY);
    for (const key of LEGACY_KEYS) localStorage.removeItem(key);
    quotaWarned = false;
  } catch {
    // ignore
  }
}
