/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.collab.jsonc --include-runtime=false worker/worker-configuration.d.ts` (hash: 6dd942a64d04145c67326e89a12da93f)
interface __BaseEnv_Env {
	ACCESS_TEAM_DOMAIN: "https://fightingentropy.cloudflareaccess.com";
	ACCESS_AUD: "ea7d51e81a3c224451e7c81b4c8c6a17882911c455c56259db178201fe740aea";
	ALLOWED_ORIGINS: "https://opencad.pages.dev";
	COLLAB_ROOM: DurableObjectNamespace<import("./src/index").CollaborationRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "CollaborationRoom";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ACCESS_TEAM_DOMAIN" | "ACCESS_AUD" | "ALLOWED_ORIGINS">> {}
}
