// Sample cable schedule data — produces a representative selection of
// cables for a multi-floor commercial / light-industrial project. Used by
// the whole-site sample, but exported standalone so a fresh project can
// also pull in a starter schedule for testing the cable schedule UI.

import { nanoid } from 'nanoid';
import type {
  Cable,
  CableConstruction,
  CableSchedule,
  CableCircuitType,
} from './models/cable';
import { emptyCableSchedule } from './models/cable';

const newCableId = (): string => nanoid(10);

export interface SampleCableRefs {
  // Equipment tag to entity-id map. Optional — when absent we leave
  // fromEntityId / toEntityId undefined and rely on the free-text from/to.
  byTag?: Record<string, string>;
  // System-id map keyed by simple system kind.
  systems?: {
    powerDistribution?: string;
    lighting?: string;
    fireAlarm?: string;
    data?: string;
    emergencyLighting?: string;
    security?: string;
    bms?: string;
  };
}

interface CableTemplate {
  ref: string;
  description: string;
  from: string;
  to: string;
  circuitType: CableCircuitType;
  construction: CableConstruction;
  cores: number;
  csa: number;
  hasEarth: boolean;
  earthCsa?: number;
  outerDiameter: number;
  voltage: number;
  designCurrent?: number;
  protectiveDevice?: string;
  protectiveDeviceRating?: number;
  estimatedLength?: number;
  systemKey?: keyof NonNullable<SampleCableRefs['systems']>;
}

// Representative cables for the corporate HQ sample: incomers, floor
// sub-mains, final circuits, life-safety loops, data backbone, security,
// BMS and roof plant feeds. References follow a consistent project
// numbering scheme: <type>-<from>-<to>-<seq>.
const TEMPLATES: CableTemplate[] = [
  // ---- LV incomer, busbar riser and floor distribution ----
  {
    ref: 'PW-TX-MSB-001',
    description: '11 kV/400 V transformer to main LV switchboard',
    from: 'TX-01',
    to: 'MSB-01',
    circuitType: 'power',
    construction: 'XLPE/SWA/LSOH',
    cores: 4,
    csa: 300,
    hasEarth: true,
    earthCsa: 120,
    outerDiameter: 64,
    voltage: 1000,
    designCurrent: 520,
    protectiveDevice: 'ACB 800A',
    protectiveDeviceRating: 800,
    estimatedLength: 24,
    systemKey: 'powerDistribution',
  },
  {
    ref: 'PW-MSB-DBLG-001',
    description: 'MSB sub-main to ground floor DB',
    from: 'MSB-01',
    to: 'DB-LG',
    circuitType: 'power',
    construction: 'XLPE/SWA/LSOH',
    cores: 4,
    csa: 95,
    hasEarth: true,
    earthCsa: 50,
    outerDiameter: 36,
    voltage: 1000,
    designCurrent: 180,
    protectiveDevice: 'MCCB 250A',
    protectiveDeviceRating: 250,
    estimatedLength: 42,
    systemKey: 'powerDistribution',
  },
  {
    ref: 'PW-MSB-DBL01-002',
    description: 'MSB busbar tap to Level 1 DB',
    from: 'MSB-01',
    to: 'DB-L01',
    circuitType: 'power',
    construction: 'XLPE/SWA/LSOH',
    cores: 4,
    csa: 95,
    hasEarth: true,
    earthCsa: 50,
    outerDiameter: 36,
    voltage: 1000,
    designCurrent: 180,
    protectiveDevice: 'MCCB 250A',
    protectiveDeviceRating: 250,
    estimatedLength: 58,
    systemKey: 'powerDistribution',
  },
  {
    ref: 'PW-MSB-DBL02-003',
    description: 'MSB busbar tap to Level 2 DB',
    from: 'MSB-01',
    to: 'DB-L02',
    circuitType: 'power',
    construction: 'XLPE/SWA/LSOH',
    cores: 4,
    csa: 95,
    hasEarth: true,
    earthCsa: 50,
    outerDiameter: 36,
    voltage: 1000,
    designCurrent: 175,
    protectiveDevice: 'MCCB 250A',
    protectiveDeviceRating: 250,
    estimatedLength: 74,
    systemKey: 'powerDistribution',
  },
  {
    ref: 'PW-MSB-DBL03-004',
    description: 'MSB busbar tap to Level 3 DB',
    from: 'MSB-01',
    to: 'DB-L03',
    circuitType: 'power',
    construction: 'XLPE/SWA/LSOH',
    cores: 4,
    csa: 95,
    hasEarth: true,
    earthCsa: 50,
    outerDiameter: 36,
    voltage: 1000,
    designCurrent: 175,
    protectiveDevice: 'MCCB 250A',
    protectiveDeviceRating: 250,
    estimatedLength: 91,
    systemKey: 'powerDistribution',
  },
  {
    ref: 'PW-MSB-DBRF-005',
    description: 'MSB busbar tap to roof plant DB',
    from: 'MSB-01',
    to: 'DB-RF',
    circuitType: 'power',
    construction: 'XLPE/SWA/LSOH',
    cores: 4,
    csa: 120,
    hasEarth: true,
    earthCsa: 70,
    outerDiameter: 42,
    voltage: 1000,
    designCurrent: 220,
    protectiveDevice: 'MCCB 250A',
    protectiveDeviceRating: 250,
    estimatedLength: 118,
    systemKey: 'powerDistribution',
  },
  // ---- Lighting circuits ----
  {
    ref: 'LT-DBLG-LG-001',
    description: 'Ground floor general lighting circuit',
    from: 'DB-LG',
    to: 'LT-LG-01',
    circuitType: 'power',
    construction: 'PVC/PVC',
    cores: 3,
    csa: 2.5,
    hasEarth: true,
    earthCsa: 1.5,
    outerDiameter: 9,
    voltage: 230,
    designCurrent: 8,
    protectiveDevice: 'MCB B16',
    protectiveDeviceRating: 16,
    estimatedLength: 32,
    systemKey: 'lighting',
  },
  {
    ref: 'LT-DBL01-001',
    description: 'Level 1 general lighting circuit',
    from: 'DB-L01',
    to: 'LT-L01-01',
    circuitType: 'power',
    construction: 'PVC/PVC',
    cores: 3,
    csa: 2.5,
    hasEarth: true,
    earthCsa: 1.5,
    outerDiameter: 9,
    voltage: 230,
    designCurrent: 9,
    protectiveDevice: 'MCB B16',
    protectiveDeviceRating: 16,
    estimatedLength: 38,
    systemKey: 'lighting',
  },
  {
    ref: 'LT-DBL02-001',
    description: 'Level 2 general lighting circuit',
    from: 'DB-L02',
    to: 'LT-L02-01',
    circuitType: 'power',
    construction: 'PVC/PVC',
    cores: 3,
    csa: 2.5,
    hasEarth: true,
    earthCsa: 1.5,
    outerDiameter: 9,
    voltage: 230,
    designCurrent: 9,
    protectiveDevice: 'MCB B16',
    protectiveDeviceRating: 16,
    estimatedLength: 36,
    systemKey: 'lighting',
  },
  {
    ref: 'LT-DBL03-001',
    description: 'Level 3 client suite lighting circuit',
    from: 'DB-L03',
    to: 'LT-L03-01',
    circuitType: 'power',
    construction: 'PVC/PVC',
    cores: 3,
    csa: 2.5,
    hasEarth: true,
    earthCsa: 1.5,
    outerDiameter: 9,
    voltage: 230,
    designCurrent: 9,
    protectiveDevice: 'MCB B16',
    protectiveDeviceRating: 16,
    estimatedLength: 40,
    systemKey: 'lighting',
  },
  // ---- Small power / sockets ----
  {
    ref: 'PW-DBLG-SK-LG',
    description: 'Ground floor ring final circuit',
    from: 'DB-LG',
    to: 'SK-LG-RING',
    circuitType: 'power',
    construction: 'PVC/PVC',
    cores: 3,
    csa: 2.5,
    hasEarth: true,
    earthCsa: 1.5,
    outerDiameter: 9,
    voltage: 230,
    designCurrent: 26,
    protectiveDevice: 'MCB B32',
    protectiveDeviceRating: 32,
    estimatedLength: 55,
    systemKey: 'powerDistribution',
  },
  {
    ref: 'PW-DBL01-SK-RING',
    description: 'Level 1 ring final circuit',
    from: 'DB-L01',
    to: 'SK-L01-RING',
    circuitType: 'power',
    construction: 'PVC/PVC',
    cores: 3,
    csa: 2.5,
    hasEarth: true,
    earthCsa: 1.5,
    outerDiameter: 9,
    voltage: 230,
    designCurrent: 28,
    protectiveDevice: 'MCB B32',
    protectiveDeviceRating: 32,
    estimatedLength: 58,
    systemKey: 'powerDistribution',
  },
  {
    ref: 'PW-DBL02-SK-RING',
    description: 'Level 2 ring final circuit',
    from: 'DB-L02',
    to: 'SK-L02-RING',
    circuitType: 'power',
    construction: 'PVC/PVC',
    cores: 3,
    csa: 2.5,
    hasEarth: true,
    earthCsa: 1.5,
    outerDiameter: 9,
    voltage: 230,
    designCurrent: 28,
    protectiveDevice: 'MCB B32',
    protectiveDeviceRating: 32,
    estimatedLength: 62,
    systemKey: 'powerDistribution',
  },
  {
    ref: 'PW-DBL03-SK-RING',
    description: 'Level 3 ring final circuit',
    from: 'DB-L03',
    to: 'SK-L03-RING',
    circuitType: 'power',
    construction: 'PVC/PVC',
    cores: 3,
    csa: 2.5,
    hasEarth: true,
    earthCsa: 1.5,
    outerDiameter: 9,
    voltage: 230,
    designCurrent: 24,
    protectiveDevice: 'MCB B32',
    protectiveDeviceRating: 32,
    estimatedLength: 60,
    systemKey: 'powerDistribution',
  },
  // ---- Roof plant and generation ----
  {
    ref: 'PW-DBRF-AHU01',
    description: 'Roof AHU-RF-01 motor feed',
    from: 'DB-RF',
    to: 'AHU-RF-01',
    circuitType: 'power',
    construction: 'XLPE/SWA/LSOH',
    cores: 4,
    csa: 16,
    hasEarth: true,
    earthCsa: 16,
    outerDiameter: 19,
    voltage: 400,
    designCurrent: 38,
    protectiveDevice: 'MCCB 50A',
    protectiveDeviceRating: 50,
    estimatedLength: 28,
    systemKey: 'powerDistribution',
  },
  {
    ref: 'PW-DBRF-AHU02',
    description: 'Roof AHU-RF-02 motor feed',
    from: 'DB-RF',
    to: 'AHU-RF-02',
    circuitType: 'power',
    construction: 'XLPE/SWA/LSOH',
    cores: 4,
    csa: 16,
    hasEarth: true,
    earthCsa: 16,
    outerDiameter: 19,
    voltage: 400,
    designCurrent: 38,
    protectiveDevice: 'MCCB 50A',
    protectiveDeviceRating: 50,
    estimatedLength: 45,
    systemKey: 'powerDistribution',
  },
  {
    ref: 'PW-DBRF-CHWP01',
    description: 'Roof chilled-water pump package feed',
    from: 'DB-RF',
    to: 'CHWP-RF-01',
    circuitType: 'power',
    construction: 'XLPE/SWA/LSOH',
    cores: 4,
    csa: 6,
    hasEarth: true,
    earthCsa: 6,
    outerDiameter: 14,
    voltage: 400,
    designCurrent: 14,
    protectiveDevice: 'MCB C20',
    protectiveDeviceRating: 20,
    estimatedLength: 22,
    systemKey: 'powerDistribution',
  },
  {
    ref: 'PW-PV-INV-DBRF',
    description: 'PV inverter AC connection to roof plant DB',
    from: 'PV-INV-01',
    to: 'DB-RF',
    circuitType: 'power',
    construction: 'XLPE/SWA/LSOH',
    cores: 4,
    csa: 25,
    hasEarth: true,
    earthCsa: 16,
    outerDiameter: 23,
    voltage: 400,
    designCurrent: 72,
    protectiveDevice: 'MCCB 100A',
    protectiveDeviceRating: 100,
    estimatedLength: 32,
    systemKey: 'powerDistribution',
  },
  // ---- Fire alarm loop ----
  {
    ref: 'FA-PNL-LG',
    description: 'Ground floor fire alarm addressable loop',
    from: 'FAP-01',
    to: 'FA-LG-LOOP',
    circuitType: 'fire-alarm',
    construction: 'FP200',
    cores: 2,
    csa: 1.5,
    hasEarth: false,
    outerDiameter: 7,
    voltage: 50,
    designCurrent: 0.5,
    protectiveDevice: 'Loop card 1',
    estimatedLength: 145,
    systemKey: 'fireAlarm',
  },
  {
    ref: 'FA-PNL-L01',
    description: 'Level 1 fire alarm addressable loop',
    from: 'FAP-01',
    to: 'FA-L01-LOOP',
    circuitType: 'fire-alarm',
    construction: 'FP200',
    cores: 2,
    csa: 1.5,
    hasEarth: false,
    outerDiameter: 7,
    voltage: 50,
    designCurrent: 0.5,
    protectiveDevice: 'Loop card 2',
    estimatedLength: 155,
    systemKey: 'fireAlarm',
  },
  {
    ref: 'FA-PNL-L02',
    description: 'Level 2 fire alarm addressable loop',
    from: 'FAP-01',
    to: 'FA-L02-LOOP',
    circuitType: 'fire-alarm',
    construction: 'FP200',
    cores: 2,
    csa: 1.5,
    hasEarth: false,
    outerDiameter: 7,
    voltage: 50,
    designCurrent: 0.5,
    protectiveDevice: 'Loop card 3',
    estimatedLength: 170,
    systemKey: 'fireAlarm',
  },
  {
    ref: 'FA-PNL-L03',
    description: 'Level 3 fire alarm addressable loop',
    from: 'FAP-01',
    to: 'FA-L03-LOOP',
    circuitType: 'fire-alarm',
    construction: 'FP200',
    cores: 2,
    csa: 1.5,
    hasEarth: false,
    outerDiameter: 7,
    voltage: 50,
    designCurrent: 0.5,
    protectiveDevice: 'Loop card 4',
    estimatedLength: 185,
    systemKey: 'fireAlarm',
  },
  {
    ref: 'FA-PNL-RF',
    description: 'Roof plant fire alarm interface loop',
    from: 'FAP-01',
    to: 'FA-RF-01',
    circuitType: 'fire-alarm',
    construction: 'FP200',
    cores: 2,
    csa: 1.5,
    hasEarth: false,
    outerDiameter: 7,
    voltage: 50,
    designCurrent: 0.5,
    protectiveDevice: 'Loop card 5',
    estimatedLength: 210,
    systemKey: 'fireAlarm',
  },
  // ---- Emergency lighting ----
  {
    ref: 'EM-DBLG-LG-001',
    description: 'Ground floor emergency lighting circuit',
    from: 'DB-LG',
    to: 'EM-LG-01',
    circuitType: 'emergency',
    construction: 'FP200',
    cores: 3,
    csa: 1.5,
    hasEarth: true,
    earthCsa: 1.5,
    outerDiameter: 8,
    voltage: 230,
    designCurrent: 3,
    protectiveDevice: 'MCB B6',
    protectiveDeviceRating: 6,
    estimatedLength: 42,
    systemKey: 'emergencyLighting',
  },
  {
    ref: 'EM-DBL01-001',
    description: 'Level 1 emergency lighting circuit',
    from: 'DB-L01',
    to: 'EM-L01-01',
    circuitType: 'emergency',
    construction: 'FP200',
    cores: 3,
    csa: 1.5,
    hasEarth: true,
    earthCsa: 1.5,
    outerDiameter: 8,
    voltage: 230,
    designCurrent: 3,
    protectiveDevice: 'MCB B6',
    protectiveDeviceRating: 6,
    estimatedLength: 48,
    systemKey: 'emergencyLighting',
  },
  {
    ref: 'EM-DBL02-001',
    description: 'Level 2 emergency lighting circuit',
    from: 'DB-L02',
    to: 'EM-L02-01',
    circuitType: 'emergency',
    construction: 'FP200',
    cores: 3,
    csa: 1.5,
    hasEarth: true,
    earthCsa: 1.5,
    outerDiameter: 8,
    voltage: 230,
    designCurrent: 3,
    protectiveDevice: 'MCB B6',
    protectiveDeviceRating: 6,
    estimatedLength: 55,
    systemKey: 'emergencyLighting',
  },
  {
    ref: 'EM-DBL03-001',
    description: 'Level 3 emergency lighting circuit',
    from: 'DB-L03',
    to: 'EM-L03-01',
    circuitType: 'emergency',
    construction: 'FP200',
    cores: 3,
    csa: 1.5,
    hasEarth: true,
    earthCsa: 1.5,
    outerDiameter: 8,
    voltage: 230,
    designCurrent: 3,
    protectiveDevice: 'MCB B6',
    protectiveDeviceRating: 6,
    estimatedLength: 62,
    systemKey: 'emergencyLighting',
  },
  // ---- Data backbone ----
  {
    ref: 'DT-CR-IDFLG-OS2',
    description: 'Main comms room to ground floor IDF — fibre OS2',
    from: 'CR-01',
    to: 'IDF-LG',
    circuitType: 'data',
    construction: 'fibre-OS2',
    cores: 12,
    csa: 0.125,
    hasEarth: false,
    outerDiameter: 9,
    voltage: 0,
    estimatedLength: 38,
    systemKey: 'data',
  },
  {
    ref: 'DT-CR-IDFL01-OS2',
    description: 'Main comms room to Level 1 IDF — fibre OS2',
    from: 'CR-01',
    to: 'IDF-L01',
    circuitType: 'data',
    construction: 'fibre-OS2',
    cores: 12,
    csa: 0.125,
    hasEarth: false,
    outerDiameter: 9,
    voltage: 0,
    estimatedLength: 52,
    systemKey: 'data',
  },
  {
    ref: 'DT-CR-IDFL02-OS2',
    description: 'Main comms room to Level 2 IDF — fibre OS2',
    from: 'CR-01',
    to: 'IDF-L02',
    circuitType: 'data',
    construction: 'fibre-OS2',
    cores: 12,
    csa: 0.125,
    hasEarth: false,
    outerDiameter: 9,
    voltage: 0,
    estimatedLength: 66,
    systemKey: 'data',
  },
  {
    ref: 'DT-CR-IDFL03-OS2',
    description: 'Main comms room to Level 3 IDF — fibre OS2',
    from: 'CR-01',
    to: 'IDF-L03',
    circuitType: 'data',
    construction: 'fibre-OS2',
    cores: 12,
    csa: 0.125,
    hasEarth: false,
    outerDiameter: 9,
    voltage: 0,
    estimatedLength: 80,
    systemKey: 'data',
  },
  {
    ref: 'DT-IDFL03-AV-RACK',
    description: 'Level 3 IDF to client-suite AV rack — Cat 6A',
    from: 'IDF-L03',
    to: 'AV-L03-RACK',
    circuitType: 'data',
    construction: 'cat6a',
    cores: 4,
    csa: 0.5,
    hasEarth: false,
    outerDiameter: 8,
    voltage: 0,
    estimatedLength: 38,
    systemKey: 'data',
  },
  // ---- Security and BMS controls ----
  {
    ref: 'SEC-CP-L02-ACS',
    description: 'Security head-end to Level 2 access-control panel',
    from: 'SEC-CP-01',
    to: 'SEC-L02-ACS',
    circuitType: 'data',
    construction: 'cat6a',
    cores: 4,
    csa: 0.5,
    hasEarth: false,
    outerDiameter: 8,
    voltage: 0,
    estimatedLength: 90,
    systemKey: 'security',
  },
  {
    ref: 'BMS-CP-L02-VAV',
    description: 'BMS supervisor to Level 2 VAV controller panel',
    from: 'BMS-CP-01',
    to: 'BMS-L02-VAV',
    circuitType: 'instrumentation',
    construction: 'CY',
    cores: 2,
    csa: 1.5,
    hasEarth: false,
    outerDiameter: 8,
    voltage: 24,
    designCurrent: 1,
    protectiveDevice: 'BMS fused spur',
    estimatedLength: 92,
    systemKey: 'bms',
  },
  {
    ref: 'BMS-CP-RF-IO',
    description: 'BMS supervisor to roof plant I/O panel',
    from: 'BMS-CP-01',
    to: 'BMS-RF-IO',
    circuitType: 'instrumentation',
    construction: 'CY',
    cores: 4,
    csa: 1.5,
    hasEarth: false,
    outerDiameter: 10,
    voltage: 24,
    designCurrent: 1,
    protectiveDevice: 'BMS fused spur',
    estimatedLength: 130,
    systemKey: 'bms',
  },
];

export const createSampleCableSchedule = (
  refs: SampleCableRefs = {},
): CableSchedule => {
  const schedule = emptyCableSchedule();
  const tagMap = refs.byTag ?? {};
  const systems = refs.systems ?? {};
  for (const t of TEMPLATES) {
    const id = newCableId();
    const cable: Cable = {
      id,
      reference: t.ref,
      description: t.description,
      from: t.from,
      to: t.to,
      fromEntityId: tagMap[t.from],
      toEntityId: tagMap[t.to],
      systemId: t.systemKey ? systems[t.systemKey] : undefined,
      circuitType: t.circuitType,
      construction: t.construction,
      cores: t.cores,
      csa: t.csa,
      hasEarth: t.hasEarth,
      earthCsa: t.earthCsa,
      outerDiameter: t.outerDiameter,
      voltage: t.voltage,
      route: [],
      estimatedLength: t.estimatedLength,
      designCurrent: t.designCurrent,
      protectiveDevice: t.protectiveDevice,
      protectiveDeviceRating: t.protectiveDeviceRating,
      status: 'design',
    };
    schedule.cables[id] = cable;
    schedule.cableOrder.push(id);
  }
  return schedule;
};

// Convenience export — number of cables produced by the standard sample.
export const SAMPLE_CABLE_COUNT = TEMPLATES.length;
